import { useRouter } from 'next/router';
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { FormProvider, useForm } from 'react-hook-form';
import { useTranslate } from '~/i18n';
import cookie from 'js-cookie';
import { getStepsList } from '~/utils/getStepsList';
import dynamic from 'next/dynamic';
import { useMediaQuery } from 'react-responsive';

// import classNames from 'classnames';
import { renderFormSteps } from '~/utils/renderFormSteps';

const MenuSteps = dynamic(() => import('./menu-steps'), { ssr: false });
const MenuStepsMd = dynamic(() => import('./menu-steps-md'), { ssr: false });

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type JoinFormWrapperProps = {
   category: string;
   token?: string;

   guestEmail?: string | null;
   guestFirstName?: string | null;
   guestLastName?: string | null;
   guestCompany?: string | null;
   guestPosition?: string | null;
   prefilldata?: string | null;
   lock_data?: string | null;
   form_shape: string | null; // Form shape identifier
   optionalFields?: string[];
   mandatoryFields?: string[];
   residencyStatusTypes?: string[];
   withOtp: boolean;
   withSmsOtp: boolean;
   withAlternativeEmail: boolean;
};

const JoinFormWrapper = ({
   category,
   token,
   guestEmail,
   guestFirstName,
   guestLastName,
   guestCompany,
   guestPosition,
   prefilldata,
   lock_data,
   form_shape,
   optionalFields,
   mandatoryFields,
   residencyStatusTypes,
   withOtp,
   withSmsOtp,
   withAlternativeEmail,
}: JoinFormWrapperProps) => {
   const router = useRouter();
   const { lang } = useTranslate();

   const userData = cookie.get('user_data') && JSON.parse(cookie.get('user_data') as any);
   const formWrapperRef = useRef<any>(null);

   // Memoize steps to prevent unnecessary re-renders
   const steps = useMemo(() => getStepsList(category, form_shape), [category, form_shape]);

   const [step, setStep] = useState('');
   const role = category;

   const methods = useForm({
      mode: 'onChange',
      defaultValues: cookie.get('user_data') && JSON.parse(cookie.get('user_data') as any),
   });

   useEffect(() => {
      if (userData) {
         const savedStep = userData?.step;
         if (savedStep && steps.includes(savedStep)) {
            setStep(savedStep);
         } else if (steps && steps.length > 0) {
            setStep(steps[0]);
         }
      } else {
         if (role && steps && steps.length > 0) {
            setStep(steps[0]);
         }
      }
   }, [role, steps, userData]);

   // Reset form values when step changes to ensure form reflects cookie data
   // This ensures that when navigating back, form values are restored from cookie
   useEffect(() => {
      const cookieData = cookie.get('user_data');
      if (cookieData && step) {
         const parsedData = JSON.parse(cookieData);
         // Only reset if there are actual values to restore (avoid resetting to empty)
         if (Object.keys(parsedData).length > 1) {
            // More than just 'step' key
            // Reset form with cookie values to preserve data when navigating between steps
            methods.reset(parsedData, { keepDefaultValues: false });
         }
      }
   }, [step, methods]);

   const updateStep = useCallback(
      (step: string) => {
         // Get current form values before navigating
         const currentFormValues = methods.getValues();
         const userData = cookie.get('user_data');

         // Merge current form values with existing cookie data
         const existingData = userData ? JSON.parse(userData) : {};
         const updatedUserObj = {
            ...existingData,
            ...currentFormValues, // Save current form values
            step: step,
         };

         cookie.set('user_data', JSON.stringify(updatedUserObj), {
            secure: true, // Ensures the cookie is secure in production
            sameSite: 'Strict', // Prevents cross-site request forgery
         });

         setStep(step);
      },
      [methods]
   );

   // Use form_shape directly
   const activeFormShape = useMemo(
      () => form_shape,
      [form_shape]
   );

   // Memoize renderSteps result to prevent unnecessary re-renders and scroll issues
   const stepsContent = useMemo(() => {
      if (!activeFormShape) {
         return null;
      }

      return renderFormSteps({
         formShape: activeFormShape,
         currentStep: step,
         setStep: updateStep,
         category: role,
         optionalFields,
         mandatoryFields,
         residencyStatusTypes,
         withOtp,
         withSmsOtp,
         withAlternativeEmail,
         router,
         lang,
         guestEmail,
         guestFirstName,
         guestLastName,
         guestCompany,
         guestPosition,
         prefilldata,
         lock_data,
         token,
      });
   }, [
      activeFormShape,
      step,
      updateStep,
      role,
      optionalFields,
      mandatoryFields,
      residencyStatusTypes,
      withOtp,
      withSmsOtp,
      withAlternativeEmail,
      router,
      lang,
      guestEmail,
      guestFirstName,
      guestLastName,
      guestCompany,
      guestPosition,
      prefilldata,
      lock_data,
      token,
   ]);

   const isWidthLessThan768px = useMediaQuery({
      query: '(max-device-width: 768px)', //tailwind md => (768px)
   });
   return (
      <React.Fragment>
         <section className="min-h-full bg-cover bg-center bg-no-repeat">
            <div className="container relative mt-5">
               <div className="row">
                  <div className="lg:col-8 lg:offset-2 xl:col-8 xl:offset-2">
                     {/* <div className="col-12 text-center">
                        <h1
                           className={classNames(
                              'text-2xl font-black',
                              'text-center text-2xl font-black',
                              'from-[#4E442D] to-gold-primary bg-clip-text text-transparent ltr:bg-gradient-to-r rtl:bg-gradient-to-l'
                           )}>
                           <Translate id="web:register_your_attendance" />
                        </h1>
                     </div> */}

                     {steps && steps.length > 1 ? (
                        <React.Fragment>
                           {isWidthLessThan768px ? (
                              <MenuStepsMd steps={steps} step={step} />
                           ) : (
                              <MenuSteps steps={steps} step={step} />
                           )}
                        </React.Fragment>
                     ) : (
                        <div className="mt-8"></div>
                     )}

                     <div id="formWrapper" ref={formWrapperRef}>
                        <FormProvider key={`form-${activeFormShape || 'default'}`} {...methods}>
                           {stepsContent}
                        </FormProvider>
                     </div>
                  </div>
               </div>
            </div>
         </section>
      </React.Fragment>
   );
};

export default JoinFormWrapper;
