import { CheckIcon } from '@heroicons/react/24/outline';
import classNames from 'classnames';
import React from 'react';
import { useTranslate } from '~/i18n';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type MenuStepsProps = {
   steps: any;
   step: string | undefined;
};

const MenuSteps = ({ steps, step }: MenuStepsProps) => {
   const currentStep = steps?.indexOf(step) + 1;
   const { translate } = useTranslate();

   return (
      <React.Fragment>
         <div className="container mt-6 mb-12">
            <div className="row">
               <div className="md:col-12 xl:col-10 xl:offset-1">
                  <div className="flex items-center">
                     {steps?.map((step: any, index: number) => {
                        index++;
                        return (
                           <React.Fragment key={index}>
                              <div className="relative flex items-center">
                                 <div
                                    className={classNames(
                                       'h-10 w-10 rounded-full border-2 py-3 font-bold transition duration-500 ease-in-out',
                                       currentStep === index && 'border-primary text-primary',
                                       currentStep > index &&
                                          'border-primary bg-primary text-white',
                                       currentStep < index && 'border-white text-white '
                                    )}>
                                    <div className="absolute-center">
                                       {currentStep > index ? (
                                          <CheckIcon className="h-6 w-6" />
                                       ) : (
                                          `${index}`
                                       )}
                                    </div>
                                 </div>
                                 <div
                                    className={classNames(
                                       'absolute top-0 mt-12 w-32 text-center text-xs font-medium uppercase ltr:-ml-11 rtl:-mr-11',
                                       currentStep === index && 'text-primary',
                                       currentStep > index && 'text-primary',
                                       currentStep < index && 'text-white '
                                    )}>
                                    {translate({ id: `web:${step}` })}
                                 </div>
                              </div>
                              {steps.length !== index && (
                                 <div
                                    className={classNames(
                                       'flex-auto  border-t-[2px]   transition duration-500 ease-in-out',
                                       currentStep < index && 'border-white',
                                       currentStep === index && 'border-white ',
                                       currentStep > index && 'border-primary'
                                    )}></div>
                              )}
                           </React.Fragment>
                        );
                     })}
                  </div>
               </div>
            </div>
         </div>
      </React.Fragment>
   );
};

export default MenuSteps;
