import { RadioGroup } from '@headlessui/react';
import classNames from 'classnames';
import React, { useState, useEffect } from 'react';
import { Translate, useTranslate } from '~/i18n';
import Axios from '~/utils/axios';
import JoinFormWrapper from './form-wrapper';
/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const ParticipationJoinFormWrapper = () => {
   const [category, setCategory] = useState('');
   const { lang } = useTranslate();
   const [formData, setFormData] = useState<{
      optional_fields: string[] | null;
      mandatory_fields: string[] | null;
      visa_status_types: string[] | null;
      token: string | null;
      form_shape: string | null;
      with_otp: string | null;
      with_sms_otp: string | null;
      with_alternative_email: string | null;
   } | null>(null);
   const [loading, setLoading] = useState(false);
   const [error, setError] = useState<string | null>(null);

   useEffect(() => {
      if (!category) {
         setFormData(null);
         return;
      }

      const fetchCategoryData = async () => {
         setLoading(true);
         setError(null);
         try {
            const { data } = await Axios.get(`verify-category/${category}?lang=${lang}`);

            if (data.status !== 'valid') {
               setError('invalid_category');
               setFormData(null);
               return;
            }

            if (data.visibility == 'private') {
               setError('category_is_private');
               setFormData(null);
               return;
            }

            setFormData({
               optional_fields: data.optional_fields || null,
               mandatory_fields: data.mandatory_fields || null,
               visa_status_types: data.visa_status_types || null,
               token: data.token || null,
               form_shape: data.form_shape || null,
               with_otp: data.with_otp || null,
               with_sms_otp: data.with_sms_otp || null,
               with_alternative_email: data.with_alternative_email || null,
            });
         } catch (err: any) {
            // Check if it's a 429 Too Many Requests error
            if (err?.response?.status === 429) {
               setError('too_many_attempts');
            } else {
               setError('failed_to_fetch_form_data');
            }
            setFormData(null);
         } finally {
            setLoading(false);
         }
      };

      fetchCategoryData();
   }, [category, lang]);

   return (
      <section className="min-h-full bg-cover bg-center bg-no-repeat">
         <style jsx>{`
            @keyframes checkmarkIn {
               0% {
                  opacity: 0;
                  transform: scale(0) rotate(-180deg);
               }
               50% {
                  transform: scale(1.2) rotate(10deg);
               }
               100% {
                  opacity: 1;
                  transform: scale(1) rotate(0deg);
               }
            }
            @keyframes fadeInUp {
               0% {
                  opacity: 0;
                  transform: translateY(20px);
               }
               100% {
                  opacity: 1;
                  transform: translateY(0);
               }
            }
            @keyframes slideUpFromBottom {
               0% {
                  opacity: 0;
                  transform: translateY(40px);
               }
               100% {
                  opacity: 1;
                  transform: translateY(0);
               }
            }
            .animate-checkmark-in {
               animation: checkmarkIn 0.4s cubic-bezier(0.34, 1.56, 0.64, 1);
            }
            .animate-fade-in-up {
               animation: fadeInUp 0.6s ease-out;
            }
            .animate-slide-up-from-bottom {
               animation: slideUpFromBottom 0.6s cubic-bezier(0.4, 0, 0.2, 1);
            }
         `}</style>
         <div className="container mt-10">
            <div>
               <h1
                  className={classNames(
                     'mb-4 text-center text-2xl font-black',
                     'from-[#4E442D] to-gold-primary bg-clip-text text-transparent ltr:bg-gradient-to-r rtl:bg-gradient-to-l'
                  )}>
                  <Translate id="web:please_choose_your_type_of_participation" />
               </h1>
            </div>
            <div className="mt-8 mb-6">
               <RadioGroup
                  value={category}
                  onChange={setCategory}
                  className="row justify-center gap-4 md:gap-6">
                  <RadioGroup.Option value="hci-attendee" className="col-12 sm:col-6 md:col-3">
                     {({ checked }) => (
                        <div
                           className={classNames(
                              'group relative flex flex-col items-center justify-center',
                              'rounded-xl transition-all duration-500 ease-out',
                              'px-4 py-6 sm:px-6 sm:py-8',
                              'animate-fade-in-up transform cursor-pointer',
                              'hover:scale-[1.03] hover:shadow-2xl',
                              'transition-[transform,box-shadow,border-color,background-color] duration-500 ease-out',
                              checked
                                 ? 'shadow-lg shadow-[#4E442D]/20'
                                 : 'border-2 border-white/20 bg-white/5 hover:border-white/40 hover:bg-white/10',
                              'backdrop-blur-sm'
                           )}
                           style={{
                              animationDelay: '0.1s',
                              ...(checked
                                 ? {
                                      border: '2px solid transparent',
                                      backgroundImage:
                                         'linear-gradient(rgba(0,0,0,0.8), rgba(0,0,0,0.8)), linear-gradient(135deg, #4E442D, #987c4b)',
                                      backgroundOrigin: 'border-box',
                                      backgroundClip: 'padding-box, border-box',
                                      backgroundColor: 'rgba(0, 155, 152, 0.1)',
                                      transition: 'all 0.5s ease-out',
                                   }
                                 : {
                                      transition: 'all 0.5s ease-out',
                                   }),
                           }}>
                           {/* Check icon when selected */}
                           {checked && (
                              <div className="animate-checkmark-in absolute top-3 right-3 sm:top-4 sm:right-4">
                                 <div className="flex h-6 w-6 items-center justify-center rounded-full bg-gradient-to-r from-[#4E442D] to-gold-primary shadow-lg shadow-[#4E442D]/50 transition-all duration-300 hover:scale-110">
                                    <svg
                                       className="h-4 w-4 text-white transition-transform duration-300"
                                       fill="none"
                                       viewBox="0 0 24 24"
                                       stroke="currentColor">
                                       <path
                                          strokeLinecap="round"
                                          strokeLinejoin="round"
                                          strokeWidth={3}
                                          d="M5 13l4 4L19 7"
                                       />
                                    </svg>
                                 </div>
                              </div>
                           )}

                           <div className="relative z-10 flex flex-col items-center text-center">
                              <p
                                 className={classNames(
                                    'mb-2 text-2xl font-black transition-all duration-500 ease-out sm:text-3xl',
                                    checked
                                       ? 'scale-105 bg-gradient-to-r from-[#4E442D] to-gold-primary bg-clip-text text-transparent'
                                       : 'text-white transition-colors duration-300 group-hover:text-[#4E442D]'
                                 )}>
                                 <Translate id="web:participation_type_hci" />
                              </p>
                              <p
                                 className={classNames(
                                    'text-sm text-white/70 transition-all duration-500 ease-out sm:text-base',
                                    checked
                                       ? 'scale-105 text-white/90'
                                       : 'group-hover:text-white/80'
                                 )}>
                                 <Translate id="web:participation_type_hci_description" />
                              </p>
                              <p
                                 className={classNames(
                                    'mt-2 text-xs text-white/60 transition-all duration-500 ease-out sm:text-sm',
                                    checked
                                       ? 'scale-105 text-white/80'
                                       : 'group-hover:text-white/70'
                                 )}>
                                 <Translate id="web:hci_date_range" />
                              </p>
                           </div>

                           {/* Hover glow effect */}
                           <div
                              className={classNames(
                                 'absolute inset-0 rounded-xl opacity-0 transition-opacity duration-500 ease-out',
                                 'bg-gradient-to-r from-[#4E442D]/10 to-gold-primary/10',
                                 'group-hover:opacity-100'
                              )}
                           />
                        </div>
                     )}
                  </RadioGroup.Option>

                  <RadioGroup.Option value="edgex-attendee" className="col-12 sm:col-6 md:col-3">
                     {({ checked }) => (
                        <div
                           className={classNames(
                              'group relative flex flex-col items-center justify-center',
                              'rounded-xl transition-all duration-500 ease-out',
                              'px-4 py-6 sm:px-6 sm:py-8',
                              'animate-fade-in-up transform cursor-pointer',
                              'hover:scale-[1.03] hover:shadow-2xl',
                              'transition-[transform,box-shadow,border-color,background-color] duration-500 ease-out',
                              checked
                                 ? 'shadow-lg shadow-[#4E442D]/20'
                                 : 'border-2 border-white/20 bg-white/5 hover:border-white/40 hover:bg-white/10',
                              'backdrop-blur-sm'
                           )}
                           style={{
                              animationDelay: '0.2s',
                              ...(checked
                                 ? {
                                      border: '2px solid transparent',
                                      backgroundImage:
                                         'linear-gradient(rgba(0,0,0,0.8), rgba(0,0,0,0.8)), linear-gradient(135deg, #4E442D, #987c4b)',
                                      backgroundOrigin: 'border-box',
                                      backgroundClip: 'padding-box, border-box',
                                      backgroundColor: 'rgba(0, 155, 152, 0.1)',
                                      transition: 'all 0.5s ease-out',
                                   }
                                 : {
                                      transition: 'all 0.5s ease-out',
                                   }),
                           }}>
                           {/* Check icon when selected */}
                           {checked && (
                              <div className="animate-checkmark-in absolute top-3 right-3 sm:top-4 sm:right-4">
                                 <div className="flex h-6 w-6 items-center justify-center rounded-full bg-gradient-to-r from-[#4E442D] to-gold-primary shadow-lg shadow-[#4E442D]/50 transition-all duration-300 hover:scale-110">
                                    <svg
                                       className="h-4 w-4 text-white transition-transform duration-300"
                                       fill="none"
                                       viewBox="0 0 24 24"
                                       stroke="currentColor">
                                       <path
                                          strokeLinecap="round"
                                          strokeLinejoin="round"
                                          strokeWidth={3}
                                          d="M5 13l4 4L19 7"
                                       />
                                    </svg>
                                 </div>
                              </div>
                           )}

                           <div className="relative z-10 flex flex-col items-center text-center">
                              <p
                                 className={classNames(
                                    'mb-2 text-2xl font-black transition-colors duration-300 sm:text-3xl',
                                    checked
                                       ? 'bg-gradient-to-r from-[#4E442D] to-gold-primary bg-clip-text text-transparent'
                                       : 'text-white group-hover:text-[#4E442D]'
                                 )}>
                                 <Translate id="web:participation_type_edgex" />
                              </p>
                              <p className="text-sm text-white/70 sm:text-base">
                                 <Translate id="web:participation_type_edgex_description" />
                              </p>
                              <p className="mt-2 text-xs text-white/60 sm:text-sm">
                                 <Translate id="web:edgex_date_range" />
                              </p>
                           </div>

                           {/* Hover glow effect */}
                           <div
                              className={classNames(
                                 'absolute inset-0 rounded-xl opacity-0 transition-opacity duration-300',
                                 'bg-gradient-to-r from-[#4E442D]/10 to-gold-primary/10',
                                 'group-hover:opacity-100'
                              )}
                           />
                        </div>
                     )}
                  </RadioGroup.Option>

                  <RadioGroup.Option value="both" className="col-12 sm:col-6 md:col-3">
                     {({ checked }) => (
                        <div
                           className={classNames(
                              'group relative flex flex-col items-center justify-center',
                              'rounded-xl transition-all duration-500 ease-out',
                              'px-4 py-6 sm:px-6 sm:py-8',
                              'animate-fade-in-up transform cursor-pointer',
                              'hover:scale-[1.03] hover:shadow-2xl',
                              'transition-[transform,box-shadow,border-color,background-color] duration-500 ease-out',
                              checked
                                 ? 'shadow-lg shadow-[#4E442D]/20'
                                 : 'border-2 border-white/20 bg-white/5 hover:border-white/40 hover:bg-white/10',
                              'backdrop-blur-sm'
                           )}
                           style={{
                              animationDelay: '0.3s',
                              ...(checked
                                 ? {
                                      border: '2px solid transparent',
                                      backgroundImage:
                                         'linear-gradient(rgba(0,0,0,0.8), rgba(0,0,0,0.8)), linear-gradient(135deg, #4E442D, #987c4b)',
                                      backgroundOrigin: 'border-box',
                                      backgroundClip: 'padding-box, border-box',
                                      backgroundColor: 'rgba(0, 155, 152, 0.1)',
                                      transition: 'all 0.5s ease-out',
                                   }
                                 : {
                                      transition: 'all 0.5s ease-out',
                                   }),
                           }}>
                           {/* Check icon when selected */}
                           {checked && (
                              <div className="animate-checkmark-in absolute top-3 right-3 sm:top-4 sm:right-4">
                                 <div className="flex h-6 w-6 items-center justify-center rounded-full bg-gradient-to-r from-[#4E442D] to-gold-primary shadow-lg shadow-[#4E442D]/50 transition-all duration-300 hover:scale-110">
                                    <svg
                                       className="h-4 w-4 text-white transition-transform duration-300"
                                       fill="none"
                                       viewBox="0 0 24 24"
                                       stroke="currentColor">
                                       <path
                                          strokeLinecap="round"
                                          strokeLinejoin="round"
                                          strokeWidth={3}
                                          d="M5 13l4 4L19 7"
                                       />
                                    </svg>
                                 </div>
                              </div>
                           )}

                           <div className="relative z-10 flex flex-col items-center text-center">
                              <p
                                 className={classNames(
                                    'mb-2 text-2xl font-black transition-colors duration-300 sm:text-3xl',
                                    checked
                                       ? 'bg-gradient-to-r from-[#4E442D] to-gold-primary bg-clip-text text-transparent'
                                       : 'text-white group-hover:text-[#4E442D]'
                                 )}>
                                 <Translate id="web:participation_type_both_description" />
                              </p>
                              <p className="text-sm text-white/70 sm:text-base">
                                 <Translate id="web:participation_type_both" />
                              </p>
                              <p className="mt-2 text-xs text-white/60 sm:text-sm">
                                 <Translate id="web:edgex_date_range" />
                              </p>
                           </div>

                           {/* Hover glow effect */}
                           <div
                              className={classNames(
                                 'absolute inset-0 rounded-xl opacity-0 transition-opacity duration-300',
                                 'bg-gradient-to-r from-[#4E442D]/10 to-gold-primary/10',
                                 'group-hover:opacity-100'
                              )}
                           />
                        </div>
                     )}
                  </RadioGroup.Option>
               </RadioGroup>
            </div>
            {/* Show info containers when no category is selected */}
            {!category && !loading && (
               <div className="row">
                  <div className="lg:col-8 lg:offset-2 xl:col-8 xl:offset-2">
                     <div className="mt-8 space-y-6">
                        {/* Container 1: About HCI Conference */}
                        <div className="group relative overflow-hidden rounded-xl border-2 border-white/20 bg-white/5 p-6 backdrop-blur-sm transition-all duration-500 hover:border-white/40 hover:bg-white/10 sm:p-8">
                           <div className="relative z-10">
                              <div className="mb-4 flex items-center justify-between">
                                 <h2 className="text-xl font-bold text-white sm:text-2xl">
                                    <Translate id="web:about_hci_conference" />
                                 </h2>
                                 <a
                                    href="https://humancapabilityinitiative.org/en/"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-[#4E442D] to-gold-primary px-4 py-2 text-sm font-semibold text-white transition-all duration-300 hover:scale-105 hover:shadow-lg">
                                    <Translate id="web:learn_more" />
                                    <svg
                                       className="h-4 w-4"
                                       fill="none"
                                       viewBox="0 0 24 24"
                                       stroke="currentColor">
                                       <path
                                          strokeLinecap="round"
                                          strokeLinejoin="round"
                                          strokeWidth={2}
                                          d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
                                       />
                                    </svg>
                                 </a>
                              </div>
                              <div className="space-y-3 text-white/80">
                                 <p className="text-base leading-relaxed sm:text-lg">
                                    <Translate id="web:hci_conference_description" />
                                 </p>
                                 <div className="mt-4 flex flex-wrap gap-2">
                                    <span className="rounded-full bg-[#4E442D]/20 px-3 py-1 text-sm text-[#4E442D]">
                                       <Translate id="web:may_3_5_2026" />
                                    </span>
                                    <span className="rounded-full bg-[#4E442D]/20 px-3 py-1 text-sm text-[#4E442D]">
                                       <Translate id="web:riyadh_saudi_arabia" />
                                    </span>
                                    <span className="rounded-full bg-[#4E442D]/20 px-3 py-1 text-sm text-[#4E442D]">
                                       <Translate id="web:beyond_readiness" />
                                    </span>
                                 </div>
                              </div>
                           </div>
                           {/* Hover glow effect */}
                           <div className="absolute inset-0 rounded-xl bg-gradient-to-r from-[#4E442D]/5 to-gold-primary/5 opacity-0 transition-opacity duration-500 group-hover:opacity-100" />
                        </div>

                        {/* Container 2: About EDGEx Exhibition */}
                        <div className="group relative overflow-hidden rounded-xl border-2 border-white/20 bg-white/5 p-6 backdrop-blur-sm transition-all duration-500 hover:border-white/40 hover:bg-white/10 sm:p-8">
                           <div className="relative z-10">
                              <div className="mb-4 flex items-center justify-between">
                                 <h2 className="text-xl font-bold text-white sm:text-2xl">
                                    <Translate id="web:about_edgex_exhibition" />
                                 </h2>
                                 <a
                                    href="https://edgex.humancapabilityinitiative.org/en"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className="flex items-center gap-2 rounded-lg bg-gradient-to-r from-[#4E442D] to-gold-primary px-4 py-2 text-sm font-semibold text-white transition-all duration-300 hover:scale-105 hover:shadow-lg">
                                    <Translate id="web:learn_more" />
                                    <svg
                                       className="h-4 w-4"
                                       fill="none"
                                       viewBox="0 0 24 24"
                                       stroke="currentColor">
                                       <path
                                          strokeLinecap="round"
                                          strokeLinejoin="round"
                                          strokeWidth={2}
                                          d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"
                                       />
                                    </svg>
                                 </a>
                              </div>
                              <div className="space-y-3 text-white/80">
                                 <p className="text-base leading-relaxed sm:text-lg">
                                    <Translate id="web:edgex_exhibition_description" />
                                 </p>
                                 <div className="mt-4 flex flex-wrap gap-2">
                                    <span className="rounded-full bg-[#4E442D]/20 px-3 py-1 text-sm text-[#4E442D]">
                                       <Translate id="web:edtech_exhibition" />
                                    </span>
                                    <span className="rounded-full bg-[#4E442D]/20 px-3 py-1 text-sm text-[#4E442D]">
                                       <Translate id="web:innovation_showcase" />
                                    </span>
                                    <span className="rounded-full bg-[#4E442D]/20 px-3 py-1 text-sm text-[#4E442D]">
                                       <Translate id="web:networking_opportunities" />
                                    </span>
                                 </div>
                              </div>
                           </div>
                           {/* Hover glow effect */}
                           <div className="absolute inset-0 rounded-xl bg-gradient-to-r from-[#4E442D]/5 to-gold-primary/5 opacity-0 transition-opacity duration-500 group-hover:opacity-100" />
                        </div>
                     </div>
                  </div>
               </div>
            )}

            <div className="mt-8">
               {loading && <div></div>}
               {error && (
                  <div className="mx-auto max-w-md rounded-xl border border-red-500/50 bg-red-500/10 px-6 py-4 backdrop-blur-sm">
                     <div className="flex items-center gap-3">
                        <svg
                           className="h-6 w-6 flex-shrink-0 text-red-400"
                           fill="none"
                           viewBox="0 0 24 24"
                           stroke="currentColor">
                           <path
                              strokeLinecap="round"
                              strokeLinejoin="round"
                              strokeWidth={2}
                              d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                           />
                        </svg>
                        <p className="text-red-300">
                           {error === 'too_many_attempts' ? (
                              <Translate id="web:too_many_attempts" />
                           ) : error === 'failed_to_fetch_form_data' ? (
                              <Translate id="web:failed_to_fetch_form_data" />
                           ) : error === 'invalid_category' ? (
                              <Translate id="web:invalid_category" />
                           ) : error === 'category_is_private' ? (
                              <Translate id="web:category_is_private" />
                           ) : (
                              error
                           )}
                        </p>
                     </div>
                  </div>
               )}
               {category && formData && !loading && (
                  <div className="animate-slide-up-from-bottom">
                     <JoinFormWrapper
                        category={category}
                        guestEmail={null}
                        guestFirstName={null}
                        guestLastName={null}
                        optionalFields={formData.optional_fields || []}
                        mandatoryFields={formData.mandatory_fields || []}
                        residencyStatusTypes={formData.visa_status_types || []}
                        token={formData.token || ''}
                        // withToken={true}
                        form_shape={formData.form_shape}
                        withOtp={formData.with_otp === 'yes' ? true : false}
                        withSmsOtp={formData.with_sms_otp === 'yes' ? true : false}
                        withAlternativeEmail={
                           formData.with_alternative_email === 'yes' ? true : false
                        }
                     />
                  </div>
               )}
            </div>
         </div>
      </section>
   );
};

export default ParticipationJoinFormWrapper;
