import React, { useState } from 'react';
import { Controller, useFormContext } from 'react-hook-form';
import SubmitBtn from '~/components/shared/buttons/submit-btn';
import { Translate, useTranslate } from '~/i18n';
import cookie from 'js-cookie';
import CustomInput from '~/components/shared/forms/custom-input';
import toast from 'react-hot-toast';
import { GuestType } from '~/interfaces/guest';
import StaticSelectNew from '~/components/shared/select/static-select-new';
import ResidencyStatusTypesSelect from '~/data/residency-status-types-select';
import DocumentTypeSelect from '~/data/document-types-select';
import CustomRadioInput from '~/components/shared/forms/custom-radio-input';
import CustomDayInput from '~/components/shared/forms/custom-day-input';
import { getUnixTime, getYear } from 'date-fns';
import CustomFileInput3 from '~/components/shared/forms/custom-file-input-2/custom-file-input-3';
import { ArrowTopRightOnSquareIcon, TrashIcon } from '@heroicons/react/20/solid';
import { CountryType } from '~/interfaces/country';
import cookies from 'js-cookie';
import CalendarIconAppend from '~/components/shared/forms/calender-icon-append';
import Label from '~/components/shared/forms/label';
import BackBtn from '~/components/shared/buttons/back-btn';
import Axios from '~/utils/axios';
import PassportTypesSelect from '~/data/passport-types-select';
import { useGoogleReCaptcha } from 'react-google-recaptcha-v3';
import { zonedTimeToUtc } from 'date-fns-tz';
import Modal from '~/components/shared/modals';
import classNames from 'classnames';
import CountrySelectNew from '~/components/shared/select/countries-select-new';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type PersonalInfo2Props = {
   onNextClick: () => any;
   onBackClick: () => any;
   onUpdateClick: () => any;

   step: string | undefined;
   token?: string;
   nextStep: string;
   role?: string;
   countries?: CountryType[];
   stepsNumber: number;
   optionalFields?: string[];
   mandatoryFields?: string[];
   residencyStatusTypes?: string[];
};

const PersonalInfo2 = ({
   onNextClick,
   onBackClick,
   step,
   nextStep,
   role,
   token,
   // countries,
   stepsNumber,
   optionalFields,
   mandatoryFields,
   residencyStatusTypes,
}: PersonalInfo2Props) => {
   const { translate, lang } = useTranslate();
   const [loading, setLoading] = useState(false);

   const {
      handleSubmit,
      getValues,
      control,
      setValue,
      register,
      watch,
      formState: { errors },
   } = useFormContext<GuestType>();
   const { executeRecaptcha } = useGoogleReCaptcha();
   const [isOpen, setIsOpen] = useState(false);
   const [isOpen2, setIsOpen2] = useState(false);

   const submitForm = async (values: GuestType) => {
      if (loading) {
         return;
      }
      setLoading(true);

      try {
         if (stepsNumber === 2) {
            const recaptcha = await executeRecaptcha?.();

            const data = {
               ...values,
               code: token || '', //todo: check
               category: role,
               email: values?.email?.toLowerCase(),
               recaptcha,
            };
            delete data.personal_image_url;
            delete data.document_copy_url;
            delete data.visa_copy_url;
            // Backend now accepts residency_status and valid_visa directly
            localStorage.removeItem('personal_image_x');
            localStorage.removeItem('doc1_x');
            localStorage.removeItem('doc2_x');

            //for speaker 4 steps
            delete data.require_flights;
            delete data.departure_city_to;
            delete data.destination_to;
            delete data.expected_date_of_arrival;
            delete data.specific_requirements_to;
            delete data.departure_city_from;
            delete data.destination_from;
            delete data.expected_date_of_departure;
            delete data.specific_requirements_from;
            delete data.comments;
            delete data.require_accommodation;
            delete data.special_requests;
            delete data.dietary_requirements;

            const response = await Axios.post(`guests?lang=${lang}`, data);
            cookies.set('reg_num', response.data.data);

            // to success page
            onNextClick();
         } else {
            const updatedUserObj = {
               ...values,
               step: nextStep,
            };

            cookie.set('user_data', JSON.stringify(updatedUserObj), {
               secure: true,
               sameSite: 'Strict',
            });
            toast.success(translate({ id: 'res:info_saved' }));
            setLoading(false);
            onNextClick();
         }
      } catch (error: any) {
         setLoading(false);
         if (error.response?.status === 404) {
            toast.error(error.response?.data?.data);
         } else if (error?.response?.status === 403) {
            toast.error(translate({ id: 'res:recaptcha_failed' }), {
               duration: 4000,
            });
         } else {
            toast.error(translate({ id: 'res:500' }));
         }
         console.log(error, 'error');
      }
   };

   const renderDocumentTypeOption = () => {
      switch (getValues()['residency_status']) {
         case 'saudi_residency':
            return DocumentTypeSelect.filter(item => item.value === 'iqama_id');
         case 'gcc':
            return DocumentTypeSelect.filter(item => item.value === 'passport');
         case 'foreign_national':
            return DocumentTypeSelect.filter(item => item.value === 'passport');
         default:
            return DocumentTypeSelect;
      }
   };

   const doc1_x = (typeof window !== 'undefined' && localStorage.getItem('doc1_x')) || '';
   const doc2_x = (typeof window !== 'undefined' && localStorage.getItem('doc2_x')) || '';

   // render inner inputs function
   const renderInnerInputs = (isSaudi: boolean) => {
      return (
         <React.Fragment>
            <div>
               <div className="">
                  {/* document_type - Hidden but logic preserved */}
                  {isSaudi === false && (
                     <div className="hidden">
                        <Controller
                           name="document_type"
                           control={control}
                           render={() => (
                              <StaticSelectNew
                                 options={renderDocumentTypeOption()}
                                 selected_id={watch('document_type')}
                                 label=""
                                 placeholderTranslationId="web:select_document_type"
                                 dropdownRounded="none"
                                 errors={errors.document_type?.message}
                                 isRequired={
                                    !optionalFields || !optionalFields.includes('document_type')
                                 }
                                 callBack={(item: { value: string } | null) => {
                                    setValue('document_type', item?.value || null, {
                                       shouldValidate: true,
                                    });
                                    setValue('document_number', null, {
                                       shouldValidate: false,
                                    });
                                 }}
                              />
                           )}
                           rules={{
                              required:
                                 optionalFields && optionalFields.includes('document_type')
                                    ? false
                                    : translate({ id: 'validation:required' }),
                           }}
                        />
                     </div>
                  )}
                  {/* valid_visa - only for foreign_national */}
                  {isSaudi === false && getValues()['residency_status'] === 'foreign_national' && (
                     <div className="row">
                        <div className="md:col-9 md:offset-3">
                           <div>
                              {/* valid_visa */}
                              <div className={classNames('')}>
                                 <Label
                                    id={'valid_visa'}
                                    label={translate({ id: 'web:valid_visa' })}
                                    isRequired={true}
                                 />
                              </div>
                              <CustomRadioInput
                                 isRequired={
                                    optionalFields && optionalFields.includes('valid_visa')
                                       ? false
                                       : true
                                 }
                                 isInline={true}
                                 options={[
                                    { value: 'yes', label: translate({ id: 'web:yes' }) },
                                    { value: 'no', label: translate({ id: 'web:no' }) },
                                 ]}
                                 id="valid_visa"
                                 error={errors.valid_visa?.message}
                                 {...register('valid_visa', {
                                    required:
                                       optionalFields && optionalFields.includes('valid_visa')
                                          ? false
                                          : translate({ id: 'validation:required' }),
                                 })}
                              />

                              {watch('valid_visa') !== null ? (
                                 watch('valid_visa') === 'no' ? (
                                    <React.Fragment>
                                       <div className="mb-6 rounded-lg border-2 border-dashed border-[#7F8694] px-4 py-2">
                                          <p className="text-white">
                                             <Translate id="web:p_visa_with_code" />
                                          </p>
                                       </div>
                                    </React.Fragment>
                                 ) : (
                                    <div className="mb-6 rounded-lg border-2 border-dashed border-[#7F8694] px-4 py-2">
                                       <p className="text-white">
                                          <Translate id="web:p_visa_without_code" />
                                       </p>
                                    </div>
                                 )
                              ) : (
                                 ''
                              )}
                           </div>
                        </div>
                     </div>
                  )}
                  {/* passport_type */}
                  {isSaudi === false && getValues()['residency_status'] !== 'saudi_residency' && (
                     <div className="row">
                        <div className="self-center md:mb-5 md:col-3">
                           <Label
                              id="passport_type"
                              isRequired={
                                 optionalFields && optionalFields.includes('passport_type')
                                    ? false
                                    : true
                              }
                              label={translate({ id: 'web:passport_type' })}
                           />
                        </div>
                        <div className="md:col-9">
                           <Controller
                              name="passport_type"
                              control={control}
                              render={() => (
                                 <StaticSelectNew
                                    options={PassportTypesSelect}
                                    selected_id={watch('passport_type')}
                                    label=""
                                    placeholderTranslationId="web:select_passport_type"
                                    dropdownRounded="none"
                                    errors={errors.passport_type?.message}
                                    isRequired={
                                       !optionalFields || !optionalFields.includes('passport_type')
                                    }
                                    callBack={(item: { value: string } | null) => {
                                       setValue('passport_type', item?.value || null, {
                                          shouldValidate: true,
                                       });
                                    }}
                                 />
                              )}
                              rules={{
                                 required:
                                    optionalFields && optionalFields.includes('passport_type')
                                       ? false
                                       : translate({ id: 'validation:required' }),
                              }}
                           />
                        </div>
                     </div>
                  )}

                  {/* document_number */}
                  <CustomInput
                     label={translate({ id: 'web:document_number' })}
                     type="text"
                     isRequired={
                        optionalFields && optionalFields.includes('document_number') ? false : true
                     }
                     isInline
                     autoComplete="off"
                     placeHolder={renderDocumentNumberPlaceHolder(getValues('document_type'))}
                     id="document_number"
                     error={errors.document_number?.message}
                     {...register('document_number', {
                        required:
                           optionalFields && optionalFields.includes('document_number')
                              ? false
                              : translate({ id: 'validation:required' }),
                        validate: {
                           trim: (value: any) => {
                              if (value) {
                                 value == value.trim() ||
                                    translate({
                                       id: 'validation:delete_spaces',
                                    });
                              } else {
                                 return true;
                              }
                           },

                           minLength: (value: any) => {
                              if (value) {
                                 if (
                                    (getValues('document_type') === 'saudi_id' ||
                                       getValues('document_type') === 'iqama_id') &&
                                    value.length !== 10
                                 ) {
                                    return translate({
                                       id: 'validation:id_10_digit',
                                    });
                                 }
                                 return true;
                              } else {
                                 return true;
                              }
                           },
                        },
                     })}
                  />
                  {/* issue_date */}
                  {isSaudi === false && (
                     <React.Fragment>
                        <CustomDayInput
                           label={translate({ id: 'web:issue_date' })}
                           type="text"
                           placeHolder={translate({ id: 'web:issue_date' })}
                           id="issue_date"
                           isInline
                           isRequired={
                              optionalFields && optionalFields.includes('issue_date') ? false : true
                           }
                           fromYear={getYear(new Date()) - 70}
                           toYear={getYear(new Date())}
                           {...register('issue_date', {
                              required:
                                 optionalFields && optionalFields.includes('issue_date')
                                    ? false
                                    : translate({ id: 'validation:required' }),
                           })}
                           append={<CalendarIconAppend />}
                           value={getValues('issue_date')}
                           error={errors.issue_date?.message}
                           callBack={(item: Date) => {
                              const timestamp = getUnixTime(item);
                              const saudiArabiaTimestamp =
                                 zonedTimeToUtc(timestamp * 1000, 'Asia/Riyadh').getTime() / 1000;
                              setValue('issue_date', saudiArabiaTimestamp.toString(), {
                                 shouldValidate: true,
                              });
                           }}
                        />

                        {/* issue_place */}
                        <CustomInput
                           label={translate({ id: 'web:issue_place' })}
                           type="text"
                           isRequired={
                              optionalFields && optionalFields.includes('issue_place')
                                 ? false
                                 : true
                           }
                           isInline
                           autoComplete="off"
                           placeHolder={translate({
                              id: 'web:issue_place',
                           })}
                           id="issue_place"
                           error={errors.issue_place?.message}
                           {...register('issue_place', {
                              required:
                                 optionalFields && optionalFields.includes('issue_place')
                                    ? false
                                    : translate({ id: 'validation:required' }),
                           })}
                        />
                     </React.Fragment>
                  )}
                  {/* expiration_date */}
                  <CustomDayInput
                     label={translate({ id: 'web:expiration_date' })}
                     type="text"
                     placeHolder={translate({ id: 'web:expiration_date' })}
                     id="expiration_date"
                     // defaultSelected={query.date_from?.toString()}
                     isInline
                     isRequired={
                        optionalFields && optionalFields.includes('expiration_date') ? false : true
                     }
                     fromYear={getYear(new Date())}
                     toYear={getYear(new Date()) + 30}
                     {...register('expiration_date', {
                        required:
                           optionalFields && optionalFields.includes('expiration_date')
                              ? false
                              : translate({ id: 'validation:required' }),
                     })}
                     append={<CalendarIconAppend />}
                     value={getValues('expiration_date')}
                     error={errors.expiration_date?.message}
                     callBack={(item: Date) => {
                        const timestamp = getUnixTime(item);
                        const saudiArabiaTimestamp =
                           zonedTimeToUtc(timestamp * 1000, 'Asia/Riyadh').getTime() / 1000;
                        setValue('expiration_date', saudiArabiaTimestamp.toString(), {
                           shouldValidate: true,
                        });
                     }}
                  />

                  {/* birth_date */}
                  <CustomDayInput
                     label={translate({ id: 'web:birth_date' })}
                     type="text"
                     placeHolder={translate({ id: 'web:birth_date' })}
                     id="birth_date"
                     fromYear={getYear(new Date()) - 100}
                     toYear={getYear(new Date())}
                     // defaultSelected={query.date_from?.toString()}
                     isInline
                     isRequired={
                        optionalFields && optionalFields.includes('birth_date') ? false : true
                     }
                     {...register('birth_date', {
                        required:
                           optionalFields && optionalFields.includes('birth_date')
                              ? false
                              : translate({ id: 'validation:required' }),
                     })}
                     disabledDays={(date: Date) => date > new Date()}
                     append={<CalendarIconAppend />}
                     value={getValues('birth_date')}
                     error={errors.birth_date?.message}
                     callBack={(item: Date) => {
                        const timestamp = getUnixTime(item);
                        const saudiArabiaTimestamp =
                           zonedTimeToUtc(timestamp * 1000, 'Asia/Riyadh').getTime() / 1000;
                        setValue('birth_date', saudiArabiaTimestamp.toString(), {
                           shouldValidate: true,
                        });
                     }}
                  />
                  {/* nationality */}
                  <Controller
                     name="nationality"
                     control={control}
                     render={() => (
                        <CountrySelectNew
                           isRequired={mandatoryFields?.includes('nationality') ?? false}
                           selected_id={watch('nationality')}
                           label={translate({ id: 'web:nationality' })}
                           errors={errors.nationality?.message}
                           callBack={(item: { value: string; label: string } | null) => {
                              setValue('nationality', item?.value || null, {
                                 shouldValidate: true,
                              });
                           }}
                        />
                     )}
                     rules={{
                        required: mandatoryFields?.includes('nationality')
                           ? translate({ id: 'validation:required' })
                           : false,
                     }}
                  />
                  {isSaudi === false && (
                     <React.Fragment>
                        {/* birth_city */}
                        <CustomInput
                           label={translate({ id: 'web:birth_city' })}
                           type="text"
                           isRequired={
                              optionalFields && optionalFields.includes('birth_city') ? false : true
                           }
                           isInline
                           autoComplete="off"
                           placeHolder={translate({
                              id: 'web:birth_city',
                           })}
                           id="birth_city"
                           error={errors.birth_city?.message}
                           {...register('birth_city', {
                              required:
                                 optionalFields && optionalFields.includes('birth_city')
                                    ? false
                                    : translate({ id: 'validation:required' }),
                           })}
                        />

                        {/* saudi_embassy_city - only for foreign_national with valid_visa === 'no' */}
                        {getValues()['residency_status'] === 'foreign_national' &&
                           getValues()['valid_visa'] === 'no' && (
                              <CustomInput
                                 label={translate({ id: 'web:saudi_embassy_city' })}
                                 type="text"
                                 isRequired={
                                    optionalFields && optionalFields.includes('saudi_embassy_city')
                                       ? false
                                       : true
                                 }
                                 isInline
                                 autoComplete="off"
                                 placeHolder={translate({
                                    id: 'web:saudi_embassy_city',
                                 })}
                                 id="saudi_embassy_city"
                                 error={errors.saudi_embassy_city?.message}
                                 {...register('saudi_embassy_city', {
                                    required:
                                       optionalFields &&
                                       optionalFields.includes('saudi_embassy_city')
                                          ? false
                                          : translate({ id: 'validation:required' }),
                                 })}
                              />
                           )}
                        {/* religion */}
                        <CustomRadioInput
                           label={translate({ id: 'web:religion' })}
                           isRequired={
                              optionalFields && optionalFields.includes('religion') ? false : true
                           }
                           isInline={true}
                           options={[
                              { value: 'muslim', label: translate({ id: 'web:muslim' }) },
                              { value: 'christian', label: translate({ id: 'web:christian' }) },
                              { value: 'other', label: translate({ id: 'web:other' }) },
                           ]}
                           id="religion"
                           error={errors.religion?.message}
                           {...register('religion', {
                              required:
                                 optionalFields && optionalFields.includes('religion')
                                    ? false
                                    : translate({ id: 'validation:required' }),
                           })}
                        />
                     </React.Fragment>
                  )}
               </div>
               <div>
                  <hr className="my-7 border-[#7F8694]" />
                  <div className="mt-4">
                     {/* document_copy */}
                     <Controller
                        name="document_copy"
                        control={control}
                        render={({ field: { ref } }) => (
                           <CustomFileInput3
                              label={translate({
                                 id: 'web:document_copy',
                                 values: {
                                    id: getValues('document_type')
                                       ? translate({ id: `web:${getValues('document_type')}` })
                                       : translate({ id: 'web:id' }),
                                 },
                              })}
                              id="document_copy"
                              isRequired={
                                 optionalFields && optionalFields.includes('document_copy')
                                    ? false
                                    : true
                              }
                              error={errors.document_copy?.message || errors.document_copy?.message}
                              ref={ref}
                              inputName="document_copy"
                              help={
                                 <React.Fragment>
                                    <span className="block text-center text-sm text-white">
                                       <Translate id="web:only_jpg_png" />
                                    </span>
                                 </React.Fragment>
                              }
                              placeholderImg={
                                 getValues('document_copy') != null &&
                                 doc1_x && (
                                    <div className="rtl:gap-reverse flex items-center justify-center gap-3 py-2">
                                       <button
                                          type="button"
                                          onClick={() => setIsOpen(true)}
                                          className="rtl:gap-reverse flex items-center gap-2 rounded-xl border-2 border-purple-500/80 bg-purple-500/10 px-4 py-2.5 text-sm font-medium text-purple-400 focus:outline-none focus:ring-2 focus:ring-purple-500/50 focus:ring-offset-2 focus:ring-offset-transparent">
                                          <span>
                                             <Translate id="web:view_file" />
                                          </span>
                                          <ArrowTopRightOnSquareIcon className="h-4 w-4" />
                                       </button>
                                       <button
                                          type="button"
                                          onClick={() => {
                                             setValue('document_copy', null, {
                                                shouldValidate: true,
                                             });
                                             localStorage.removeItem('doc1_x');

                                             const el = document.getElementById(
                                                'document_copy'
                                             ) as HTMLInputElement;

                                             if (el) {
                                                el.value = '';
                                             }
                                          }}
                                          className="rtl:gap-reverse flex items-center gap-2 rounded-xl bg-gradient-to-r from-red-500 to-red-600 px-4 py-2.5 text-sm font-medium text-white shadow-md focus:outline-none focus:ring-2 focus:ring-red-500/50 focus:ring-offset-2 focus:ring-offset-transparent">
                                          <TrashIcon className="h-4 w-4" />
                                          <span>
                                             <Translate id="web:delete" />
                                          </span>
                                       </button>
                                    </div>
                                 )
                              }
                              callBack={(id?: string | null, url?: string | null) => {
                                 setValue('document_copy', id || null, {
                                    shouldValidate: true,
                                 });
                                 try {
                                    // Save the base64 image in localStorage
                                    localStorage.setItem('doc1_x', url || '');
                                 } catch {
                                    console.log('Failed to save the image in localStorage');
                                 }
                              }}
                           />
                        )}
                        rules={{
                           required:
                              optionalFields && optionalFields.includes('document_copy')
                                 ? false
                                 : translate({ id: 'validation:required' }),
                        }}
                     />
                     {/* visa_copy */}
                     {getValues()['residency_status'] === 'foreign_national' &&
                     getValues()['valid_visa'] === 'yes' ? (
                        <Controller
                           name="visa_copy"
                           control={control}
                           render={({ field: { ref } }) => (
                              <CustomFileInput3
                                 label={translate({ id: 'web:visa_copy' })}
                                 id="visa_copy"
                                 isRequired={
                                    optionalFields && optionalFields.includes('visa_copy')
                                       ? false
                                       : true
                                 }
                                 error={errors.visa_copy?.message || errors.visa_copy?.message}
                                 ref={ref}
                                 inputName="visa_copy"
                                 help={
                                    <React.Fragment>
                                       <span className="block text-center text-sm text-white">
                                          <Translate id="web:only_pdf_jpg_png" />
                                       </span>
                                    </React.Fragment>
                                 }
                                 placeholderImg={
                                    getValues()['visa_copy'] !== null &&
                                    doc2_x && (
                                       <div className="rtl:gap-reverse flex items-center justify-center gap-3 py-2">
                                          <button
                                             type="button"
                                             onClick={() => setIsOpen2(true)}
                                             className="rtl:gap-reverse flex items-center gap-2 rounded-xl border-2 border-purple-500/80 bg-purple-500/10 px-4 py-2.5 text-sm font-medium text-purple-400 focus:outline-none focus:ring-2 focus:ring-purple-500/50 focus:ring-offset-2 focus:ring-offset-transparent">
                                             <span>
                                                <Translate id="web:view_file" />
                                             </span>
                                             <ArrowTopRightOnSquareIcon className="h-4 w-4" />
                                          </button>
                                          <button
                                             type="button"
                                             onClick={() => {
                                                setValue('visa_copy', null, {
                                                   shouldValidate: true,
                                                });
                                                localStorage.removeItem('doc2_x');

                                                const el = document.getElementById(
                                                   'visa_copy'
                                                ) as HTMLInputElement;

                                                if (el) {
                                                   el.value = '';
                                                }
                                             }}
                                             className="rtl:gap-reverse flex items-center gap-2 rounded-xl bg-gradient-to-r from-red-500 to-red-600 px-4 py-2.5 text-sm font-medium text-white shadow-md focus:outline-none focus:ring-2 focus:ring-red-500/50 focus:ring-offset-2 focus:ring-offset-transparent">
                                             <TrashIcon className="h-4 w-4" />
                                             <span>
                                                <Translate id="web:delete" />
                                             </span>
                                          </button>
                                       </div>
                                    )
                                 }
                                 callBack={(id?: string | null, url?: string | null) => {
                                    setValue('visa_copy', id || null, {
                                       shouldValidate: true,
                                    });
                                    try {
                                       // Save the base64 image in localStorage
                                       localStorage.setItem('doc2_x', url || '');
                                    } catch {
                                       console.log('Failed to save the image in localStorage');
                                    }
                                 }}
                              />
                           )}
                           rules={{
                              required:
                                 optionalFields && optionalFields.includes('visa_copy')
                                    ? false
                                    : translate({ id: 'validation:required' }),
                           }}
                        />
                     ) : (
                        ''
                     )}
                  </div>
               </div>
            </div>
         </React.Fragment>
      );
   };

   const renderDocumentNumberPlaceHolder = (documentType: string | null) => {
      switch (documentType) {
         case 'saudi_id':
            return translate({
               id: 'web:document_number_saudi_id',
            });
         case 'passport':
            return translate({
               id: 'web:document_number_passport',
            });
         case 'iqama_id':
            return translate({
               id: 'web:document_number_iqama_id',
            });
         default:
            return translate({
               id: 'web:document_number',
            });
      }
   };

   return (
      <React.Fragment>
         {step === 'personal-info-2' ? (
            <div className="rounded-lg border shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)]">
               <div className="p-6 sm:p-12">
                  <div className=" text-xl font-bold capitalize text-primary md:mb-4 md:text-2xl">
                     <Translate id="web:id_information" />
                  </div>
                  <div className="pt-5">
                     <form
                        noValidate
                        onSubmit={handleSubmit(submitForm)}
                        className="relative"
                        autoComplete="off">
                        <div>
                           {/* residency_status */}
                           {watch('is_saudi') === 'no' && (
                              <React.Fragment>
                                 <div className="row">
                                    <div className="self-center md:mb-5 md:col-3">
                                       <Label
                                          id="residency_status"
                                          isRequired
                                          label={translate({ id: 'web:residency_status' })}
                                       />
                                    </div>
                                    <div className="md:col-9">
                                       <Controller
                                          name="residency_status"
                                          control={control}
                                          render={() => (
                                             <StaticSelectNew
                                                options={
                                                   residencyStatusTypes &&
                                                   residencyStatusTypes?.length > 0
                                                      ? ResidencyStatusTypesSelect.filter(x =>
                                                           residencyStatusTypes?.includes(x.value)
                                                        )
                                                      : ResidencyStatusTypesSelect
                                                }
                                                selected_id={watch('residency_status')}
                                                label=""
                                                placeholderTranslationId="web:select_residency_status"
                                                dropdownRounded="none"
                                                errors={errors.residency_status?.message}
                                                isRequired={true}
                                                callBack={(item: { value: string } | null) => {
                                                   setValue(
                                                      'residency_status',
                                                      item?.value || null,
                                                      {
                                                         shouldValidate: true,
                                                      }
                                                   );
                                                   setValue('document_type', null, {
                                                      shouldValidate: false,
                                                   });
                                                   setValue('valid_visa', null, {
                                                      shouldValidate: false,
                                                   });

                                                   if (item?.value === 'saudi_residency') {
                                                      setValue('document_type', 'iqama_id');
                                                   }
                                                   if (item?.value === 'gcc') {
                                                      setValue('document_type', 'passport');
                                                   }
                                                   if (item?.value === 'foreign_national') {
                                                      setValue('document_type', 'passport');
                                                   }
                                                }}
                                             />
                                          )}
                                          rules={{
                                             required: translate({
                                                id: 'validation:required',
                                             }),
                                          }}
                                       />
                                    </div>
                                 </div>
                              </React.Fragment>
                           )}
                           <div>
                              {watch('is_saudi') === 'yes' ? (
                                 <React.Fragment>{renderInnerInputs(true)}</React.Fragment>
                              ) : watch('is_saudi') === 'no' &&
                                watch('residency_status') !== null ? (
                                 watch('residency_status') === 'saudi_residency' ||
                                 watch('residency_status') === 'gcc' ||
                                 watch('residency_status') === 'foreign_national' ? (
                                    <React.Fragment>{renderInnerInputs(false)}</React.Fragment>
                                 ) : (
                                    ''
                                 )
                              ) : (
                                 ''
                              )}
                           </div>
                        </div>
                        <div className="mt-10">
                           <div className="row ">
                              <div className="col-6 sm:col-3 sm:offset-3">
                                 <BackBtn
                                    id="back-btn" //* for test cases
                                    callBack={() => {
                                       onBackClick();
                                    }}
                                    text={`${translate({ id: `web:back` })}`}
                                 />
                              </div>
                              <div className="col-6 sm:col-3">
                                 <SubmitBtn
                                    id="submit-btn" //* for test cases
                                    loading={loading}
                                    text={`${translate({
                                       id: `web:${stepsNumber === 4 ? 'next' : 'submit'}`,
                                    })}`}
                                 />
                              </div>
                           </div>
                        </div>
                     </form>
                  </div>
               </div>
            </div>
         ) : (
            ''
         )}
         <Modal size="md" open={isOpen}>
            <Modal.Body>
               <div className="">
                  <div className="relative rounded-lg border bg-white p-4 shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)] sm:px-10 sm:py-6">
                     <div className="">
                        <div className="row">
                           <div className="col-12">
                              <div className="">
                                 <img
                                    src={doc1_x || ''}
                                    className="border border-primary object-cover"
                                 />
                              </div>
                           </div>
                        </div>
                        <div className="row mt-5">
                           <div className="md:col-6 md:offset-3">
                              <button
                                 type="button"
                                 className={classNames(
                                    ' block w-full  border border-gray-500 px-4 py-[11px] text-center text-sm font-medium leading-5 text-gray-500 transition-colors duration-150  focus:outline-none focus:ring  focus:ring-opacity-50  ',
                                    'disabled:cursor-not-allowed disabled:opacity-50 ',
                                    'enabled:focus:ring-accent enabled:focus:ring-opacity-50 '
                                 )}
                                 onClick={() => {
                                    setIsOpen(false);
                                 }}>
                                 <Translate id="web:no_cancel" />
                              </button>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </Modal.Body>
         </Modal>
         <Modal size="md" open={isOpen2}>
            <Modal.Body>
               <div className="">
                  <div className="relative rounded-lg border bg-white p-4 shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)] sm:px-10 sm:py-6">
                     <div className="">
                        <div className="row">
                           <div className="col-12">
                              <div className="">
                                 <img
                                    src={doc2_x || ''}
                                    className="border border-primary object-cover"
                                 />
                              </div>
                           </div>
                        </div>
                        <div className="row mt-5">
                           <div className="md:col-6 md:offset-3">
                              <button
                                 type="button"
                                 className={classNames(
                                    ' block w-full  border border-gray-500 px-4 py-[11px] text-center text-sm font-medium leading-5 text-gray-500 transition-colors duration-150  focus:outline-none focus:ring  focus:ring-opacity-50  ',
                                    'disabled:cursor-not-allowed disabled:opacity-50 ',
                                    'enabled:focus:ring-accent enabled:focus:ring-opacity-50 '
                                 )}
                                 onClick={() => {
                                    setIsOpen2(false);
                                 }}>
                                 <Translate id="web:no_cancel" />
                              </button>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </Modal.Body>
         </Modal>
      </React.Fragment>
   );
};

export default PersonalInfo2;
