import classNames from 'classnames';
import React, { useEffect, useState } from 'react';
import { ClassicSpinner } from 'react-spinners-kit';
import { Translate, useTranslate } from '~/i18n';
import Axios from '~/utils/axios';
import { CustomSelect } from '../forms/custom-select';
import { useRouter } from 'next/router';
import Label from '../forms/label';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type Item = {
   value: string;
   label: string;
};
type PositionSelectProps = {
   // type: 'whole' | 'part';
   callBack: (value: any) => void;
   errors: string | undefined;
   selected_id?: string | null;
   label?: string;
   isRequired?: boolean;
   isPhoneCode?: boolean;

   // role?: string;
};

const PositionSelect = ({
   label,
   callBack,
   errors,
   selected_id,
   isRequired,
}: // role,
// isPhoneCode,
PositionSelectProps) => {
   const { lang, translate } = useTranslate();
   const [fetchLoading, setFetchLoading] = useState(false);

   // const [hasError, setHasError] = useState(false);
   const [list, setList] = useState<any>([]);
   const router = useRouter();
   // console.log(router.query.category, 'router');
   const role = router.query.category;
   useEffect(() => {
      const fetchData = async () => {
         setFetchLoading(true);
         try {
            const response = await Axios.get(`/positions-select/${role}?lang=${lang}`);

            setList(response.data.data);
            setFetchLoading(false);
         } catch (error: any) {
            setFetchLoading(false);
            // setCountries([]);
            // setHasError(true);
         }
      };
      if (role) {
         fetchData();
      }
   }, [lang, role]);

   const options: Item[] = list.map((country: any) => ({
      value: country.id,
      label: `${country.name}`,
   }));

   const selected = options.find(item => item.value === selected_id);

   return (
      <React.Fragment>
         <div className={classNames(label ? 'row' : 'relative mb-5 w-full')}>
            {/* //todo */}
            {label && (
               <div className={classNames(label ? 'mb-5 self-center md:col-3' : '')}>
                  <Label id={''} label={label} isRequired={isRequired} />
               </div>
            )}
            <div className={classNames(label ? 'md:col-9' : '')}>
               {fetchLoading ? (
                  <div className="custom-input focus:shadow-outline-purple mb-5 block w-full animate-pulse select-none rounded-md">
                     <div className="flex">
                        <div className="my-auto">
                           <Translate id="web:loading" />
                        </div>
                        <div className="my-auto ltr:ml-4 rtl:mr-4">
                           <ClassicSpinner color="#bebebe" size={20} />
                        </div>
                     </div>
                  </div>
               ) : (
                  <CustomSelect
                     value={selected || ''}
                     placeholder={translate({ id: 'web:select_position' })}
                     onChange={callBack}
                     groupClassName="relative"
                     // id="countries_id"
                     options={options}
                     error={errors}
                  />
               )}
            </div>
         </div>
      </React.Fragment>
   );
};

export default PositionSelect;
