import classNames from 'classnames';
import React, { useEffect, useState } from 'react';
import { ClassicSpinner } from 'react-spinners-kit';
import { Translate, useTranslate } from '~/i18n';
import Axios from '~/utils/axios';
import { CustomSelect } from '../forms/custom-select';
import { useRouter } from 'next/router';
import Label from '../forms/label';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/
interface Data {
   id: string;
   name: string;
   allowed_genders: string[];
   gender_specific_ar: any;
   // Define other properties as needed
}

type Item = {
   value: string;
   label: string;
};
type TitleSelectProps = {
   // type: 'whole' | 'part';
   callBack: (value: any) => void;
   errors: string | undefined;
   selected_id?: string | null;
   label?: string;
   isRequired?: boolean;
   isPhoneCode?: boolean;
   gender: string | null;

   // role?: string;
};

const TitleSelect = ({
   label,
   callBack,
   errors,
   selected_id,
   isRequired,
   gender,
}: // role,
// isPhoneCode,
TitleSelectProps) => {
   const { lang, translate } = useTranslate();
   const [fetchLoading, setFetchLoading] = useState(false);

   // const [hasError, setHasError] = useState(false);
   const [list, setList] = useState<any>([]);
   const router = useRouter();
   // console.log(router.query.category, 'router');
   const role = router.query.category;
   useEffect(() => {
      const fetchData = async () => {
         setFetchLoading(true);
         try {
            const response = await Axios.get(`/titles-select/${role}?lang=${lang}`);

            setList(response.data.data);
            setFetchLoading(false);
         } catch (error: any) {
            setFetchLoading(false);
            // setCountries([]);
            // setHasError(true);
         }
      };
      if (role) {
         fetchData();
      }
   }, [lang, role]);

   // Assuming gender is defined elsewhere
   // Assuming gender and translation logic are defined elsewhere
   // Assuming gender and translation logic are defined elsewhere
   const options: Item[] = list
      .filter((item: Data) => {
         // Apply gender filter if gender exists, otherwise return the full list
         return gender ? item.allowed_genders?.includes(gender) : true;
      })
      .map((item: Data) => {
         // Check for missing gender-specific translation and fallback to default name if not available
         const genderSpecificName =
            lang === 'en'
               ? item.name
               : gender === 'male'
               ? item.gender_specific_ar?.male || item.name // Use default name if male translation is missing
               : gender === 'female'
               ? item.gender_specific_ar?.female || item.name // Use default name if female translation is missing
               : item.name; // Default to the generic name if gender doesn't match

         return {
            value: item.id,
            label: `${genderSpecificName}`, // Use gender-specific translation or fallback
         };
      });

   const selected = options.find(item => item.value === selected_id);

   return (
      <React.Fragment>
         <div className={classNames(label ? 'row mb-6' : 'relative mb-6 w-full pb-1')}>
            {/* //todo */}
            {label && (
               <div className={classNames(label ? 'self-center md:col-3' : '')}>
                  <Label id={''} label={label} isRequired={isRequired} />
               </div>
            )}
            <div className={classNames(label ? 'md:col-9' : '')}>
               {fetchLoading ? (
                  <div className="custom-input focus:shadow-outline-purple mb-5 block w-full animate-pulse select-none rounded-md">
                     <div className="flex">
                        <div className="my-auto">
                           <Translate id="web:loading" />
                        </div>
                        <div className="my-auto ltr:ml-4 rtl:mr-4">
                           <ClassicSpinner color="#bebebe" size={20} />
                        </div>
                     </div>
                  </div>
               ) : (
                  <CustomSelect
                     value={selected || ''}
                     placeholder={translate({ id: 'web:select_title' })}
                     onChange={callBack}
                     groupClassName="relative"
                     // id="countries_id"
                     options={options}
                     error={errors}
                  />
               )}
            </div>
         </div>
      </React.Fragment>
   );
};

export default TitleSelect;
