import { Translate, useTranslate } from '~/i18n';
import React, { useEffect, useState, useCallback, useRef } from 'react';
import { useForm, FormProvider } from 'react-hook-form';
import CustomInput from '../shared/forms/custom-input';
import { toast } from 'react-hot-toast';
import { useGoogleReCaptcha } from 'react-google-recaptcha-v3';
import Axios from '~/utils/axios';
import classNames from 'classnames';
import ButtonBtn from '../shared/buttons/button-btn';
import SubmitBtn from '../shared/buttons/submit-btn';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/
type VerifyEmailFormProps = {
   userEmail: string;
   userPhone?: string;
   setIsOpen: React.Dispatch<React.SetStateAction<boolean>>;
   callBack: (tokens: { emailToken?: string; phoneToken?: string }) => void;

   // feature flags
   isPhoneVerificationOn?: boolean;
   isEmailVerificationOn?: boolean;
   // Auto-send phone OTP and skip first step (phone number display)
   autoSendPhoneOtp?: boolean;

   // Optional form data to save in draft
   formData?: {
      email?: string | null;
      gender?: string | null;
      title_id?: string | null;
      first_name?: string | null;
      last_name?: string | null;
      company?: string | null;
      job_title?: string | null;
      invitation_token?: string | null;
      category?: string | null;
   };
};

type VerificationStep = 'email' | 'phone';

type FormData = {
   token: string;
   phone_token: string;
};

const VerifyEmailForm = ({
   userEmail,
   userPhone,
   setIsOpen,
   callBack,
   isPhoneVerificationOn,
   isEmailVerificationOn,
   formData,
   autoSendPhoneOtp = false,
}: VerifyEmailFormProps) => {
   const { lang, translate } = useTranslate();
   const { executeRecaptcha } = useGoogleReCaptcha();

   // ---- feature flags / modes ----
   const rawEmailFlag = Boolean(isEmailVerificationOn);
   const rawPhoneFlag = Boolean(isPhoneVerificationOn && userPhone);

   // default behavior: if neither flag is set => email-only (backward compatible)
   let emailVerificationEnabled = rawEmailFlag;
   let phoneVerificationEnabled = rawPhoneFlag;

   if (!isEmailVerificationOn && !isPhoneVerificationOn) {
      // old behavior: email only
      emailVerificationEnabled = true;
      phoneVerificationEnabled = false;
   }

   // if phone flag is true but phone missing, disable phone mode
   if (isPhoneVerificationOn && !userPhone) {
      phoneVerificationEnabled = false;
   }

   const [loading, setLoading] = useState(false); // send email/phone code
   const [loading2, setLoading2] = useState(false); // verify code
   const [holdOn, setHoldOn] = useState(true);
   // If autoSendPhoneOtp is true, skip first modal and show code entry form directly
   const [isSent, setIsSent] = useState(
      autoSendPhoneOtp && phoneVerificationEnabled && !emailVerificationEnabled
   );
   const [emailToken, setEmailToken] = useState<string | null>(null);

   const [currentStep, setCurrentStep] = useState<VerificationStep>(
      emailVerificationEnabled ? 'email' : 'phone'
   );

   const [timeLeft, setTimeLeft] = useState(30);
   const hasAutoSentRef = useRef(false); // Track if we've already auto-sent the OTP

   const methods = useForm<FormData>();
   const {
      register,
      handleSubmit,
      formState: { errors },
   } = methods;

   // ---------------- SEND CODES ----------------
   const sendEmailVerification = async () => {
      if (!emailVerificationEnabled) return;
      if (loading) return;

      setLoading(true);
      const recaptcha = await executeRecaptcha?.();

      try {
         await Axios.post(`/guests/email-verification?lang=${lang}`, {
            phone: userPhone,
            recaptcha,
            ...(formData || {}), // Include form data if provided
            email: (formData?.email || userEmail || '').toLowerCase(), // Ensure email is always included and lowercase
         });

         setHoldOn(true);
         setIsSent(true);
         toast.success(translate({ id: 'res:check_your_email' }));
      } catch (error: any) {
         if (error?.response?.status === 403) {
            toast.error(translate({ id: 'res:recaptcha_failed' }), { duration: 6000 });
         } else {
            toast.error(translate({ id: 'res:500' }), { duration: 6000 });
         }
      }

      setLoading(false);
   };

   const sendPhoneVerification = useCallback(async () => {
      if (!phoneVerificationEnabled) return;
      if (!userPhone) {
         toast.error('Phone number is missing');
         return;
      }
      if (loading) return;

      setLoading(true);
      const recaptcha = await executeRecaptcha?.();

      try {
         await Axios.post(`/guests/phone-verification?lang=${lang}`, {
            phone: userPhone,
            email: userEmail || formData?.email || '',
            recaptcha,
            ...(formData || {}), // Include form data if provided
         });

         setHoldOn(true);
         setIsSent(true);
         toast.success(translate({ id: 'res:phone_verification_code_sent' }));
      } catch (error: any) {
         if (error?.response?.status === 403) {
            toast.error(translate({ id: 'res:recaptcha_failed' }), { duration: 6000 });
         } else {
            toast.error(translate({ id: 'res:500' }) || 'Failed to send verification code', {
               duration: 6000,
            });
         }
      }

      setLoading(false);
   }, [
      phoneVerificationEnabled,
      userPhone,
      loading,
      executeRecaptcha,
      lang,
      translate,
      formData,
      userEmail,
   ]);

   // Auto-send phone OTP if flag is enabled and we're on phone step
   // Skip first modal by setting isSent=true initially, but still send OTP in background
   useEffect(() => {
      if (
         autoSendPhoneOtp &&
         phoneVerificationEnabled &&
         currentStep === 'phone' &&
         !hasAutoSentRef.current &&
         !loading &&
         userPhone
      ) {
         hasAutoSentRef.current = true;
         sendPhoneVerification();
      }
   }, [
      autoSendPhoneOtp,
      phoneVerificationEnabled,
      currentStep,
      loading,
      userPhone,
      sendPhoneVerification,
   ]);

   useEffect(() => {
      if (!holdOn) return setTimeLeft(30);
      if (!timeLeft) return setHoldOn(false);

      const intervalId = setInterval(() => {
         setTimeLeft(prev => prev - 1);
      }, 1000);

      return () => clearInterval(intervalId);
   }, [holdOn, timeLeft]);

   const handleResend = async () => {
      if (currentStep === 'email') {
         await sendEmailVerification();
      } else if (currentStep === 'phone') {
         await sendPhoneVerification();
      }
   };

   // ---------------- VERIFY CODES ----------------
   const verifyEmailToken = async (values: FormData) => {
      if (!emailVerificationEnabled) return;
      if (loading2) return;

      setLoading2(true);
      const recaptcha = await executeRecaptcha?.();

      try {
         const response = await Axios.post(`/guests/email-confirmation?lang=${lang}`, {
            token: values.token,
            recaptcha,
         });

         // toast.success(translate({ id: 'res:verification_done' }));

         if (phoneVerificationEnabled) {
            // email -> then phone
            setEmailToken(response.data.token);
            // If autoSendPhoneOtp is enabled, skip first modal and show code entry directly
            setIsSent(autoSendPhoneOtp);
            setHoldOn(true);
            setTimeLeft(30);
            setCurrentStep('phone');
            // Reset auto-send ref so it can trigger when transitioning to phone step
            hasAutoSentRef.current = false;
         } else {
            // email-only mode => finish
            setIsOpen(false);
            callBack({ emailToken: response.data.token });
         }
      } catch (error: any) {
         if (error?.response?.status === 403) {
            toast.error(translate({ id: 'res:recaptcha_failed' }), { duration: 6000 });
         } else if (error?.response?.status === 404) {
            toast.error(translate({ id: 'res:wrong_token' }), { duration: 4000 });
         } else {
            toast.error(translate({ id: 'res:500' }), { duration: 6000 });
         }
      }

      setLoading2(false);
   };

   const verifyPhoneToken = async (values: FormData) => {
      if (!phoneVerificationEnabled) return;
      if (loading2) return;

      setLoading2(true);
      const recaptcha = await executeRecaptcha?.();

      try {
         const response = await Axios.post(`/guests/phone-confirmation?lang=${lang}`, {
            token: values.phone_token,
            phone: userPhone,
            recaptcha,
         });

         // toast.success(translate({ id: 'res:phone_verification_done' }));
         setIsOpen(false);

         // Pass both tokens if email was verified, otherwise just phone token
         callBack({
            emailToken: emailToken || undefined,
            phoneToken: response.data.token,
         });
      } catch (error: any) {
         if (error?.response?.status === 403) {
            toast.error(translate({ id: 'res:recaptcha_failed' }), { duration: 6000 });
         } else if (error?.response?.status === 404) {
            toast.error(translate({ id: 'res:wrong_token' }), { duration: 4000 });
         } else {
            toast.error(translate({ id: 'res:500' }), { duration: 6000 });
         }
      }

      setLoading2(false);
   };

   /********************************************************
    * EMAIL VERIFICATION STEP (if enabled)
    ********************************************************/
   if (currentStep === 'email' && emailVerificationEnabled) {
      return (
         <FormProvider {...methods}>
            {isSent ? (
               <form noValidate onSubmit={handleSubmit(verifyEmailToken)} className="relative">
                  <div className="text-center text-xl text-white">
                     <Translate id="web:email_verification" />
                  </div>
                  <div className="mb-3 text-center text-white">
                     <Translate id="web:please_enter_the_code" /> {userEmail}
                  </div>
                  <CustomInput
                     type="text"
                     isInline={false}
                     placeHolder={translate({ id: 'web:code' })}
                     id="token"
                     error={errors.token?.message}
                     {...register('token', {
                        required: translate({ id: 'validation:required' }),
                     })}
                  />

                  <>
                     <div className="row">
                        <div className="col-6">
                           <button
                              type="button"
                              className={classNames(
                                 'block w-full border border-gray-500 px-4 py-[10px] text-center text-sm font-medium leading-5 text-gray-500 transition-colors duration-150 focus:outline-none focus:ring focus:ring-opacity-50',
                                 'disabled:cursor-not-allowed disabled:opacity-50',
                                 'enabled:focus:ring-accent enabled:focus:ring-opacity-50',
                                 'rounded-xl'
                              )}
                              disabled={holdOn}
                              onClick={() => setIsOpen(false)}>
                              <Translate id="web:no_cancel" />
                           </button>
                        </div>
                        <div className="col-6">
                           <SubmitBtn
                              id="submit-btn"
                              text={translate({ id: 'web:verify_now' })}
                              loading={loading2}
                           />
                        </div>
                     </div>
                     <div className="row">
                        <div className="col-12">
                           <p className="mt-4 text-white">
                              <Translate id="web:did_not_get_verification_code" />{' '}
                              {holdOn ? (
                                 <>
                                    <Translate id="web:send_after" /> {timeLeft}
                                 </>
                              ) : (
                                 <button
                                    type="button"
                                    onClick={handleResend}
                                    className="text-primary"
                                    disabled={loading}>
                                    {loading ? (
                                       <Translate id="web:loading" />
                                    ) : (
                                       <Translate id="web:resend" />
                                    )}
                                 </button>
                              )}
                           </p>
                           <p className="mt-2 text-white">
                              <Translate id="web:please_check_spam_junk_folder" />
                           </p>
                        </div>
                     </div>
                  </>
               </form>
            ) : (
               <div className="relative">
                  <div className="text-center text-xl text-white">
                     <Translate id="web:email_verification" />
                  </div>

                  <div className="mb-3 text-center text-white">
                     <Translate id="web:to_continue_you_need_to_verify_your_email_first" />
                  </div>

                  <div className="rounded-md border border-gray-500 py-2 text-center text-gray-500">
                     {userEmail}
                  </div>

                  <div className="row mt-5">
                     <div className="col-6">
                        <button
                           type="button"
                           className={classNames(
                              'block w-full border border-gray-500 px-4 py-[10px] text-center text-sm font-medium leading-5 text-gray-500 transition-colors duration-150 focus:outline-none focus:ring focus:ring-opacity-50',
                              'disabled:cursor-not-allowed disabled:opacity-50',
                              'enabled:focus:ring-accent enabled:focus:ring-opacity-50',
                              'rounded-xl'
                           )}
                           onClick={() => setIsOpen(false)}>
                           <Translate id="web:no_cancel" />
                        </button>
                     </div>
                     <div className="col-6">
                        <ButtonBtn
                           id="submit-btn"
                           text={translate({ id: 'web:verify_now' })}
                           loading={loading}
                           callBack={sendEmailVerification}
                        />
                     </div>
                  </div>
               </div>
            )}
         </FormProvider>
      );
   }

   /********************************************************
    * PHONE VERIFICATION STEP (if enabled)
    ********************************************************/
   if (currentStep === 'phone' && phoneVerificationEnabled) {
      return (
         <FormProvider {...methods}>
            {isSent ? (
               <form noValidate onSubmit={handleSubmit(verifyPhoneToken)} className="relative">
                  <div className="text-center text-xl text-white">
                     <Translate id="web:phone_verification" />
                  </div>
                  <div className="mb-3 text-center text-white">
                     <Translate id="web:please_enter_the_code_phone" />{' '}
                     <span dir="ltr">{userPhone}</span>
                  </div>
                  <CustomInput
                     type="text"
                     isInline={false}
                     placeHolder={translate({ id: 'web:code' })}
                     id="phone_token"
                     error={errors.phone_token?.message}
                     {...register('phone_token', {
                        required: translate({ id: 'validation:required' }),
                     })}
                  />

                  <>
                     <div className="row">
                        <div className="col-6">
                           <button
                              type="button"
                              className={classNames(
                                 'block w-full border border-gray-500 px-4 py-[10px] text-center text-sm font-medium leading-5 text-gray-500 transition-colors duration-150 focus:outline-none focus:ring focus:ring-opacity-50',
                                 'disabled:cursor-not-allowed disabled:opacity-50',
                                 'enabled:focus:ring-accent enabled:focus:ring-opacity-50',
                                 'rounded-xl'
                              )}
                              disabled={holdOn}
                              onClick={() => setIsOpen(false)}>
                              <Translate id="web:no_cancel" />
                           </button>
                        </div>
                        <div className="col-6">
                           <SubmitBtn
                              id="submit-btn"
                              text={translate({ id: 'web:verify_now' })}
                              loading={loading2}
                           />
                        </div>
                     </div>
                     <div className="row">
                        <div className="col-12">
                           <p className="mt-4 text-white">
                              <Translate id="web:did_not_get_verification_code" />{' '}
                              {holdOn ? (
                                 <>
                                    <Translate id="web:send_after" /> {timeLeft}
                                 </>
                              ) : (
                                 <button
                                    type="button"
                                    onClick={handleResend}
                                    className="text-primary"
                                    disabled={loading}>
                                    {loading ? (
                                       <Translate id="web:loading" />
                                    ) : (
                                       <Translate id="web:resend" />
                                    )}
                                 </button>
                              )}
                           </p>
                        </div>
                     </div>
                  </>
               </form>
            ) : (
               <div className="relative">
                  <div className="text-center text-xl text-white">
                     <Translate id="web:phone_verification" />
                  </div>

                  <div className="mb-3 text-center text-white">
                     <Translate id="web:to_continue_you_need_to_verify_your_phone_first" />
                  </div>

                  <div
                     dir="ltr"
                     className="rounded-md border border-gray-500 py-2 text-center text-gray-500">
                     {userPhone}
                  </div>

                  <div className="row mt-5">
                     <div className="col-6">
                        <button
                           type="button"
                           className={classNames(
                              'block w-full border border-gray-500 px-4 py-[10px] text-center text-sm font-medium leading-5 text-gray-500 transition-colors duration-150 focus:outline-none focus:ring focus:ring-opacity-50',
                              'disabled:cursor-not-allowed disabled:opacity-50',
                              'enabled:focus:ring-accent enabled:focus:ring-opacity-50',
                              'rounded-xl'
                           )}
                           onClick={() => setIsOpen(false)}>
                           <Translate id="web:no_cancel" />
                        </button>
                     </div>
                     <div className="col-6">
                        <ButtonBtn
                           id="submit-btn"
                           text={translate({ id: 'web:verify_now' })}
                           loading={loading}
                           callBack={sendPhoneVerification}
                        />
                     </div>
                  </div>
               </div>
            )}
         </FormProvider>
      );
   }

   // if somehow step doesn't match any enabled mode, just fallback to null
   return null;
};

export default VerifyEmailForm;
