import classNames from 'classnames';
import ThreeDotsWave from '~/components/animation/three-dots-wave';
import { useTranslate } from '~/i18n';
// import { ArrowRightIcon } from '@heroicons/react/20/solid';
import React from 'react';
import { ArrowLeftIcon } from '@heroicons/react/20/solid';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/
type ButtonBtnProps = {
   loading?: boolean;
   text: string;
   id: string;
   className?: string;
   noIcon?: boolean;
   icon?: React.ReactNode;
   secondary?: boolean;
   disable?: boolean;
   customLoader?: React.ReactNode;
   callBack: () => void;
};

const BackBtn = ({
   className,
   loading,
   text,
   id,
   icon,
   // secondary,
   noIcon = false,
   disable,
   customLoader,
   callBack,
}: ButtonBtnProps) => {
   const { lang } = useTranslate();
   return (
      <button
         disabled={disable || loading}
         type="button"
         id={id}
         onClick={callBack}
         className={classNames(
            className,
            'block w-full border-none border-transparent px-4 py-3 text-center text-sm font-bold leading-5 text-white',
            (loading || disable) && 'disabled:cursor-not-allowed disabled:opacity-50',
            'bg-primary hover:bg-primary-600',
            // 'bg-gradient-to-r from-[#C3FF42] via-[#27CBC0] to-[#0077C0]',
            'focus:outline-none focus:ring focus:ring-primary focus:ring-opacity-50',
            'transition-all duration-150',
            'rounded-xl',
            'from-[#4E442D] to-gold-primary ltr:bg-gradient-to-r rtl:bg-gradient-to-l',
            'rounded-xl'
         )}>
         {noIcon ? (
            <span className="inline-flex">
               <div className={classNames('my-auto')}>
                  {loading ? (
                     <div className="w-8">
                        {customLoader ? customLoader : <ThreeDotsWave color="white" />}
                     </div>
                  ) : (
                     <div className="my-auto">{text}</div>
                  )}
               </div>
            </span>
         ) : (
            <div className="flex justify-center space-x-2 rtl:space-x-reverse">
               <div className={classNames('my-auto', lang === 'ar' && 'flip-x')}>
                  {loading ? (
                     <div className="w-8">
                        {customLoader ? customLoader : <ThreeDotsWave color="white" />}
                     </div>
                  ) : (
                     <React.Fragment>
                        {icon ? icon : <ArrowLeftIcon className="h-5 w-5" />}
                     </React.Fragment>
                  )}
               </div>
               <div className="my-auto">{text}</div>
            </div>
         )}
      </button>
   );
};

export default BackBtn;
