// import Image from '~/components/shared/image';
// import { useTranslate } from '~/i18n';
// import { publicUrl } from '~/utils/publicUrl';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const Section2 = () => {
   // const { lang } = useTranslate();
   // const { lang } = useTranslate();
   // const stores = [
   //    {
   //       href: '',
   //       src: `/images/app/${lang}/app_store.png`,
   //       label: 'app store',
   //    },
   //    {
   //       href: '',
   //       src: `/images/app/${lang}/google_play.png`,
   //       label: 'google play',
   //    },
   // ];
   return (
      <section>
         <div className="container">
            <div className="row pb-12">
               {/* <div className="col-10 offset-1 h-[64px] md:col-4 md:offset-4">
                  <Image
                     src="/images/footer_logos.png"
                     // height="300px"
                     // width="400px"
                     alt="about-img"
                     layout="fill"
                     objectFit="contain"
                     // className="lg:h-full"
                  />
               </div> */}
               {/* <div className="col-12">
                  <ul className=" mt-8 flex justify-center space-x-2 rtl:space-x-reverse">
                     {stores.map((item, index) => (
                        <li className="" key={index}>
                           <a
                              href={item.href}
                              target="_blank"
                              rel="noopener noreferrer"
                              aria-label={item.label}>
                              <img src={item.src} alt={item.label} className="w-32 sm:w-40" />
                           </a>
                        </li>
                     ))}
                  </ul>
               </div> */}
            </div>
         </div>
      </section>
   );
};

export default Section2;
