import classNames from 'classnames';
import React, { useEffect, useState } from 'react';
import { Controller, useFormContext } from 'react-hook-form';
import SubmitBtn from '~/components/shared/buttons/submit-btn';
import CustomInput from '~/components/shared/forms/custom-input';
import { Translate, useTranslate } from '~/i18n';
import toast from 'react-hot-toast';
import { GuestType } from '~/interfaces/guest';
import validator from 'validator';
import CustomRadioInput from '~/components/shared/forms/custom-radio-input';
import isUniqueAttribute from '~/utils/unique-attribute';
import Modal from '~/components/shared/modals';
import VerifyEmailForm from '../../../verify-email-form';
import { XMarkIcon } from '@heroicons/react/20/solid';
import CustomFileInput2 from '~/components/shared/forms/custom-file-input-2/custom-file-input';
// import CheckboxInput from '~/components/shared/forms/checkbox-input';
import { useGoogleReCaptcha } from 'react-google-recaptcha-v3';
import Axios from '~/utils/axios';
import Cookies from 'js-cookie';
import PhoneInputV2 from '~/components/shared/forms/phone-input-new';
import parsePhoneNumberFromString from 'libphonenumber-js';
import TitleSelectNew from '~/components/shared/select/titles-select-new';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type PersonalInfoShortProps = {
   onNextClick: () => any;
   onUpdateClick: () => any;
   onBackClick: () => any;
   setStep?: (val: string) => any;
   step?: string | undefined;
   nextStep?: string;
   // countries: CountryType[];
   guestEmail?: string | null;
   guestFirstName?: string | null;
   guestLastName?: string | null;
   guestCompany?: string | null;
   guestPosition?: string | null;
   prefilldata?: string | null;
   lock_data?: string | null;

   role?: string;
   optionalFields?: string[];
   mandatoryFields?: string[];
   withOtp: boolean;
   withSmsOtp: boolean;
   token?: string | null;
   withAlternativeEmail: boolean;
};

// type Item = {
//    label: string;
//    value: string;
// };

const PersonalInfoShort = ({
   onNextClick,
   // onBackClick,
   // onUpdateClick,
   step,
   // nextStep,
   // countries,
   guestEmail,
   guestFirstName,
   guestLastName,
   guestCompany,
   guestPosition,
   prefilldata,
   lock_data,
   role,
   // optionalFields,
   mandatoryFields,
   withOtp,
   withSmsOtp,
   token,
}: // withAlternativeEmail,
// role,
PersonalInfoShortProps) => {
   const { translate } = useTranslate();
   const [loading, setLoading] = useState(false);
   // setLockEmail
   const [verificationDone, setVerificationDone] = useState(false);
   // console.log(guestEmail, 'guestEmail');
   // console.log(guestFirstName, 'guestFirstName');
   // console.log(guestLastName, 'guestLastName');
   const [isOpen, setIsOpen] = useState(false);
   const { lang } = useTranslate();

   const {
      register,
      handleSubmit,
      getValues,
      control,
      setValue,
      watch,
      // trigger,

      formState: { errors },
   } = useFormContext<GuestType>();

   // Sync hasPlusOne with form value
   // const hasPlusOneValue = watch('has_plus_one');
   // const primaryEmail = watch('email');
   // useEffect(() => {
   //    setHasPlusOne(hasPlusOneValue === 'yes' || hasPlusOneValue === true);
   // }, [hasPlusOneValue]);

   // // Re-validate plus_one_email when primary email changes
   // useEffect(() => {
   //    if (hasPlusOne && primaryEmail) {
   //       trigger('plus_one_email');
   //    }
   // }, [primaryEmail, hasPlusOne, trigger]);

   const submitForm = async (values: GuestType) => {
      try {
         if (getValues('is_email_verified') === 'yes' || getValues('is_phone_verified') === 'yes') {
            submitForm2(values);
         } else {
            if (!withOtp && !withSmsOtp) {
               submitForm2(values);
            } else {
               setIsOpen(true);
            }
         }
      } catch (error: any) {
         console.log(error, 'error');
      }
      // setLoading(false);
   };
   // const submitForm2 = async () => {
   //    // setLoading(true);
   //    try {
   //       const values = getValues();

   //       const updatedUserObj = {
   //          ...values,
   //          step: nextStep,
   //       };
   //       // cookie.set('user_data', JSON.stringify(updatedUserObj));
   //       cookie.set('user_data', JSON.stringify(updatedUserObj), {
   //          secure: true, // Ensures the cookie is secure in production
   //          sameSite: 'Strict', // Prevents cross-site request forgery
   //       });
   //       toast.success(translate({ id: 'res:info_saved' }));
   //       // onNextClick();
   //    } catch (error: any) {
   //       console.log(error, 'error');
   //    }
   //    // setLoading(false);
   // };
   const { executeRecaptcha } = useGoogleReCaptcha();

   const submitForm2 = async (values: GuestType) => {
      setLoading(true);
      if (loading) {
         return;
      }
      setLoading(true);

      try {
         const recaptcha = await executeRecaptcha?.();

         const data = {
            ...values,
            code: token || '', //todo: check
            category: role,
            email: values?.email?.toLowerCase(),
            recaptcha,
         };

         // console.log(data, 'data');

         const response = await Axios.post(`guests?lang=${lang}`, data);
         Cookies.set('reg_num', response.data.data);

         // to success page
         onNextClick();
      } catch (error: any) {
         setLoading(false);
         if (error.response?.status === 404) {
            toast.error(error.response?.data?.data);
         } else if (error?.response?.status === 403) {
            toast.error(translate({ id: 'res:recaptcha_failed' }), {
               duration: 4000,
            });
         } else {
            toast.error(translate({ id: 'res:500' }));
         }
         console.log(error, 'error');
      }
   };

   const personal_image_x =
      (typeof window !== 'undefined' && localStorage.getItem('personal_image_x')) || '';

   // Prefill fields when prefilldata is "yes"
   useEffect(() => {
      if (prefilldata === 'yes') {
         if (guestFirstName) {
            setValue('first_name', guestFirstName, { shouldValidate: false });
         }
         if (guestLastName) {
            setValue('last_name', guestLastName, { shouldValidate: false });
         }
         if (guestEmail) {
            setValue('email', guestEmail, { shouldValidate: false });
         }
         if (guestCompany) {
            setValue('company', guestCompany, { shouldValidate: false });
         }
         if (guestPosition) {
            setValue('job_title', guestPosition, { shouldValidate: false });
         }
      }
   }, [
      prefilldata,
      guestFirstName,
      guestLastName,
      guestEmail,
      guestCompany,
      guestPosition,
      setValue,
   ]);

   // Determine if fields should be locked
   const isLocked = lock_data === 'yes';

   const getImgPlaceHolder = () => {
      switch (getValues('gender')) {
         case 'male':
            return '/images/man_dark.png';
         case 'female':
            return '/images/woman_dark.png';
         default:
            return '/images/man_dark.png';
      }
   };

   return (
      <React.Fragment>
         {step === 'personal-info-1' ? (
            <React.Fragment>
               <div className="rounded-xl border  shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)]">
                  <div className="p-6 sm:p-12">
                     <h2
                        className={classNames(
                           'text-xl font-bold capitalize text-white md:mb-4 md:text-2xl'
                        )}>
                        <Translate id="web:personal_information" />
                     </h2>

                     <div className="pt-5">
                        <form
                           noValidate
                           onSubmit={handleSubmit(submitForm)}
                           className="relative"
                           autoComplete="off">
                           {/* gender */}
                           <CustomRadioInput
                              label={translate({ id: 'web:gender' })}
                              isRequired={mandatoryFields?.includes('gender') ?? false}
                              isInline
                              options={[
                                 { value: 'male', label: translate({ id: 'web:male' }) },
                                 { value: 'female', label: translate({ id: 'web:female' }) },
                              ]}
                              id="gender"
                              error={errors.gender?.message}
                              {...register('gender', {
                                 required: mandatoryFields?.includes('gender')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                              })}
                           />
                           {/* title_id */}
                           <Controller
                              name="title_id"
                              control={control}
                              render={() => (
                                 <TitleSelectNew
                                    category={role}
                                    gender={watch('gender')}
                                    isRequired={mandatoryFields?.includes('title_id') ?? false}
                                    selected_id={getValues()['title_id']} // on edit
                                    label={translate({ id: 'web:title' })}
                                    errors={errors.title_id?.message}
                                    callBack={(item: { value: string } | null) => {
                                       setValue('title_id', item?.value || null, {
                                          shouldValidate: true,
                                       });
                                    }}
                                 />
                              )}
                              rules={{
                                 required: mandatoryFields?.includes('title_id')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                              }}
                           />

                           {/* first_name */}
                           <CustomInput
                              label={translate({ id: 'web:first_name' })}
                              type="text"
                              isRequired={mandatoryFields?.includes('first_name') ?? false}
                              isInline
                              autoComplete="off"
                              placeHolder={translate({ id: 'web:first_name' })}
                              id="first_name"
                              disabled={isLocked}
                              error={errors.first_name?.message}
                              {...register('first_name', {
                                 required: mandatoryFields?.includes('first_name')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 pattern: {
                                    value: /^[a-zA-Z0-9 -]+$/i,
                                    message: translate({
                                       id: 'validation:english_letters',
                                    }),
                                 },
                              })}
                           />

                           {/* last_name */}
                           <CustomInput
                              label={translate({ id: 'web:last_name' })}
                              type="text"
                              autoComplete="off"
                              placeHolder={translate({ id: 'web:last_name' })}
                              id="last_name"
                              isRequired={mandatoryFields?.includes('last_name') ?? false}
                              isInline
                              disabled={isLocked}
                              error={errors.last_name?.message}
                              {...register('last_name', {
                                 required: mandatoryFields?.includes('last_name')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 pattern: {
                                    value: /^[a-zA-Z0-9 -]+$/i,
                                    message: translate({
                                       id: 'validation:english_letters',
                                    }),
                                 },
                              })}
                           />

                           {/* company */}
                           <CustomInput
                              label={translate({ id: 'web:company' })}
                              type="text"
                              autoComplete="off"
                              // disabled={!!user && role !== 'xrole-name'}
                              placeHolder={translate({ id: 'web:company' })}
                              id="company"
                              isRequired={mandatoryFields?.includes('company') ?? false}
                              isInline
                              disabled={isLocked}
                              error={errors.company?.message}
                              {...register('company', {
                                 required: mandatoryFields?.includes('company')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 maxLength: {
                                    value: 100,
                                    message: translate({
                                       id: 'validation:you_reached_the_text_limit',
                                    }),
                                 },
                                 pattern: {
                                    value: /^(?!.*[\u0600-\u06FF]).+$/,
                                    message: translate({
                                       id: 'validation:english_letters',
                                    }),
                                 },
                              })}
                           />

                           {/* job_title */}
                           <CustomInput
                              label={translate({ id: 'web:job_title' })}
                              type="text"
                              autoComplete="off"
                              // disabled={!!user && role !== 'xrole-name'}
                              placeHolder={translate({ id: 'web:job_title' })}
                              id="job_title"
                              isRequired={mandatoryFields?.includes('job_title') ?? false}
                              isInline
                              error={errors.job_title?.message}
                              {...register('job_title', {
                                 required: mandatoryFields?.includes('job_title')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 maxLength: {
                                    value: 100,
                                    message: translate({
                                       id: 'validation:you_reached_the_text_limit',
                                    }),
                                 },
                                 pattern: {
                                    value: /^(?!.*[\u0600-\u06FF]).+$/,
                                    message: translate({
                                       id: 'validation:english_letters',
                                    }),
                                 },
                              })}
                           />

                           {/* email */}
                           <CustomInput
                              label={translate({ id: 'web:email' })}
                              type="email"
                              // disabled={!!user && role == 'xrole-name'}
                              isRequired={mandatoryFields?.includes('email') ?? false}
                              isInline
                              placeHolder={translate({ id: 'web:email' })}
                              id="email"
                              disabled={isLocked || verificationDone}
                              error={errors.email?.message}
                              {...register('email', {
                                 required: mandatoryFields?.includes('email')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 // value: guestEmail,
                                 validate: {
                                    trim: (value: any) =>
                                       value == value.trim() || 'يرجى حذف المسافات',
                                    isEmail: value => {
                                       // If field is not mandatory and empty, skip validation
                                       if (!mandatoryFields?.includes('email') && !value) {
                                          return true;
                                       }
                                       // If mandatory or has value, validate email format
                                       return (
                                          validator.isEmail(value || '') ||
                                          translate({ id: 'validation:not_email' })
                                       );
                                    },
                                    isUnique: async value => {
                                       // If field is not mandatory and empty, skip uniqueness check
                                       if (!mandatoryFields?.includes('email') && !value) {
                                          return true;
                                       }
                                       const { isUnique, status } = await isUniqueAttribute(
                                          'guests',
                                          'email',
                                          value,
                                          'create',
                                          getValues('id')
                                       );
                                       if (!isUnique && status === 422) {
                                          return translate({ id: 'validation:unique_email' });
                                       } else if (!isUnique) {
                                          return translate({
                                             id: 'validation:unique_email_failed',
                                          });
                                       } else {
                                          return true;
                                       }
                                    },
                                 },
                              })}
                           />

                           {/* phone (single field with flags + masking; stores E.164 in `phone`) */}
                           <Controller
                              name="phone"
                              control={control}
                              rules={{
                                 required: mandatoryFields?.includes('phone')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 validate: (v?: string | null) => {
                                    if (!mandatoryFields?.includes('phone') && !v) {
                                       return true; // Not required, so empty is valid
                                    }
                                    const s = (v ?? '').replace(/\s+/g, '');
                                    const pn = parsePhoneNumberFromString(s);
                                    return pn?.isValid()
                                       ? true
                                       : translate({ id: 'validation:invalid_phone' });
                                 },
                              }}
                              render={({ field }) => (
                                 <PhoneInputV2
                                    lang={lang}
                                    label={translate({ id: 'web:phone' })}
                                    isInline
                                    isRequired={mandatoryFields?.includes('phone') ?? false}
                                    defaultCountry="sa"
                                    // onlyCountries={ONLY_COUNTRIES}
                                    value={field.value ?? ''}
                                    onChange={field.onChange}
                                    // show error only after touch or submit
                                    error={errors.phone?.message}
                                 />
                              )}
                           />

                           <div>
                              <hr className="my-7 border-white/50" />
                              {/* <p className="text-accent">
                                             <Translate id="web:upload_document_p" />
                                          </p> */}
                              <div className="mt-4">
                                 {/* personal_image */}
                                 <Controller
                                    name="personal_image"
                                    control={control}
                                    render={({ field: { ref } }) => (
                                       <CustomFileInput2
                                          label={translate({ id: 'web:personal_image' })}
                                          id="personal_image"
                                          isRequired={
                                             mandatoryFields?.includes('personal_image') ?? false
                                          }
                                          error={
                                             errors.personal_image?.message ||
                                             errors.personal_image?.message
                                          }
                                          ref={ref}
                                          // inputName="personal_image"
                                          withCrop
                                          note={
                                             <React.Fragment>
                                                <span className="block text-center text-sm text-white">
                                                   <Translate id="web:upload_document_p" />
                                                </span>
                                             </React.Fragment>
                                          }
                                          placeholderImg={
                                             <div className="relative mx-auto h-[120px] w-[120px] rounded-full">
                                                {/* delete button */}
                                                {getValues('personal_image') != null &&
                                                   personal_image_x && (
                                                      <div
                                                         onClick={() => {
                                                            setValue('personal_image', null, {
                                                               shouldValidate: true,
                                                            });
                                                            // setValue('personal_image_url', null, {
                                                            //    shouldValidate: true,
                                                            // });
                                                            localStorage.removeItem(
                                                               'personal_image_x'
                                                            );

                                                            const el = document.getElementById(
                                                               'personal_image'
                                                            ) as HTMLInputElement;

                                                            if (el) {
                                                               el.value = '';
                                                            }
                                                         }}
                                                         className="absolute top-1 flex h-6 w-6  cursor-pointer items-center justify-center rounded-full border border-black bg-white text-black ltr:right-1 rtl:left-1">
                                                         <XMarkIcon className="h-4 w-4" />
                                                      </div>
                                                   )}
                                                {getValues('personal_image') ? (
                                                   <img
                                                      src={personal_image_x || getImgPlaceHolder()}
                                                      className="h-[120px] w-[120px] rounded-full border border-accent object-cover"
                                                      alt="personal image"
                                                   />
                                                ) : (
                                                   <img
                                                      src={getImgPlaceHolder()}
                                                      className="h-[120px] w-[120px] rounded-full border border-accent object-cover"
                                                      alt="personal image placeholder"
                                                   />
                                                )}
                                             </div>
                                          }
                                          help={
                                             <React.Fragment>
                                                <span className="block text-center text-sm text-white">
                                                   <Translate id="web:only_jpg_png" />
                                                </span>
                                             </React.Fragment>
                                          }
                                          callBack={(id?: string | null, url?: string | null) => {
                                             setValue('personal_image', id || null, {
                                                shouldValidate: true,
                                             });
                                             // setValue('personal_image_url', url || null, {
                                             //    shouldValidate: true,
                                             // });
                                             try {
                                                // Save the base64 image in localStorage
                                                localStorage.setItem('personal_image_x', url || '');
                                             } catch {
                                                console.log(
                                                   'Failed to save the image in localStorage'
                                                );
                                             }
                                          }}
                                       />
                                    )}
                                    rules={{
                                       required: mandatoryFields?.includes('personal_image')
                                          ? translate({ id: 'validation:required' })
                                          : false,
                                    }}
                                 />
                              </div>
                           </div>

                           {/* terms */}
                           <div className="row">
                              <div className="col-12">
                                 <p className="text-white">
                                    {lang === 'ar'
                                       ? 'بإرسال هذا النموذج أوافق على شروط الفعالية وسياسة الخصوصية'
                                       : 'By submitting this form I agree to the event terms and privacy policy'}
                                 </p>
                              </div>
                           </div>

                           <div className="mt-10">
                              {/* {process.env.NEXT_PUBLIC_ENV === 'local' && (
                              <div className="row pb-4">
                                 <div className="sm:col-6 sm:offset-3">
                                    <ButtonBtn
                                       // disable={image === undefined ? true : false}

                                       callBack={() => autoFillSA()}
                                       id="upload-btn"
                                       // loading={loading}
                                       text={'auto fill SA'}
                                    />
                                 </div>
                              </div>
                           )} */}
                              {/* {process.env.NEXT_PUBLIC_ENV === 'local' && (
                              <div className="row pb-4">
                                 <div className="sm:col-6 sm:offset-3">
                                    <ButtonBtn
                                       // disable={image === undefined ? true : false}
                                       callBack={() => autoFillNotSA()}
                                       id="upload-btn"
                                       // loading={loading}
                                       text={'auto fill Not Sa'}
                                    />
                                 </div>
                              </div>
                           )} */}
                              {/*  email verification Done */}

                              <div className="row justify-end ">
                                 {/* <div className="col-6 sm:col-3 sm:offset-3">
                                 <BackBtn
                                    id="back-btn" //* for test cases
                                    // loading={loading}
                                    callBack={() => {
                                       onBackClick();
                                    }}
                                    className="w-full overflow-hidden rounded-md bg-secondary p-3"
                                    text={`${translate({ id: `web:back` })}`}
                                 />
                              </div> */}

                                 {/* <div className="mb-3 sm:mb-0 sm:col-8">
                                    {verificationDone && (
                                       <div className="border bg-secondary-50 py-[13px] px-2 text-xs text-secondary-700">
                                          <Translate id="web:verification_done_phone" />
                                       </div>
                                    )}
                                 </div> */}

                                 <div className="sm:col-4">
                                    <SubmitBtn
                                       id="submit-btn" //* for test cases
                                       loading={loading}
                                       className="w-full overflow-hidden rounded-md bg-primary p-3"
                                       text={`${translate({ id: `web:submit` })}`}
                                    />
                                 </div>
                              </div>
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
               <div className="mt-7 text-center">
                  <p
                     className={classNames(
                        'mt-5 text-lg font-bold ',
                        'text-white'
                        // 'from-primary via-primary to-primary bg-clip-text text-transparent ltr:bg-gradient-to-r rtl:bg-gradient-to-l'
                     )}>
                     <Translate id="homepage:contact_us" />
                  </p>

                  <div className="mt-1">
                     <p className="break-all font-en text-white/80">
                        registration@esportsworldcup.com
                     </p>
                  </div>
               </div>
            </React.Fragment>
         ) : (
            ''
         )}

         <Modal size="md" open={isOpen}>
            <Modal.Body>
               <div className="">
                  <div className="relative rounded-lg border bg-black p-4 shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)] sm:px-10 sm:py-6">
                     <div className="">
                        <div className="row">
                           <div className="col-12">
                              <VerifyEmailForm
                                 isEmailVerificationOn={withOtp}
                                 isPhoneVerificationOn={withSmsOtp}
                                 autoSendPhoneOtp={withSmsOtp}
                                 setIsOpen={setIsOpen}
                                 userEmail={getValues('email') || ''}
                                 userPhone={getValues('phone') || ''}
                                 formData={{
                                    email: getValues('email') || '',
                                    first_name: getValues('first_name'),
                                    last_name: getValues('last_name'),
                                    company: getValues('company'),
                                    job_title: getValues('job_title'),
                                    invitation_token: token || null,
                                    category: role || null,
                                 }}
                                 callBack={(tokens: {
                                    emailToken?: string;
                                    phoneToken?: string;
                                 }) => {
                                    if (withOtp && tokens.emailToken) {
                                       setValue('is_email_verified', 'yes');
                                       setValue('otp_token', tokens.emailToken);
                                    }
                                    if (withSmsOtp && tokens.phoneToken) {
                                       setValue('is_phone_verified', 'yes');
                                       setValue('sms_otp_token', tokens.phoneToken);
                                    }
                                    setVerificationDone(true);
                                    // setIsOpen(false);
                                    // Auto-submit form after verification
                                    const formValues = getValues();
                                    submitForm2(formValues);
                                 }}
                              />
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </Modal.Body>
         </Modal>
      </React.Fragment>
   );
};

export default PersonalInfoShort;
