import classNames from 'classnames';
import React, { useEffect, useState } from 'react';
import { Controller, useFormContext } from 'react-hook-form';
import SubmitBtn from '~/components/shared/buttons/submit-btn';
import CustomInput from '~/components/shared/forms/custom-input';
import { Translate, useTranslate } from '~/i18n';
import toast from 'react-hot-toast';
import { GuestType } from '~/interfaces/guest';
import validator from 'validator';
import CustomRadioInput from '~/components/shared/forms/custom-radio-input';
import isUniqueAttribute from '~/utils/unique-attribute';
import Modal from '~/components/shared/modals';
import VerifyEmailForm from '../../../verify-email-form';
import { XMarkIcon } from '@heroicons/react/20/solid';
import CustomFileInput2 from '~/components/shared/forms/custom-file-input-2/custom-file-input';
// import CheckboxInput from '~/components/shared/forms/checkbox-input';
import { useGoogleReCaptcha } from 'react-google-recaptcha-v3';
import Axios from '~/utils/axios';
import Cookies from 'js-cookie';
import PhoneInputV2 from '~/components/shared/forms/phone-input-new';
import parsePhoneNumberFromString from 'libphonenumber-js';
import TitleSelectNew from '~/components/shared/select/titles-select-new';
import StaticSelectNew from '~/components/shared/select/static-select-new';
import SectorTypeSelect from '~/data/sector-types-select';
import IndustryTypeSelect from '~/data/industry-types-select';
import KnowingAboutEventTypeSelect from '~/data/knowing-about-event-types-select';
import PositionSelectNew from '~/components/shared/select/position-select-new';
import CountrySelectNew from '~/components/shared/select/countries-select-new';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type PersonalInfoShortProps = {
   onNextClick: () => any;
   onUpdateClick: () => any;
   onBackClick: () => any;
   setStep?: (val: string) => any;
   step?: string | undefined;
   nextStep?: string;
   // countries: CountryType[];
   guestEmail?: string | null;
   guestFirstName?: string | null;
   guestLastName?: string | null;
   guestCompany?: string | null;
   guestPosition?: string | null;
   prefilldata?: string | null;
   lock_data?: string | null;

   role?: string;
   optionalFields?: string[];
   mandatoryFields?: string[];
   withOtp: boolean;
   withSmsOtp: boolean;
   token?: string | null;
   withAlternativeEmail: boolean;
};

// type Item = {
//    label: string;
//    value: string;
// };

const PersonalInfoShort = ({
   onNextClick,
   // onBackClick,
   // onUpdateClick,
   step,
   // nextStep,
   // countries,
   guestEmail,
   guestFirstName,
   guestLastName,
   guestCompany,
   guestPosition,
   prefilldata,
   lock_data,
   role,
   // optionalFields,
   mandatoryFields,
   withOtp,
   withSmsOtp,
   token,
}: // withAlternativeEmail,
// role,
PersonalInfoShortProps) => {
   const { translate } = useTranslate();
   const [loading, setLoading] = useState(false);
   // setLockEmail
   const [verificationDone, setVerificationDone] = useState(false);
   // console.log(guestEmail, 'guestEmail');
   // console.log(guestFirstName, 'guestFirstName');
   // console.log(guestLastName, 'guestLastName');
   const [isOpen, setIsOpen] = useState(false);
   const [isPrivacyModalOpen, setIsPrivacyModalOpen] = useState(false);
   const { lang } = useTranslate();

   const {
      register,
      handleSubmit,
      getValues,
      control,
      setValue,
      watch,
      // trigger,

      formState: { errors },
   } = useFormContext<GuestType>();

   // Sync hasPlusOne with form value
   // const hasPlusOneValue = watch('has_plus_one');
   // const primaryEmail = watch('email');
   // useEffect(() => {
   //    setHasPlusOne(hasPlusOneValue === 'yes' || hasPlusOneValue === true);
   // }, [hasPlusOneValue]);

   // // Re-validate plus_one_email when primary email changes
   // useEffect(() => {
   //    if (hasPlusOne && primaryEmail) {
   //       trigger('plus_one_email');
   //    }
   // }, [primaryEmail, hasPlusOne, trigger]);

   const submitForm = async (values: GuestType) => {
      try {
         if (getValues('is_email_verified') === 'yes' || getValues('is_phone_verified') === 'yes') {
            submitForm2(values);
         } else {
            if (!withOtp && !withSmsOtp) {
               submitForm2(values);
            } else {
               setIsOpen(true);
            }
         }
      } catch (error: any) {
         console.log(error, 'error');
      }
      // setLoading(false);
   };
   // const submitForm2 = async () => {
   //    // setLoading(true);
   //    try {
   //       const values = getValues();

   //       const updatedUserObj = {
   //          ...values,
   //          step: nextStep,
   //       };
   //       // cookie.set('user_data', JSON.stringify(updatedUserObj));
   //       cookie.set('user_data', JSON.stringify(updatedUserObj), {
   //          secure: true, // Ensures the cookie is secure in production
   //          sameSite: 'Strict', // Prevents cross-site request forgery
   //       });
   //       toast.success(translate({ id: 'res:info_saved' }));
   //       // onNextClick();
   //    } catch (error: any) {
   //       console.log(error, 'error');
   //    }
   //    // setLoading(false);
   // };
   const { executeRecaptcha } = useGoogleReCaptcha();

   const submitForm2 = async (values: GuestType) => {
      setLoading(true);
      if (loading) {
         return;
      }
      setLoading(true);

      try {
         const recaptcha = await executeRecaptcha?.();

         const data = {
            ...values,
            code: token || '', //todo: check
            category: role,
            email: values?.email?.toLowerCase(),
            recaptcha,
         };

         // console.log(data, 'data');

         const response = await Axios.post(`guests?lang=${lang}`, data);
         Cookies.set('reg_num', response.data.data);

         // to success page
         onNextClick();
      } catch (error: any) {
         setLoading(false);
         if (error.response?.status === 404) {
            toast.error(error.response?.data?.data);
         } else if (error?.response?.status === 403) {
            toast.error(translate({ id: 'res:recaptcha_failed' }), {
               duration: 4000,
            });
         } else {
            toast.error(translate({ id: 'res:500' }));
         }
         console.log(error, 'error');
      }
   };

   const personal_image_x =
      (typeof window !== 'undefined' && localStorage.getItem('personal_image_x')) || '';

   // Prefill fields when prefilldata is "yes"
   useEffect(() => {
      if (prefilldata === 'yes') {
         if (guestFirstName) {
            setValue('first_name', guestFirstName, { shouldValidate: false });
         }
         if (guestLastName) {
            setValue('last_name', guestLastName, { shouldValidate: false });
         }
         if (guestEmail) {
            setValue('email', guestEmail, { shouldValidate: false });
         }
         if (guestCompany) {
            setValue('company', guestCompany, { shouldValidate: false });
         }
         if (guestPosition) {
            setValue('job_title', guestPosition, { shouldValidate: false });
         }
      }
   }, [
      prefilldata,
      guestFirstName,
      guestLastName,
      guestEmail,
      guestCompany,
      guestPosition,
      setValue,
   ]);

   // Determine if fields should be locked
   const isLocked = lock_data === 'yes';

   const getImgPlaceHolder = () => {
      switch (getValues('gender')) {
         case 'male':
            return '/images/man_dark.png';
         case 'female':
            return '/images/woman_dark.png';
         default:
            return '/images/man_dark.png';
      }
   };

   return (
      <React.Fragment>
         {step === 'personal-info-1' ? (
            <React.Fragment>
               <div className="rounded-xl border  shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)]">
                  <div className="p-6 sm:p-12">
                     <h2
                        className={classNames(
                           'text-xl font-bold capitalize text-white md:mb-4 md:text-2xl'
                        )}>
                        <Translate id="web:personal_information" />
                     </h2>

                     <div className="pt-5">
                        <form
                           noValidate
                           onSubmit={handleSubmit(submitForm)}
                           className="relative"
                           autoComplete="off">
                           {/* gender */}
                           <CustomRadioInput
                              label={translate({ id: 'web:gender' })}
                              isRequired={mandatoryFields?.includes('gender') ?? false}
                              isInline
                              options={[
                                 { value: 'male', label: translate({ id: 'web:male' }) },
                                 { value: 'female', label: translate({ id: 'web:female' }) },
                              ]}
                              id="gender"
                              error={errors.gender?.message}
                              {...register('gender', {
                                 required: mandatoryFields?.includes('gender')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                              })}
                           />
                           {/* title_id */}
                           <Controller
                              name="title_id"
                              control={control}
                              render={() => (
                                 <TitleSelectNew
                                    category={role}
                                    gender={watch('gender')}
                                    isRequired={mandatoryFields?.includes('title_id') ?? false}
                                    selected_id={getValues()['title_id']} // on edit
                                    label={translate({ id: 'web:title' })}
                                    errors={errors.title_id?.message}
                                    callBack={(item: { value: string } | null) => {
                                       setValue('title_id', item?.value || null, {
                                          shouldValidate: true,
                                       });
                                    }}
                                 />
                              )}
                              rules={{
                                 required: mandatoryFields?.includes('title_id')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                              }}
                           />

                           {/* first_name */}
                           <CustomInput
                              label={translate({ id: 'web:first_name' })}
                              type="text"
                              isRequired={mandatoryFields?.includes('first_name') ?? false}
                              isInline
                              autoComplete="off"
                              placeHolder={translate({ id: 'web:first_name' })}
                              id="first_name"
                              disabled={isLocked}
                              error={errors.first_name?.message}
                              {...register('first_name', {
                                 required: mandatoryFields?.includes('first_name')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 pattern: {
                                    value: /^[a-zA-Z0-9 -]+$/i,
                                    message: translate({
                                       id: 'validation:english_letters',
                                    }),
                                 },
                              })}
                           />

                           {/* last_name */}
                           <CustomInput
                              label={translate({ id: 'web:last_name' })}
                              type="text"
                              autoComplete="off"
                              placeHolder={translate({ id: 'web:last_name' })}
                              id="last_name"
                              isRequired={mandatoryFields?.includes('last_name') ?? false}
                              isInline
                              disabled={isLocked}
                              error={errors.last_name?.message}
                              {...register('last_name', {
                                 required: mandatoryFields?.includes('last_name')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 pattern: {
                                    value: /^[a-zA-Z0-9 -]+$/i,
                                    message: translate({
                                       id: 'validation:english_letters',
                                    }),
                                 },
                              })}
                           />

                           {/* sector */}
                           <Controller
                              name="sector"
                              control={control}
                              render={() => (
                                 <StaticSelectNew
                                    options={SectorTypeSelect}
                                    isRequired={mandatoryFields?.includes('sector') ?? false}
                                    selected_id={watch('sector')}
                                    label={translate({ id: 'web:sector' })}
                                    errors={errors.sector?.message}
                                    placeholderTranslationId="web:select_sector"
                                    dropdownRounded="xl"
                                    callBack={(item: { value: string } | null) => {
                                       setValue('sector', item?.value || null, {
                                          shouldValidate: true,
                                       });
                                    }}
                                 />
                              )}
                              rules={{
                                 required: mandatoryFields?.includes('sector')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                              }}
                           />

                           {/* industry */}
                           <Controller
                              name="industry"
                              control={control}
                              render={() => (
                                 <StaticSelectNew
                                    options={IndustryTypeSelect}
                                    isRequired={mandatoryFields?.includes('industry') ?? false}
                                    selected_id={watch('industry')}
                                    label={translate({ id: 'web:industry' })}
                                    errors={errors.industry?.message}
                                    placeholderTranslationId="web:select_industry"
                                    dropdownRounded="none"
                                    callBack={(item: { value: string } | null) => {
                                       setValue('industry', item?.value || null, {
                                          shouldValidate: true,
                                       });
                                    }}
                                 />
                              )}
                              rules={{
                                 required: mandatoryFields?.includes('industry')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                              }}
                           />

                           {/* company */}
                           <CustomInput
                              label={translate({ id: 'web:company' })}
                              type="text"
                              autoComplete="off"
                              // disabled={!!user && role !== 'xrole-name'}
                              placeHolder={translate({ id: 'web:company' })}
                              id="company"
                              isRequired={mandatoryFields?.includes('company') ?? false}
                              isInline
                              disabled={isLocked}
                              error={errors.company?.message}
                              {...register('company', {
                                 required: mandatoryFields?.includes('company')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 maxLength: {
                                    value: 100,
                                    message: translate({
                                       id: 'validation:you_reached_the_text_limit',
                                    }),
                                 },
                                 pattern: {
                                    value: /^(?!.*[\u0600-\u06FF]).+$/,
                                    message: translate({
                                       id: 'validation:english_letters',
                                    }),
                                 },
                              })}
                           />

                           {/* job_title */}
                           <CustomInput
                              label={translate({ id: 'web:job_title' })}
                              type="text"
                              autoComplete="off"
                              // disabled={!!user && role !== 'xrole-name'}
                              placeHolder={translate({ id: 'web:job_title' })}
                              id="job_title"
                              isRequired={mandatoryFields?.includes('job_title') ?? false}
                              isInline
                              error={errors.job_title?.message}
                              {...register('job_title', {
                                 required: mandatoryFields?.includes('job_title')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 maxLength: {
                                    value: 100,
                                    message: translate({
                                       id: 'validation:you_reached_the_text_limit',
                                    }),
                                 },
                                 pattern: {
                                    value: /^(?!.*[\u0600-\u06FF]).+$/,
                                    message: translate({
                                       id: 'validation:english_letters',
                                    }),
                                 },
                              })}
                           />

                           {/* position_id */}
                           <Controller
                              name="position_id"
                              control={control}
                              render={() => (
                                 <PositionSelectNew
                                    category={role}
                                    isRequired={mandatoryFields?.includes('position_id') ?? false}
                                    selected_id={getValues()['position_id']}
                                    label={translate({ id: 'web:position' })}
                                    errors={errors.position_id?.message}
                                    callBack={(item: { value: string } | null) => {
                                       setValue('position_id', item?.value || null, {
                                          shouldValidate: true,
                                       });
                                    }}
                                 />
                              )}
                              rules={{
                                 required: mandatoryFields?.includes('position_id')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                              }}
                           />

                           {/* email */}
                           <CustomInput
                              label={translate({ id: 'web:email' })}
                              type="email"
                              // disabled={!!user && role == 'xrole-name'}
                              isRequired={mandatoryFields?.includes('email') ?? false}
                              isInline
                              placeHolder={translate({ id: 'web:email' })}
                              id="email"
                              disabled={isLocked || verificationDone}
                              error={errors.email?.message}
                              {...register('email', {
                                 required: mandatoryFields?.includes('email')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 // value: guestEmail,
                                 validate: {
                                    trim: (value: any) =>
                                       value == value.trim() || 'يرجى حذف المسافات',
                                    isEmail: value => {
                                       // If field is not mandatory and empty, skip validation
                                       if (!mandatoryFields?.includes('email') && !value) {
                                          return true;
                                       }
                                       // If mandatory or has value, validate email format
                                       return (
                                          validator.isEmail(value || '') ||
                                          translate({ id: 'validation:not_email' })
                                       );
                                    },
                                    isUnique: async value => {
                                       // If field is not mandatory and empty, skip uniqueness check
                                       if (!mandatoryFields?.includes('email') && !value) {
                                          return true;
                                       }
                                       const { isUnique, status } = await isUniqueAttribute(
                                          'guests',
                                          'email',
                                          value,
                                          'create',
                                          getValues('id')
                                       );
                                       if (!isUnique && status === 422) {
                                          return translate({ id: 'validation:unique_email' });
                                       } else if (!isUnique) {
                                          return translate({
                                             id: 'validation:unique_email_failed',
                                          });
                                       } else {
                                          return true;
                                       }
                                    },
                                 },
                              })}
                           />

                           {/* phone (single field with flags + masking; stores E.164 in `phone`) */}
                           <Controller
                              name="phone"
                              control={control}
                              rules={{
                                 required: mandatoryFields?.includes('phone')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 validate: (v?: string | null) => {
                                    if (!mandatoryFields?.includes('phone') && !v) {
                                       return true; // Not required, so empty is valid
                                    }
                                    const s = (v ?? '').replace(/\s+/g, '');
                                    const pn = parsePhoneNumberFromString(s);
                                    return pn?.isValid()
                                       ? true
                                       : translate({ id: 'validation:invalid_phone' });
                                 },
                              }}
                              render={({ field }) => (
                                 <PhoneInputV2
                                    lang={lang}
                                    label={translate({ id: 'web:phone' })}
                                    isInline
                                    isRequired={mandatoryFields?.includes('phone') ?? false}
                                    defaultCountry="sa"
                                    // onlyCountries={ONLY_COUNTRIES}
                                    value={field.value ?? ''}
                                    onChange={field.onChange}
                                    // show error only after touch or submit
                                    error={errors.phone?.message}
                                 />
                              )}
                           />

                           {/* country_of_residence */}
                           <Controller
                              name="country_of_residence"
                              control={control}
                              render={() => (
                                 <CountrySelectNew
                                    isRequired={
                                       mandatoryFields?.includes('country_of_residence') ?? false
                                    }
                                    selected_id={getValues()['country_of_residence']}
                                    label={translate({ id: 'web:country_of_residence' })}
                                    errors={errors.country_of_residence?.message}
                                    callBack={(item: { value: string } | null) => {
                                       setValue('country_of_residence', item?.value || null, {
                                          shouldValidate: true,
                                       });
                                    }}
                                 />
                              )}
                              rules={{
                                 required: mandatoryFields?.includes('country_of_residence')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                              }}
                           />

                           {/* nationality */}
                           <Controller
                              name="nationality"
                              control={control}
                              render={() => (
                                 <CountrySelectNew
                                    isRequired={mandatoryFields?.includes('nationality') ?? false}
                                    selected_id={getValues()['nationality']}
                                    label={translate({ id: 'web:nationality' })}
                                    errors={errors.nationality?.message}
                                    callBack={(item: { value: string; label: string } | null) => {
                                       setValue('nationality', item?.value || null, {
                                          shouldValidate: true,
                                       });

                                       const result =
                                          item?.label === 'Saudi Arabia' ||
                                          item?.label === 'المملكة العربية السعودية'
                                             ? true
                                             : false;
                                       if (result) {
                                          setValue('is_saudi', 'yes', {
                                             shouldValidate: false,
                                          });
                                          setValue('document_type', 'saudi_id', {
                                             shouldValidate: false,
                                          });
                                          setValue('religion', 'muslim', {
                                             shouldValidate: false,
                                          });
                                          setValue('residency_status', null, {
                                             shouldValidate: false,
                                          });
                                          setValue('valid_visa', null, {
                                             shouldValidate: false,
                                          });
                                          setValue('document_number', null, {
                                             shouldValidate: false,
                                          });
                                       } else {
                                          setValue('is_saudi', 'no', {
                                             shouldValidate: false,
                                          });
                                          setValue('document_type', null, {
                                             shouldValidate: false,
                                          });
                                          setValue('religion', null, {
                                             shouldValidate: false,
                                          });
                                          setValue('residency_status', null, {
                                             shouldValidate: false,
                                          });
                                          setValue('valid_visa', null, {
                                             shouldValidate: false,
                                          });
                                          setValue('document_number', null, {
                                             shouldValidate: false,
                                          });
                                       }
                                    }}
                                 />
                              )}
                              rules={{
                                 required: mandatoryFields?.includes('nationality')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                              }}
                           />
                           {/* knowing_about_event */}
                           <Controller
                              name="knowing_about_event"
                              control={control}
                              render={() => (
                                 <StaticSelectNew
                                    options={KnowingAboutEventTypeSelect}
                                    isRequired={
                                       mandatoryFields?.includes('knowing_about_event') ?? false
                                    }
                                    selected_id={watch('knowing_about_event')}
                                    label={translate({ id: 'web:knowing_about_event' })}
                                    errors={errors.knowing_about_event?.message}
                                    placeholderTranslationId="web:knowing_about_event"
                                    dropdownRounded="none"
                                    callBack={(item: { value: string } | null) => {
                                       setValue('knowing_about_event', item?.value || null, {
                                          shouldValidate: true,
                                       });
                                    }}
                                 />
                              )}
                              rules={{
                                 required: mandatoryFields?.includes('knowing_about_event')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                              }}
                           />

                           <div>
                              <hr className="my-7 border-white/50" />
                              {/* <p className="text-accent">
                                             <Translate id="web:upload_document_p" />
                                          </p> */}
                              <div className="mt-4">
                                 {/* personal_image */}
                                 <Controller
                                    name="personal_image"
                                    control={control}
                                    render={({ field: { ref } }) => (
                                       <CustomFileInput2
                                          label={translate({ id: 'web:personal_image' })}
                                          id="personal_image"
                                          isRequired={
                                             mandatoryFields?.includes('personal_image') ?? false
                                          }
                                          error={
                                             errors.personal_image?.message ||
                                             errors.personal_image?.message
                                          }
                                          ref={ref}
                                          // inputName="personal_image"
                                          withCrop
                                          note={
                                             <React.Fragment>
                                                <span className="block text-center text-sm text-white">
                                                   <Translate id="web:upload_document_p" />
                                                </span>
                                             </React.Fragment>
                                          }
                                          placeholderImg={
                                             <div className="relative mx-auto h-[120px] w-[120px] rounded-full">
                                                {/* delete button */}
                                                {getValues('personal_image') != null &&
                                                   personal_image_x && (
                                                      <div
                                                         onClick={() => {
                                                            setValue('personal_image', null, {
                                                               shouldValidate: true,
                                                            });
                                                            // setValue('personal_image_url', null, {
                                                            //    shouldValidate: true,
                                                            // });
                                                            localStorage.removeItem(
                                                               'personal_image_x'
                                                            );

                                                            const el = document.getElementById(
                                                               'personal_image'
                                                            ) as HTMLInputElement;

                                                            if (el) {
                                                               el.value = '';
                                                            }
                                                         }}
                                                         className="absolute top-1 flex h-6 w-6  cursor-pointer items-center justify-center rounded-full border border-black bg-white text-black ltr:right-1 rtl:left-1">
                                                         <XMarkIcon className="h-4 w-4" />
                                                      </div>
                                                   )}
                                                {getValues('personal_image') ? (
                                                   <img
                                                      src={personal_image_x || getImgPlaceHolder()}
                                                      className="h-[120px] w-[120px] rounded-full border border-accent object-cover"
                                                      alt="personal image"
                                                   />
                                                ) : (
                                                   <img
                                                      src={getImgPlaceHolder()}
                                                      className="h-[120px] w-[120px] rounded-full border border-accent object-cover"
                                                      alt="personal image placeholder"
                                                   />
                                                )}
                                             </div>
                                          }
                                          help={
                                             <React.Fragment>
                                                <span className="block text-center text-sm text-white">
                                                   <Translate id="web:only_jpg_png" />
                                                </span>
                                             </React.Fragment>
                                          }
                                          callBack={(id?: string | null, url?: string | null) => {
                                             setValue('personal_image', id || null, {
                                                shouldValidate: true,
                                             });
                                             // setValue('personal_image_url', url || null, {
                                             //    shouldValidate: true,
                                             // });
                                             try {
                                                // Save the base64 image in localStorage
                                                localStorage.setItem('personal_image_x', url || '');
                                             } catch {
                                                console.log(
                                                   'Failed to save the image in localStorage'
                                                );
                                             }
                                          }}
                                       />
                                    )}
                                    rules={{
                                       required: mandatoryFields?.includes('personal_image')
                                          ? translate({ id: 'validation:required' })
                                          : false,
                                    }}
                                 />
                              </div>
                           </div>

                           {/* terms */}
                           <div className="row">
                              <div className="col-12">
                                 <p className="text-white">
                                    {lang === 'ar' ? (
                                       <>
                                          بإرسال هذا النموذج أوافق على{' '}
                                          <button
                                             type="button"
                                             onClick={() => setIsPrivacyModalOpen(true)}
                                             className="underline transition-colors hover:text-primary">
                                             شروط الفعالية وسياسة الخصوصية
                                          </button>
                                       </>
                                    ) : (
                                       <>
                                          By submitting this form I agree to the event{' '}
                                          <button
                                             type="button"
                                             onClick={() => setIsPrivacyModalOpen(true)}
                                             className="underline transition-colors hover:text-primary">
                                             terms and privacy policy
                                          </button>
                                       </>
                                    )}
                                 </p>
                              </div>
                           </div>

                           <div className="mt-10">
                              {/* {process.env.NEXT_PUBLIC_ENV === 'local' && (
                              <div className="row pb-4">
                                 <div className="sm:col-6 sm:offset-3">
                                    <ButtonBtn
                                       // disable={image === undefined ? true : false}

                                       callBack={() => autoFillSA()}
                                       id="upload-btn"
                                       // loading={loading}
                                       text={'auto fill SA'}
                                    />
                                 </div>
                              </div>
                           )} */}
                              {/* {process.env.NEXT_PUBLIC_ENV === 'local' && (
                              <div className="row pb-4">
                                 <div className="sm:col-6 sm:offset-3">
                                    <ButtonBtn
                                       // disable={image === undefined ? true : false}
                                       callBack={() => autoFillNotSA()}
                                       id="upload-btn"
                                       // loading={loading}
                                       text={'auto fill Not Sa'}
                                    />
                                 </div>
                              </div>
                           )} */}
                              {/*  email verification Done */}

                              <div className="row justify-end ">
                                 {/* <div className="col-6 sm:col-3 sm:offset-3">
                                 <BackBtn
                                    id="back-btn" //* for test cases
                                    // loading={loading}
                                    callBack={() => {
                                       onBackClick();
                                    }}
                                    className="w-full overflow-hidden rounded-md bg-secondary p-3"
                                    text={`${translate({ id: `web:back` })}`}
                                 />
                              </div> */}

                                 {/* <div className="mb-3 sm:mb-0 sm:col-8">
                                    {verificationDone && (
                                       <div className="border bg-secondary-50 py-[13px] px-2 text-xs text-secondary-700">
                                          <Translate id="web:verification_done_phone" />
                                       </div>
                                    )}
                                 </div> */}

                                 <div className="sm:col-4">
                                    <SubmitBtn
                                       id="submit-btn" //* for test cases
                                       loading={loading}
                                       className="w-full overflow-hidden rounded-md bg-primary p-3"
                                       text={`${translate({ id: `web:submit` })}`}
                                    />
                                 </div>
                              </div>
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
               <div className="mt-7 text-center">
                  <p
                     className={classNames(
                        'mt-5 text-lg font-bold ',
                        'text-white'
                        // 'from-primary via-primary to-primary bg-clip-text text-transparent ltr:bg-gradient-to-r rtl:bg-gradient-to-l'
                     )}>
                     <Translate id="homepage:contact_us" />
                  </p>

                  <div className="mt-1">
                     <p className="break-all font-en text-white/80">
                        registration@esportsworldcup.com
                     </p>
                  </div>
               </div>
            </React.Fragment>
         ) : (
            ''
         )}

         <Modal size="md" open={isOpen}>
            <Modal.Body>
               <div className="">
                  <div className="relative rounded-lg border bg-black p-4 shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)] sm:px-10 sm:py-6">
                     <div className="">
                        <div className="row">
                           <div className="col-12">
                              <VerifyEmailForm
                                 isEmailVerificationOn={withOtp}
                                 isPhoneVerificationOn={withSmsOtp}
                                 autoSendPhoneOtp={withSmsOtp}
                                 setIsOpen={setIsOpen}
                                 userEmail={getValues('email') || ''}
                                 userPhone={getValues('phone') || ''}
                                 formData={{
                                    email: getValues('email') || '',
                                    first_name: getValues('first_name'),
                                    last_name: getValues('last_name'),
                                    company: getValues('company'),
                                    job_title: getValues('job_title'),
                                    invitation_token: token || null,
                                    category: role || null,
                                 }}
                                 callBack={(tokens: {
                                    emailToken?: string;
                                    phoneToken?: string;
                                 }) => {
                                    if (withOtp && tokens.emailToken) {
                                       setValue('is_email_verified', 'yes');
                                       setValue('otp_token', tokens.emailToken);
                                    }
                                    if (withSmsOtp && tokens.phoneToken) {
                                       setValue('is_phone_verified', 'yes');
                                       setValue('sms_otp_token', tokens.phoneToken);
                                    }
                                    setVerificationDone(true);
                                    // setIsOpen(false);
                                    // Auto-submit form after verification
                                    const formValues = getValues();
                                    submitForm2(formValues);
                                 }}
                              />
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </Modal.Body>
         </Modal>

         {/* Privacy Policy Modal */}
         <Modal
            size={1024}
            open={isPrivacyModalOpen}
            onClickOutside={() => setIsPrivacyModalOpen(false)}>
            <Modal.Body>
               <div className="relative rounded-xl border border-white/20 bg-gradient-to-b from-black via-black to-gray-900 shadow-2xl">
                  <style jsx>{`
                     .privacy-scrollbar::-webkit-scrollbar {
                        width: 8px;
                     }
                     .privacy-scrollbar::-webkit-scrollbar-track {
                        background: rgba(255, 255, 255, 0.1);
                        border-radius: 4px;
                     }
                     .privacy-scrollbar::-webkit-scrollbar-thumb {
                        background: rgba(255, 255, 255, 0.3);
                        border-radius: 4px;
                     }
                     .privacy-scrollbar::-webkit-scrollbar-thumb:hover {
                        background: rgba(255, 255, 255, 0.5);
                     }
                  `}</style>
                  <button
                     type="button"
                     onClick={() => setIsPrivacyModalOpen(false)}
                     className="absolute top-6 z-20 flex h-10 w-10 items-center justify-center rounded-full bg-white/10 text-white transition-all hover:scale-110 hover:bg-white/20 hover:text-primary ltr:right-6 rtl:left-6">
                     <XMarkIcon className="h-6 w-6" />
                  </button>
                  <div className="privacy-scrollbar max-h-[85vh] overflow-y-auto">
                     <div className="p-6 ltr:pr-14 rtl:pl-14 sm:p-8 md:p-12">
                        {lang === 'ar' ? (
                           <div className="space-y-6 text-white" dir="rtl">
                              <div className="border-b border-white/20 pb-3">
                                 <h2 className="from-primary to-accent bg-clip-text text-2xl font-bold text-transparent ltr:bg-gradient-to-r rtl:bg-gradient-to-l md:text-3xl">
                                    سياسة الخصوصية
                                 </h2>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">
                                    1. المعلومات التي نقوم بجمعها
                                 </h3>
                                 <p className="mb-3 text-sm leading-relaxed text-white/90">
                                    عند تعبئة نموذج التسجيل، قد نقوم بجمع المعلومات الشخصية التالية:
                                 </p>
                                 <div className="space-y-3">
                                    <div>
                                       <p className="mb-2 text-base font-semibold text-primary">
                                          البيانات الشخصية
                                       </p>
                                       <ul className="mr-4 list-inside list-disc space-y-1.5 text-sm text-white/80">
                                          <li>الجنس</li>
                                          <li>اللقب</li>
                                          <li>الاسم الأول واسم العائلة</li>
                                       </ul>
                                    </div>
                                    <div>
                                       <p className="mb-2 text-lg font-semibold text-primary">
                                          البيانات المهنية
                                       </p>
                                       <ul className="mr-4 list-inside list-disc space-y-2 text-white/80">
                                          <li>القطاع</li>
                                          <li>المجال</li>
                                          <li>اسم الجهة أو الشركة</li>
                                          <li>المسمى الوظيفي</li>
                                          <li>المستوى الوظيفي</li>
                                       </ul>
                                    </div>
                                    <div>
                                       <p className="mb-2 text-lg font-semibold text-primary">
                                          معلومات التواصل
                                       </p>
                                       <ul className="mr-4 list-inside list-disc space-y-2 text-white/80">
                                          <li>البريد الإلكتروني</li>
                                          <li>رقم الجوال</li>
                                          <li>دولة الإقامة</li>
                                          <li>الجنسية</li>
                                       </ul>
                                    </div>
                                    <div>
                                       <p className="mb-2 text-lg font-semibold text-primary">
                                          بيانات التفاعل
                                       </p>
                                       <ul className="mr-4 list-inside list-disc space-y-2 text-white/80">
                                          <li>
                                             كيفية تعرفك على مؤتمر كأس العالم للرياضات الإلكترونية
                                          </li>
                                       </ul>
                                    </div>
                                    <div>
                                       <p className="mb-2 text-lg font-semibold text-primary">
                                          التحقق من الهوية والصلاحيات
                                       </p>
                                       <ul className="mr-4 list-inside list-disc space-y-2 text-white/80">
                                          <li>
                                             صورة شخصية تظهر الوجه بشكل كامل من الأمام، يتم تقديمها
                                             لأغراض الاعتماد وتنظيم الدخول
                                          </li>
                                          <li>
                                             سيتم إضافة الصورة الشخصية لاحقا عبر تطبيق المؤتمر.
                                          </li>
                                       </ul>
                                    </div>
                                    <div>
                                       <p className="mb-2 text-lg font-semibold text-primary">
                                          البيانات التقنية
                                       </p>
                                       <ul className="mr-4 list-inside list-disc space-y-2 text-white/80">
                                          <li>عنوان بروتوكول الإنترنت IP</li>
                                          <li>معلومات الجهاز</li>
                                          <li>
                                             ملفات تعريف الارتباط وبيانات التصفح المتعلقة باستخدامك
                                             لمنصة التسجيل
                                          </li>
                                       </ul>
                                    </div>
                                    <p className="mt-3 rounded-lg border-r-4 border-primary bg-white/5 p-3 text-sm leading-relaxed text-white/90">
                                       يتم جمع جميع المعلومات التي تقدمها من خلال النموذج بشكل طوعي،
                                       باستثناء البيانات المطلوبة لأغراض الدخول إلى الفعالية أو
                                       الاعتماد أو المتطلبات الأمنية.
                                    </p>
                                 </div>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">
                                    2. كيفية استخدام معلوماتك
                                 </h3>
                                 <p className="mb-3 text-sm leading-relaxed text-white/90">
                                    يتم استخدام بياناتك الشخصية للأغراض التالية:
                                 </p>
                                 <ul className="mr-4 list-inside list-disc space-y-2 text-sm text-white/80">
                                    <li>
                                       معالجة وإدارة تسجيلك في مؤتمر كأس العالم للرياضات الإلكترونية
                                    </li>
                                    <li>
                                       التحقق من هويتك وإصدار بطاقات الاعتماد والشارات الخاصة
                                       بالفعالية
                                    </li>
                                    <li>إدارة صلاحيات الدخول وإجراءات الأمن</li>
                                    <li>
                                       التواصل معك بشأن التحديثات المهمة المتعلقة بالبرنامج والتنظيم
                                       والدخول
                                    </li>
                                    <li>
                                       فهم تركيبة الحضور حسب القطاعات والمجالات والأدوار لأغراض
                                       التخطيط وإعداد التقارير
                                    </li>
                                    <li>تحسين تجربة التسجيل وأداء المنصة</li>
                                    <li>الرد على استفساراتك وطلبات الدعم</li>
                                    <li>
                                       الالتزام بالأنظمة واللوائح والمتطلبات الأمنية المعمول بها في
                                       المملكة العربية السعودية
                                    </li>
                                 </ul>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">
                                    3. تخزين البيانات وحمايتها
                                 </h3>
                                 <p className="mb-3 text-sm leading-relaxed text-white/90">
                                    نطبق الإجراءات الإدارية والتقنية والتنظيمية المناسبة لحماية
                                    بياناتك الشخصية من الوصول غير المصرح به أو الفقدان أو سوء
                                    الاستخدام أو الإفصاح.
                                 </p>
                                 <p className="mb-3 text-sm leading-relaxed text-white/90">
                                    وبما يتوافق مع أنظمة حماية البيانات في المملكة العربية السعودية:
                                 </p>
                                 <ul className="mr-4 list-inside list-disc space-y-2 text-sm text-white/80">
                                    <li>قد يتم تخزين بياناتك على خوادم آمنة داخل المملكة</li>
                                    <li>يقتصر الوصول إلى بياناتك على الموظفين المخولين فقط</li>
                                    <li>
                                       يتم الاحتفاظ ببياناتك الشخصية للمدة اللازمة لدعم عمليات
                                       الفعالية وإعداد التقارير والامتثال للأنظمة
                                    </li>
                                    <li>
                                       بعد انتهاء مؤتمر كأس العالم للرياضات الإلكترونية والأنشطة
                                       المرتبطة بها، يتم حذف بياناتك أو إخفاء هويتها بشكل آمن
                                    </li>
                                 </ul>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">
                                    4. استخدام ملفات تعريف الارتباط
                                 </h3>
                                 <p className="mb-2 text-sm leading-relaxed text-white/90">
                                    تستخدم منصة التسجيل ملفات تعريف الارتباط لتحسين الأداء وتعزيز
                                    تجربة المستخدم. تساعدنا هذه الملفات على فهم طريقة تفاعل
                                    المستخدمين مع المنصة ودعم كفاءة النظام.
                                 </p>
                                 <p className="text-sm leading-relaxed text-white/90">
                                    يمكنك تعطيل ملفات تعريف الارتباط في أي وقت من خلال إعدادات
                                    المتصفح، مع العلم أن ذلك قد يؤثر على بعض خصائص منصة التسجيل.
                                 </p>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">
                                    5. الأطراف الثالثة ومشاركة البيانات
                                 </h3>
                                 <p className="mb-3 text-sm leading-relaxed text-white/90">
                                    قد تتم مشاركة بياناتك الشخصية فقط مع الجهات الموثوقة المشاركة في
                                    تنفيذ مؤتمر كأس العالم للرياضات الإلكترونية، وتشمل:
                                 </p>
                                 <ul className="mr-4 list-inside list-disc space-y-2 text-sm text-white/80">
                                    <li>فريق تنظيم الفعالية الرسمي</li>
                                    <li>شركاء الاعتماد وإنتاج البطاقات</li>
                                    <li>فرق الأمن وتنظيم الدخول في المواقع</li>
                                    <li>مزودي الخدمات التقنية الداعمين لنظام التسجيل</li>
                                 </ul>
                                 <p className="mt-3 text-sm leading-relaxed text-white/90">
                                    وتلتزم جميع هذه الجهات تعاقديا بحماية بياناتك واستخدامها حصرا
                                    للأغراض المرتبطة بتنفيذ الفعالية.
                                 </p>
                                 <p className="mt-2 rounded-lg border-r-4 border-primary bg-white/5 p-3 text-sm leading-relaxed text-white/90">
                                    نؤكد أننا لا نقوم ببيع أو تأجير أو تبادل بياناتك الشخصية مع أي
                                    طرف ثالث لأغراض تسويقية أو تجارية.
                                 </p>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">
                                    6. نطاق هذه السياسة
                                 </h3>
                                 <p className="text-sm leading-relaxed text-white/90">
                                    تنطبق سياسة الخصوصية هذه فقط على المعلومات الشخصية التي يتم
                                    جمعها من خلال منصة التسجيل الإلكترونية الرسمية لمؤتمر مبادرة
                                    القدرات البشرية، ولا تشمل المعلومات التي يتم جمعها عبر القنوات
                                    غير الإلكترونية إلا إذا تم النص على ذلك صراحة.
                                 </p>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">7. موافقتك</h3>
                                 <p className="text-sm leading-relaxed text-white/90">
                                    من خلال تقديم نموذج التسجيل وتحديد خيار الموافقة، فإنك تقر بأنك
                                    قد قرأت سياسة الخصوصية هذه وفهمتها وتوافق على جمع واستخدام
                                    بياناتك الشخصية وفقا لأحكامها.
                                 </p>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">
                                    8. التحديثات على سياسة الخصوصية
                                 </h3>
                                 <p className="mb-2 text-sm leading-relaxed text-white/90">
                                    قد نقوم بتحديث سياسة الخصوصية هذه من وقت لآخر لتعكس التغييرات
                                    التشغيلية أو النظامية أو التنظيمية. سيتم نشر أي تحديثات على هذه
                                    الصفحة وتصبح نافذة المفعول فور نشرها.
                                 </p>
                                 <p className="text-sm leading-relaxed text-white/90">
                                    نوصي بمراجعة هذه السياسة بشكل دوري.
                                 </p>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">9. التواصل</h3>
                                 <p className="text-sm leading-relaxed text-white/90">
                                    في حال وجود أي استفسار حول سياسة الخصوصية هذه أو طريقة التعامل
                                    مع بياناتك الشخصية، يرجى التواصل مع فريق تسجيل مؤتمر مبادرة
                                    القدرات البشرية عبر البريد الإلكتروني:
                                 </p>
                                 <p className="mt-2 text-base font-semibold text-primary">
                                    registration@esportsworldcup.com
                                 </p>
                              </div>
                           </div>
                        ) : (
                           <div className="space-y-6 text-white" dir="ltr">
                              <div className="border-b border-white/20 pb-3">
                                 <h2 className="bg-gradient-to-r from-primary to-accent bg-clip-text text-2xl font-bold text-transparent md:text-3xl">
                                    Privacy Policy
                                 </h2>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">
                                    1. Information We Collect
                                 </h3>
                                 <p className="mb-3 text-sm leading-relaxed text-white/90">
                                    When you complete the registration form, we may collect the
                                    following personal information:
                                 </p>
                                 <div className="space-y-3">
                                    <div>
                                       <p className="mb-2 text-base font-semibold text-primary">
                                          Personal details
                                       </p>
                                       <ul className="ml-4 list-inside list-disc space-y-1.5 text-sm text-white/80">
                                          <li>Gender</li>
                                          <li>Title</li>
                                          <li>First name and last name</li>
                                       </ul>
                                    </div>
                                    <div>
                                       <p className="mb-2 text-lg font-semibold text-primary">
                                          Professional details
                                       </p>
                                       <ul className="ml-4 list-inside list-disc space-y-2 text-white/80">
                                          <li>Sector</li>
                                          <li>Industry</li>
                                          <li>Company name</li>
                                          <li>Job title</li>
                                          <li>Position level</li>
                                       </ul>
                                    </div>
                                    <div>
                                       <p className="mb-2 text-lg font-semibold text-primary">
                                          Contact information
                                       </p>
                                       <ul className="ml-4 list-inside list-disc space-y-2 text-white/80">
                                          <li>Email address</li>
                                          <li>Mobile number</li>
                                          <li>Country of residence</li>
                                          <li>Nationality</li>
                                       </ul>
                                    </div>
                                    <div>
                                       <p className="mb-2 text-lg font-semibold text-primary">
                                          Engagement data
                                       </p>
                                       <ul className="ml-4 list-inside list-disc space-y-2 text-white/80">
                                          <li>How you heard about the Esports World Cup</li>
                                       </ul>
                                    </div>
                                    <div>
                                       <p className="mb-2 text-lg font-semibold text-primary">
                                          Identity and access verification
                                       </p>
                                       <ul className="ml-4 list-inside list-disc space-y-2 text-white/80">
                                          <li>
                                             Your profile photo will be added later through the
                                             event mobile application.
                                          </li>
                                          <li>
                                             A profile photo showing a full face front view with a
                                             white background, submitted for accreditation, and
                                             access control purposes
                                          </li>
                                       </ul>
                                    </div>
                                    <div>
                                       <p className="mb-2 text-lg font-semibold text-primary">
                                          Technical data
                                       </p>
                                       <ul className="ml-4 list-inside list-disc space-y-2 text-white/80">
                                          <li>IP address</li>
                                          <li>Device information</li>
                                          <li>
                                             Cookies and browsing data related to your use of the
                                             registration platform
                                          </li>
                                       </ul>
                                    </div>
                                    <p className="mt-3 rounded-lg border-l-4 border-primary bg-white/5 p-3 text-sm leading-relaxed text-white/90">
                                       Any information you provide through the form is collected on
                                       a voluntary basis, except where required for event access,
                                       accreditation, or security purposes.
                                    </p>
                                 </div>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">
                                    2. How We Use Your Information
                                 </h3>
                                 <p className="mb-3 text-sm leading-relaxed text-white/90">
                                    Your personal information is used for the following purposes:
                                 </p>
                                 <ul className="ml-4 list-inside list-disc space-y-2 text-sm text-white/80">
                                    <li>
                                       To process and manage your registration for the Human
                                       Capability Initiative
                                    </li>
                                    <li>
                                       To verify your identity and issue event credentials and
                                       badges
                                    </li>
                                    <li>To manage venue access and security clearance</li>
                                    <li>
                                       To communicate important updates related to the agenda,
                                       logistics, and event access
                                    </li>
                                    <li>
                                       To understand audience composition by sector, industry, and
                                       role for planning and reporting purposes
                                    </li>
                                    <li>
                                       To improve the registration experience and platform
                                       performance
                                    </li>
                                    <li>To respond to your inquiries and support requests</li>
                                    <li>
                                       To comply with applicable laws, regulations, and security
                                       requirements in the Kingdom of Saudi Arabia
                                    </li>
                                 </ul>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">
                                    3. Data Storage and Protection
                                 </h3>
                                 <p className="mb-3 text-sm leading-relaxed text-white/90">
                                    We apply appropriate administrative, technical, and
                                    organizational measures to safeguard your personal information
                                    from unauthorized access, loss, misuse, or disclosure.
                                 </p>
                                 <p className="mb-3 text-sm leading-relaxed text-white/90">
                                    In accordance with data protection regulations in the Kingdom of
                                    Saudi Arabia:
                                 </p>
                                 <ul className="ml-4 list-inside list-disc space-y-2 text-sm text-white/80">
                                    <li>
                                       Your data may be stored on secure servers located within the
                                       Kingdom
                                    </li>
                                    <li>
                                       Access to your information is restricted to authorized
                                       personnel only
                                    </li>
                                    <li>
                                       Your personal data is retained only for the duration
                                       necessary to support event operations, reporting, and
                                       compliance
                                    </li>
                                    <li>
                                       After the conclusion of the Esports World Cup and related
                                       activities, your data will be securely deleted or anonymized
                                    </li>
                                 </ul>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">
                                    4. Use of Cookies
                                 </h3>
                                 <p className="mb-2 text-sm leading-relaxed text-white/90">
                                    Our registration platform uses cookies to enhance functionality
                                    and improve user experience. Cookies help us understand how
                                    users interact with the platform and support system performance.
                                 </p>
                                 <p className="text-sm leading-relaxed text-white/90">
                                    You may disable cookies through your browser settings at any
                                    time. Please note that doing so may affect certain features of
                                    the registration platform.
                                 </p>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">
                                    5. Third Parties and Data Sharing
                                 </h3>
                                 <p className="mb-3 text-sm leading-relaxed text-white/90">
                                    Your personal data may be shared only with trusted parties
                                    involved in delivering the Esports World Cup, including:
                                 </p>
                                 <ul className="ml-4 list-inside list-disc space-y-2 text-sm text-white/80">
                                    <li>The official event organizing team</li>
                                    <li>Accreditation and badge production partners</li>
                                    <li>Venue access control and security teams</li>
                                    <li>
                                       Technical service providers supporting the registration
                                       system
                                    </li>
                                 </ul>
                                 <p className="mt-3 text-sm leading-relaxed text-white/90">
                                    All third parties are contractually required to protect your
                                    data and use it solely for purposes related to the delivery of
                                    the event.
                                 </p>
                                 <p className="mt-2 rounded-lg border-l-4 border-primary bg-white/5 p-3 text-sm leading-relaxed text-white/90">
                                    We do not sell, rent, or trade your personal information to
                                    third parties for marketing or commercial purposes.
                                 </p>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">
                                    6. Scope of This Policy
                                 </h3>
                                 <p className="text-sm leading-relaxed text-white/90">
                                    This Privacy Policy applies only to personal information
                                    collected through the official HCI online registration platform.
                                    It does not apply to information collected through offline
                                    channels unless explicitly stated.
                                 </p>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">
                                    7. Your Consent
                                 </h3>
                                 <p className="text-sm leading-relaxed text-white/90">
                                    By submitting the registration form and selecting the agreement
                                    checkbox, you confirm that you have read and understood this
                                    Privacy Policy and agree to the collection and use of your
                                    personal data in accordance with its terms.
                                 </p>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">
                                    8. Updates to This Privacy Policy
                                 </h3>
                                 <p className="mb-2 text-sm leading-relaxed text-white/90">
                                    We may update this Privacy Policy from time to time to reflect
                                    operational, legal, or regulatory changes. Any updates will be
                                    published on this page and will take effect immediately upon
                                    posting.
                                 </p>
                                 <p className="text-sm leading-relaxed text-white/90">
                                    We encourage you to review this policy periodically.
                                 </p>
                              </div>

                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <h3 className="mb-3 text-xl font-bold text-primary">9. Contact</h3>
                                 <p className="text-sm leading-relaxed text-white/90">
                                    If you have any questions about this Privacy Policy or how your
                                    personal information is handled, please contact the Human
                                    Capability Initiative registration team at:
                                 </p>
                                 <p className="mt-2 text-base font-semibold text-primary">
                                    registration@esportsworldcup.com
                                 </p>
                              </div>
                           </div>
                        )}
                     </div>
                  </div>
               </div>
            </Modal.Body>
         </Modal>
      </React.Fragment>
   );
};

export default PersonalInfoShort;
