import React from 'react';
import { NextLink, Translate, useTranslate } from '~/i18n';
import SpeakerLabel from '../home/speaker-label';
import Image from '../shared/image';
import classNames from 'classnames';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

interface Speaker {
   id: number;
   name: string;
   title: string | null;
   job_title: string | null;
   photo_url: string | null;
   color: string | null;
   order: number;
}
interface SpeakerGroup {
   label: {
      id: number;
      name: string;
   } | null;
   speakers: Speaker[];
}

interface speakersDataProps {
   speakers: SpeakerGroup[];
}

const SpeakerPageSections = ({ speakers }: speakersDataProps) => {
   const { translate, lang } = useTranslate();

   if (!speakers || speakers.length === 0) {
      return (
         <React.Fragment>
            <section className=" py-14 md:py-20">
               <div className="container">
                  <h2 className="text-center text-3xl font-extrabold text-white md:text-5xl">
                     {translate({ id: 'web:deve_go_speakers' })}
                  </h2>
                  <p className="mt-6 text-center text-white">
                     {lang === 'en' ? 'No speakers available.' : 'لا يوجد متحدثون متاحون.'}
                  </p>
               </div>
            </section>
         </React.Fragment>
      );
   }
   return (
      <React.Fragment>
         <section className="bg-primary py-14 md:py-20">
            <div className="container">
               {/* Title */}
               <h2 className="text-center text-3xl font-extrabold text-white md:text-5xl">
                  <Translate id="web:deve_go_speakers" />
               </h2>

               {/* Grouped Speakers */}
               <div className="mt-10">
                  {speakers.map((group, index) => (
                     <div key={group.label?.id || `uncategorized-${index}`} className="mb-12">
                        {group.label && (
                           <SpeakerLabel
                              text={group.label.name}
                              iconSrc="/images/speakers/flower.png"
                           />
                        )}
                        {/* Speakers Grid using container/row/col */}
                        {group.speakers && group.speakers.length > 0 && (
                           <div className="row gx-0 mt-6">
                              {group.speakers.map(speaker => (
                                 <div
                                    key={speaker.id}
                                    className="col-12 mb-6 sm:col-6 md:col-4 lg:col-3">
                                    <div className="flex justify-center px-[2px]">
                                       <div
                                          className={classNames(
                                             'relative h-[360px] w-full',
                                             'bg-contain bg-center bg-no-repeat',
                                             {
                                                'bg-shape-violet-en':
                                                   speaker.color === 'violet' && lang === 'en',
                                                'bg-shape-violet-ar':
                                                   speaker.color === 'violet' && lang === 'ar',
                                                'bg-shape-orange-en':
                                                   speaker.color === 'orange' && lang === 'en',
                                                'bg-shape-orange-ar':
                                                   speaker.color === 'orange' && lang === 'ar',
                                                'bg-shape-green-en':
                                                   speaker.color === 'green' && lang === 'en',
                                                'bg-shape-green-ar':
                                                   speaker.color === 'green' && lang === 'ar',
                                                'bg-shape-beige-en':
                                                   speaker.color === 'beige' && lang === 'en',
                                                'bg-shape-beige-ar':
                                                   speaker.color === 'beige' && lang === 'ar',
                                             }
                                          )}>
                                          {speaker.photo_url && (
                                             <Image
                                                src={speaker.photo_url}
                                                alt={speaker.name}
                                                layout="fill"
                                                objectFit="contain"
                                             />
                                          )}

                                          <div
                                             className={classNames(
                                                'absolute bottom-0 left-0 right-0',
                                                {
                                                   'bg-[#bfaed5]': speaker.color === 'violet',
                                                   'bg-[#fdc99b]': speaker.color === 'orange',
                                                   'bg-[#68c8c7]': speaker.color === 'green',
                                                   'bg-[#e9e5dd]': speaker.color === 'beige',
                                                }
                                             )}>
                                             <div
                                                className={classNames(
                                                   'absolute bottom-0 left-0 right-0',
                                                   {
                                                      'bg-[#bfaed5]': speaker.color === 'violet',
                                                      'bg-[#fdc99b]': speaker.color === 'orange',
                                                      'bg-[#68c8c7]': speaker.color === 'green',
                                                      'bg-[#e9e5dd]': speaker.color === 'beige',
                                                   }
                                                )}>
                                                <div className="flex h-full min-h-[92px] flex-col justify-center py-2">
                                                   {speaker.title && (
                                                      <div className="px-5 text-center text-xs font-medium text-gray-700">
                                                         {speaker.title}
                                                      </div>
                                                   )}
                                                   <div className="px-5 text-center text-sm font-semibold text-gray-900">
                                                      {speaker.name}
                                                   </div>
                                                   {speaker.job_title && (
                                                      <div className="px-5 text-center text-sm text-gray-600">
                                                         {speaker.job_title}
                                                      </div>
                                                   )}
                                                </div>
                                             </div>
                                          </div>
                                       </div>
                                    </div>
                                 </div>
                              ))}
                           </div>
                        )}
                     </div>
                  ))}
               </div>

               {/* back to homepage */}
               <div className="mt-10 text-center">
                  <NextLink
                     href="/"
                     className="inline-block rounded-lg bg-white px-8 py-3 text-lg font-semibold text-secondary transition-colors hover:bg-gray-100">
                     {lang === 'en' ? 'Back to Homepage' : 'العودة إلى الصفحة الرئيسية'}
                  </NextLink>
               </div>
            </div>
         </section>
      </React.Fragment>
   );
};

export default SpeakerPageSections;
