import classNames from 'classnames';
import React, { useEffect, useState } from 'react';
import { Controller, useFormContext } from 'react-hook-form';
import SubmitBtn from '~/components/shared/buttons/submit-btn';
import CustomInput from '~/components/shared/forms/custom-input';
import { Translate, useTranslate } from '~/i18n';
import toast from 'react-hot-toast';
import { GuestType } from '~/interfaces/guest';
import validator from 'validator';
import CustomRadioInput from '~/components/shared/forms/custom-radio-input';
import isUniqueAttribute from '~/utils/unique-attribute';
import Modal from '~/components/shared/modals';
import VerifyEmailForm from '../../../verify-email-form';
import CheckboxInput from '~/components/shared/forms/checkbox-input';
import { XMarkIcon } from '@heroicons/react/20/solid';
import { useGoogleReCaptcha } from 'react-google-recaptcha-v3';
import Axios from '~/utils/axios';
import Cookies from 'js-cookie';
import PhoneInputV2 from '~/components/shared/forms/phone-input-new';
import parsePhoneNumberFromString from 'libphonenumber-js';
import StaticSelectNew from '~/components/shared/select/static-select-new';
import CountrySelectNew from '~/components/shared/select/countries-select-new';
import { EdgeXJobRoleTypeSelect } from '~/data/edgex-job-role-types-select';
import { EdgeXEducationLevelsSelect } from '~/data/edgex-education-levels-select';
import { EdgeXAreasOfInterestSelect } from '~/data/edgex-areas-of-interest-select';
import { EdgeXOrganizationTypeSelect } from '~/data/edgex-organization-type-select';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type PersonalInfoShortProps = {
   onNextClick: () => any;
   onUpdateClick: () => any;
   onBackClick: () => any;
   setStep?: (val: string) => any;
   step?: string | undefined;
   nextStep?: string;
   // countries: CountryType[];
   guestEmail?: string | null;
   guestFirstName?: string | null;
   guestLastName?: string | null;
   guestCompany?: string | null;
   guestPosition?: string | null;
   prefilldata?: string | null;
   lock_data?: string | null;

   role?: string;
   optionalFields?: string[];
   mandatoryFields?: string[];
   withOtp: boolean;
   withSmsOtp: boolean;
   token?: string | null;
   withAlternativeEmail: boolean;
};

// type Item = {
//    label: string;
//    value: string;
// };

const PersonalInfoShort = ({
   onNextClick,
   // onBackClick,
   // onUpdateClick,
   step,
   // nextStep,
   // countries,
   guestEmail,
   guestFirstName,
   guestLastName,
   guestCompany,
   guestPosition,
   prefilldata,
   lock_data,
   role,
   // optionalFields,
   mandatoryFields,
   withOtp,
   withSmsOtp,
   token,
}: // withAlternativeEmail,
// role,
PersonalInfoShortProps) => {
   const { translate } = useTranslate();
   const [loading, setLoading] = useState(false);
   // setLockEmail
   const [verificationDone, setVerificationDone] = useState(false);
   // console.log(guestEmail, 'guestEmail');
   // console.log(guestFirstName, 'guestFirstName');
   // console.log(guestLastName, 'guestLastName');
   const [isOpen, setIsOpen] = useState(false);
   const [isPrivacyModalOpen, setIsPrivacyModalOpen] = useState(false);
   const { lang } = useTranslate();

   const {
      register,
      handleSubmit,
      getValues,
      control,
      setValue,
      watch,
      // trigger,

      formState: { errors },
   } = useFormContext<GuestType>();

   // Sync hasPlusOne with form value
   // const hasPlusOneValue = watch('has_plus_one');
   // const primaryEmail = watch('email');
   // useEffect(() => {
   //    setHasPlusOne(hasPlusOneValue === 'yes' || hasPlusOneValue === true);
   // }, [hasPlusOneValue]);

   // // Re-validate plus_one_email when primary email changes
   // useEffect(() => {
   //    if (hasPlusOne && primaryEmail) {
   //       trigger('plus_one_email');
   //    }
   // }, [primaryEmail, hasPlusOne, trigger]);

   const submitForm = async (values: GuestType) => {
      try {
         if (getValues('is_email_verified') === 'yes' || getValues('is_phone_verified') === 'yes') {
            submitForm2(values);
         } else {
            if (!withOtp && !withSmsOtp) {
               submitForm2(values);
            } else {
               setIsOpen(true);
            }
         }
      } catch (error: any) {
         console.log(error, 'error');
      }
      // setLoading(false);
   };
   // const submitForm2 = async () => {
   //    // setLoading(true);
   //    try {
   //       const values = getValues();

   //       const updatedUserObj = {
   //          ...values,
   //          step: nextStep,
   //       };
   //       // cookie.set('user_data', JSON.stringify(updatedUserObj));
   //       cookie.set('user_data', JSON.stringify(updatedUserObj), {
   //          secure: true, // Ensures the cookie is secure in production
   //          sameSite: 'Strict', // Prevents cross-site request forgery
   //       });
   //       toast.success(translate({ id: 'res:info_saved' }));
   //       // onNextClick();
   //    } catch (error: any) {
   //       console.log(error, 'error');
   //    }
   //    // setLoading(false);
   // };
   const { executeRecaptcha } = useGoogleReCaptcha();

   const submitForm2 = async (values: GuestType) => {
      setLoading(true);
      if (loading) {
         return;
      }
      setLoading(true);

      try {
         const recaptcha = await executeRecaptcha?.();

         const data = {
            ...values,
            code: token || '', //todo: check
            category: role,
            email: values?.email?.toLowerCase(),
            recaptcha,
         };

         // console.log(data, 'data');

         const response = await Axios.post(`guests?lang=${lang}`, data);
         Cookies.set('reg_num', response.data.data);

         // to success page
         onNextClick();
      } catch (error: any) {
         setLoading(false);
         if (error.response?.status === 404) {
            toast.error(error.response?.data?.data);
         } else if (error?.response?.status === 403) {
            toast.error(translate({ id: 'res:recaptcha_failed' }), {
               duration: 4000,
            });
         } else {
            toast.error(translate({ id: 'res:500' }));
         }
         console.log(error, 'error');
      }
   };

   // Prefill fields when prefilldata is "yes"
   useEffect(() => {
      if (prefilldata === 'yes') {
         if (guestFirstName) {
            setValue('first_name', guestFirstName, { shouldValidate: false });
         }
         if (guestLastName) {
            setValue('last_name', guestLastName, { shouldValidate: false });
         }
         if (guestEmail) {
            setValue('email', guestEmail, { shouldValidate: false });
         }
         if (guestCompany) {
            setValue('company', guestCompany, { shouldValidate: false });
         }
         if (guestPosition) {
            setValue('job_title', guestPosition, { shouldValidate: false });
         }
      }
   }, [
      prefilldata,
      guestFirstName,
      guestLastName,
      guestEmail,
      guestCompany,
      guestPosition,
      setValue,
   ]);

   // Determine if fields should be locked
   const isLocked = lock_data === 'yes';

   return (
      <React.Fragment>
         {step === 'personal-info-1' ? (
            <React.Fragment>
               <div className="rounded-xl border  shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)]">
                  <div className="p-6 sm:p-12">
                     <h2
                        className={classNames(
                           'text-xl font-bold capitalize text-white md:mb-4 md:text-2xl'
                        )}>
                        <Translate id="web:personal_information" />
                     </h2>

                     <div className="pt-5">
                        <form
                           noValidate
                           onSubmit={handleSubmit(submitForm)}
                           className="relative"
                           autoComplete="off">
                           {/* First Name */}
                           <CustomInput
                              label={translate({ id: 'web:first_name' })}
                              type="text"
                              isRequired={mandatoryFields?.includes('first_name') ?? false}
                              isInline
                              autoComplete="off"
                              placeHolder={translate({ id: 'web:first_name' })}
                              id="first_name"
                              disabled={isLocked}
                              error={errors.first_name?.message}
                              {...register('first_name', {
                                 required: mandatoryFields?.includes('first_name')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 pattern: {
                                    value: /^[a-zA-Z0-9 -]+$/i,
                                    message: translate({
                                       id: 'validation:english_letters',
                                    }),
                                 },
                              })}
                           />

                           {/* Last Name */}
                           <CustomInput
                              label={translate({ id: 'web:last_name' })}
                              type="text"
                              autoComplete="off"
                              placeHolder={translate({ id: 'web:last_name' })}
                              id="last_name"
                              isRequired={mandatoryFields?.includes('last_name') ?? false}
                              isInline
                              disabled={isLocked}
                              error={errors.last_name?.message}
                              {...register('last_name', {
                                 required: mandatoryFields?.includes('last_name')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 pattern: {
                                    value: /^[a-zA-Z0-9 -]+$/i,
                                    message: translate({
                                       id: 'validation:english_letters',
                                    }),
                                 },
                              })}
                           />

                           {/* Email Address */}
                           <CustomInput
                              label={translate({ id: 'web:email' })}
                              type="email"
                              isRequired={mandatoryFields?.includes('email') ?? false}
                              isInline
                              placeHolder={translate({ id: 'web:email' })}
                              id="email"
                              disabled={isLocked || verificationDone}
                              error={errors.email?.message}
                              {...register('email', {
                                 required: mandatoryFields?.includes('email')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 validate: {
                                    trim: (value: any) =>
                                       value == value.trim() || 'يرجى حذف المسافات',
                                    isEmail: value => {
                                       if (!mandatoryFields?.includes('email') && !value) {
                                          return true;
                                       }
                                       return (
                                          validator.isEmail(value || '') ||
                                          translate({ id: 'validation:not_email' })
                                       );
                                    },
                                    isUnique: async value => {
                                       if (!mandatoryFields?.includes('email') && !value) {
                                          return true;
                                       }
                                       const { isUnique, status } = await isUniqueAttribute(
                                          'guests',
                                          'email',
                                          value,
                                          'create',
                                          getValues('id')
                                       );
                                       if (!isUnique && status === 422) {
                                          return translate({ id: 'validation:unique_email' });
                                       } else if (!isUnique) {
                                          return translate({
                                             id: 'validation:unique_email_failed',
                                          });
                                       } else {
                                          return true;
                                       }
                                    },
                                 },
                              })}
                           />

                           {/* Country */}
                           <Controller
                              name="country_of_residence"
                              control={control}
                              render={() => (
                                 <CountrySelectNew
                                    isRequired={
                                       mandatoryFields?.includes('country_of_residence') ?? false
                                    }
                                    selected_id={getValues()['country_of_residence']}
                                    label={translate({ id: 'web:country' })}
                                    errors={errors.country_of_residence?.message}
                                    callBack={(item: { value: string } | null) => {
                                       setValue('country_of_residence', item?.value || null, {
                                          shouldValidate: true,
                                       });
                                    }}
                                 />
                              )}
                              rules={{
                                 required: mandatoryFields?.includes('country_of_residence')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                              }}
                           />

                           {/* City */}
                           <CustomInput
                              label={translate({ id: 'web:city' })}
                              type="text"
                              autoComplete="off"
                              placeHolder={translate({ id: 'web:city' })}
                              id="city"
                              isRequired={mandatoryFields?.includes('city') ?? false}
                              isInline
                              disabled={isLocked}
                              error={errors.city?.message}
                              {...register('city', {
                                 required: mandatoryFields?.includes('city')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 pattern: {
                                    value: /^[a-zA-Z0-9 -]+$/i,
                                    message: translate({
                                       id: 'validation:english_letters',
                                    }),
                                 },
                              })}
                           />

                           {/* Organization / Institution */}
                           <CustomInput
                              label={translate({ id: 'web:company' })}
                              type="text"
                              autoComplete="off"
                              placeHolder={translate({ id: 'web:company' })}
                              id="company"
                              isRequired={mandatoryFields?.includes('company') ?? false}
                              isInline
                              disabled={isLocked}
                              error={errors.company?.message}
                              {...register('company', {
                                 required: mandatoryFields?.includes('company')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 maxLength: {
                                    value: 100,
                                    message: translate({
                                       id: 'validation:you_reached_the_text_limit',
                                    }),
                                 },
                                 pattern: {
                                    value: /^(?!.*[\u0600-\u06FF]).+$/,
                                    message: translate({
                                       id: 'validation:english_letters',
                                    }),
                                 },
                              })}
                           />

                           {/* Job Title */}
                           <CustomInput
                              label={translate({ id: 'web:job_title' })}
                              type="text"
                              autoComplete="off"
                              placeHolder={translate({ id: 'web:job_title' })}
                              id="job_title"
                              isRequired={mandatoryFields?.includes('job_title') ?? false}
                              isInline
                              error={errors.job_title?.message}
                              {...register('job_title', {
                                 required: mandatoryFields?.includes('job_title')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 maxLength: {
                                    value: 100,
                                    message: translate({
                                       id: 'validation:you_reached_the_text_limit',
                                    }),
                                 },
                                 pattern: {
                                    value: /^(?!.*[\u0600-\u06FF]).+$/,
                                    message: translate({
                                       id: 'validation:english_letters',
                                    }),
                                 },
                              })}
                           />

                           {/* Mobile Number */}
                           <Controller
                              name="phone"
                              control={control}
                              rules={{
                                 required: mandatoryFields?.includes('phone')
                                    ? translate({ id: 'validation:required' })
                                    : false,
                                 validate: (v?: string | null) => {
                                    if (!mandatoryFields?.includes('phone') && !v) {
                                       return true;
                                    }
                                    const s = (v ?? '').replace(/\s+/g, '');
                                    const pn = parsePhoneNumberFromString(s);
                                    return pn?.isValid()
                                       ? true
                                       : translate({ id: 'validation:invalid_phone' });
                                 },
                              }}
                              render={({ field }) => (
                                 <PhoneInputV2
                                    lang={lang}
                                    label={translate({ id: 'web:phone' })}
                                    isInline
                                    isRequired={mandatoryFields?.includes('phone') ?? false}
                                    defaultCountry="sa"
                                    value={field.value ?? ''}
                                    onChange={field.onChange}
                                    error={errors.phone?.message}
                                 />
                              )}
                           />

                           {/* edgex_job_role */}
                           <Controller
                              name="edgex_job_role"
                              control={control}
                              render={() => (
                                 <StaticSelectNew
                                    options={EdgeXJobRoleTypeSelect}
                                    isRequired={true}
                                    selected_id={watch('edgex_job_role')}
                                    label={translate({ id: 'web:edgex_job_role' })}
                                    errors={errors.edgex_job_role?.message}
                                    placeholderTranslationId="web:select_job_role"
                                    dropdownRounded="xl"
                                    callBack={(item: { value: string } | null) => {
                                       setValue('edgex_job_role', item?.value || null, {
                                          shouldValidate: true,
                                       });
                                    }}
                                 />
                              )}
                              rules={{
                                 required: translate({ id: 'validation:required' }),
                              }}
                           />

                           {/* edgex_decision_influence */}
                           <CustomRadioInput
                              label={translate({ id: 'web:edgex_decision_influence' })}
                              isRequired={true}
                              isInline
                              options={[
                                 { value: 'yes', label: translate({ id: 'web:yes' }) },
                                 { value: 'no', label: translate({ id: 'web:no' }) },
                              ]}
                              id="edgex_decision_influence"
                              error={errors.edgex_decision_influence?.message}
                              {...register('edgex_decision_influence', {
                                 required: translate({ id: 'validation:required' }),
                              })}
                           />

                           <div className="row">
                              <div className="md:col-12">
                                 {/* edgex_education_levels */}
                                 <CheckboxInput
                                    label={translate({ id: 'web:edgex_education_levels' })}
                                    isRequired={
                                       mandatoryFields?.includes('edgex_education_levels') ?? false
                                    }
                                    isInline
                                    options={EdgeXEducationLevelsSelect}
                                    id="edgex_education_levels"
                                    error={errors.edgex_education_levels?.message}
                                    {...register('edgex_education_levels', {
                                       required: mandatoryFields?.includes('edgex_education_levels')
                                          ? translate({ id: 'validation:required' })
                                          : false,
                                    })}
                                 />
                              </div>
                           </div>

                           <div className="row">
                              <div className="md:col-12">
                                 {/* edgex_areas_of_interest */}
                                 <CheckboxInput
                                    label={translate({ id: 'web:edgex_areas_of_interest' })}
                                    isRequired={
                                       mandatoryFields?.includes('edgex_education_levels') ?? false
                                    }
                                    isInline
                                    options={EdgeXAreasOfInterestSelect}
                                    id="edgex_areas_of_interest"
                                    error={errors.edgex_areas_of_interest?.message}
                                    {...register('edgex_areas_of_interest', {
                                       required: mandatoryFields?.includes('edgex_education_levels')
                                          ? translate({ id: 'validation:required' })
                                          : false,
                                       validate: (value: string[] | null | undefined) => {
                                          if (!value || value.length === 0) {
                                             return translate({ id: 'validation:required' });
                                          }
                                          if (value.length > 5) {
                                             return 'Maximum 5 selections allowed';
                                          }
                                          return true;
                                       },
                                    })}
                                 />
                              </div>
                           </div>

                           {/* edgex_organization_type */}
                           <Controller
                              name="edgex_organization_type"
                              control={control}
                              render={() => (
                                 <StaticSelectNew
                                    options={EdgeXOrganizationTypeSelect}
                                    isRequired={true}
                                    selected_id={watch('edgex_organization_type')}
                                    label={translate({ id: 'web:edgex_organization_type' })}
                                    errors={errors.edgex_organization_type?.message}
                                    placeholderTranslationId="web:select_organization_type"
                                    dropdownRounded="xl"
                                    callBack={(item: { value: string } | null) => {
                                       setValue('edgex_organization_type', item?.value || null, {
                                          shouldValidate: true,
                                       });
                                    }}
                                 />
                              )}
                              rules={{
                                 required: translate({ id: 'validation:required' }),
                              }}
                           />

                           {/* terms */}
                           <div className="row">
                              <div className="col-12">
                                 <p className="text-white">
                                    {lang === 'ar' ? (
                                       <>
                                          بإرسال هذا النموذج أوافق على{' '}
                                          <button
                                             type="button"
                                             onClick={() => setIsPrivacyModalOpen(true)}
                                             className="cursor-pointer underline transition-colors hover:text-primary">
                                             شروط الفعالية وسياسة الخصوصية
                                          </button>
                                       </>
                                    ) : (
                                       <>
                                          By submitting this form I agree to the event{' '}
                                          <button
                                             type="button"
                                             onClick={() => setIsPrivacyModalOpen(true)}
                                             className="cursor-pointer underline transition-colors hover:text-primary">
                                             terms and privacy policy
                                          </button>
                                       </>
                                    )}
                                 </p>
                              </div>
                           </div>

                           <div className="mt-10">
                              {/*  email verification Done */}
                              <div className="row justify-end ">
                                 <div className="sm:col-4">
                                    <SubmitBtn
                                       id="submit-btn" //* for test cases
                                       loading={loading}
                                       className="w-full overflow-hidden rounded-md bg-primary p-3"
                                       text={`${translate({ id: `web:submit` })}`}
                                    />
                                 </div>
                              </div>
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
               <div className="mt-7 text-center">
                  <p className={classNames('mt-5 text-lg font-bold ', 'text-white')}>
                     <Translate id="homepage:contact_us" />
                  </p>

                  <div className="mt-1">
                     <p className="break-all font-en text-white/80">
                        registration@esportsworldcup.com
                     </p>
                  </div>
               </div>
            </React.Fragment>
         ) : (
            ''
         )}

         <Modal size="md" open={isOpen}>
            <Modal.Body>
               <div className="">
                  <div className="relative rounded-lg border bg-black p-4 shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)] sm:px-10 sm:py-6">
                     <div className="">
                        <div className="row">
                           <div className="col-12">
                              <VerifyEmailForm
                                 isEmailVerificationOn={withOtp}
                                 isPhoneVerificationOn={withSmsOtp}
                                 autoSendPhoneOtp={withSmsOtp}
                                 setIsOpen={setIsOpen}
                                 userEmail={getValues('email') || ''}
                                 userPhone={getValues('phone') || ''}
                                 formData={{
                                    email: getValues('email') || '',
                                    first_name: getValues('first_name'),
                                    last_name: getValues('last_name'),
                                    company: getValues('company'),
                                    job_title: getValues('job_title'),
                                    invitation_token: token || null,
                                    category: role || null,
                                 }}
                                 callBack={(tokens: {
                                    emailToken?: string;
                                    phoneToken?: string;
                                 }) => {
                                    if (withOtp && tokens.emailToken) {
                                       setValue('is_email_verified', 'yes');
                                       setValue('otp_token', tokens.emailToken);
                                    }
                                    if (withSmsOtp && tokens.phoneToken) {
                                       setValue('is_phone_verified', 'yes');
                                       setValue('sms_otp_token', tokens.phoneToken);
                                    }
                                    setVerificationDone(true);
                                    // setIsOpen(false);
                                    // Auto-submit form after verification
                                    const formValues = getValues();
                                    submitForm2(formValues);
                                 }}
                              />
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </Modal.Body>
         </Modal>

         {/* Privacy Policy Modal */}
         <Modal
            size={1024}
            open={isPrivacyModalOpen}
            onClickOutside={() => setIsPrivacyModalOpen(false)}>
            <Modal.Body>
               <div className="relative rounded-xl border border-white/20 bg-gradient-to-b from-black via-black to-gray-900 shadow-2xl">
                  <style jsx>{`
                     .privacy-scrollbar::-webkit-scrollbar {
                        width: 8px;
                     }
                     .privacy-scrollbar::-webkit-scrollbar-track {
                        background: rgba(255, 255, 255, 0.1);
                        border-radius: 4px;
                     }
                     .privacy-scrollbar::-webkit-scrollbar-thumb {
                        background: rgba(255, 255, 255, 0.3);
                        border-radius: 4px;
                     }
                     .privacy-scrollbar::-webkit-scrollbar-thumb:hover {
                        background: rgba(255, 255, 255, 0.5);
                     }
                  `}</style>
                  <button
                     type="button"
                     onClick={() => setIsPrivacyModalOpen(false)}
                     className="absolute top-6 z-20 flex h-10 w-10 items-center justify-center rounded-full bg-white/10 text-white transition-all hover:scale-110 hover:bg-white/20 hover:text-primary ltr:right-6 rtl:left-6">
                     <XMarkIcon className="h-6 w-6" />
                  </button>
                  <div className="privacy-scrollbar max-h-[85vh] overflow-y-auto">
                     <div className="p-6 ltr:pr-14 rtl:pl-14 sm:p-8 md:p-12">
                        {lang === 'ar' ? (
                           <div className="space-y-6 text-white" dir="rtl">
                              <div className="border-b border-white/20 pb-3">
                                 <h2 className="from-primary to-accent bg-clip-text text-2xl font-bold text-transparent ltr:bg-gradient-to-r rtl:bg-gradient-to-l md:text-3xl">
                                    سياسة الخصوصية
                                 </h2>
                              </div>
                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <p className="text-sm leading-relaxed text-white/90">
                                    بإرسال هذا النموذج، أنت توافق على شروط الفعالية وسياسة الخصوصية.
                                 </p>
                              </div>
                           </div>
                        ) : (
                           <div className="space-y-6 text-white">
                              <div className="border-b border-white/20 pb-3">
                                 <h2 className="bg-gradient-to-r from-primary to-accent bg-clip-text text-2xl font-bold text-transparent md:text-3xl">
                                    Privacy Policy
                                 </h2>
                              </div>
                              <div className="rounded-lg border border-white/10 bg-white/5 p-5">
                                 <p className="text-sm leading-relaxed text-white/90">
                                    By submitting this form, you agree to the event terms and
                                    privacy policy.
                                 </p>
                              </div>
                           </div>
                        )}
                     </div>
                  </div>
               </div>
            </Modal.Body>
         </Modal>
      </React.Fragment>
   );
};

export default PersonalInfoShort;
