import classNames from 'classnames';
import { forwardRef } from 'react';
import Label from './label';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type Item = {
   label: string | React.ReactNode;
   value: string;
   disabled?: boolean;
};

export type InputProps = {
   label?: React.ReactNode;
   error?: React.ReactNode;
   name?: string;
   id?: string;
   innerRef?: any;
   disabled?: boolean;
   placeHolder?: string;
   autoComplete?: string;
   className?: string;
   groupClassName?: string;
   options: Item[];
   isInline?: boolean;
   isRequired?: boolean;
   help?: React.ReactNode;
} & React.HTMLAttributes<HTMLInputElement | HTMLTextAreaElement>;

const CheckboxInput = forwardRef<any, InputProps>(
   (
      {
         label,
         error,
         groupClassName,
         disabled = false,
         id = '',
         isInline = false,
         isRequired = false,
         help,
         options,
         ...props
      },
      ref
   ) => {
      return (
         <div className={groupClassName || classNames(isInline ? 'row' : 'relative mb-5  w-full')}>
            {label && (
               <div className={classNames(isInline ? 'col-3 mb-5 self-center' : '')}>
                  <Label id={id} label={label} isRequired={isRequired} />
               </div>
            )}
            <div className={classNames(isInline ? 'col-9 mb-5' : '')}>
               <div className="col-12">
                  <div className={classNames('')}>
                     {options.map((item, key) => (
                        <label
                           key={key}
                           className={classNames(
                              'flex cursor-pointer items-center space-x-2 rtl:space-x-reverse',
                              (disabled || item.disabled) && 'cursor-not-allowed opacity-60'
                           )}>
                           <input
                              id={id}
                              ref={ref}
                              type="checkbox"
                              className="form-checkbox border-white/50 bg-transparent text-accent focus:outline-none focus:ring focus:ring-accent focus:ring-opacity-50 focus:ring-offset-0 focus:ring-offset-transparent"
                              value={item.value}
                              disabled={disabled || item.disabled}
                              {...props}
                           />
                           <div
                              className={classNames(
                                 'text-white',
                                 (disabled || item.disabled) && 'line-through'
                              )}>
                              {item.label}
                           </div>
                        </label>
                     ))}
                  </div>
                  {help && <div>{help}</div>}
                  {error && typeof error !== 'boolean' && (
                     <div className="absolute text-xs text-red-500" role="alert">
                        {error}
                     </div>
                  )}
               </div>
            </div>
         </div>
      );
   }
);

CheckboxInput.displayName = `CheckboxInput`;
export default CheckboxInput;
