import classNames from 'classnames';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type LabelProps = {
   label?: React.ReactNode | string;
   isRequired?: boolean;
   id: string;
};

const Label = ({ label, isRequired, id }: LabelProps) => {
   return (
      <label
         htmlFor={id}
         className={classNames(
            'inline-block text-sm font-medium text-white',
            isRequired && 'required-label'
         )}>
         {label}
      </label>
   );
};

export default Label;
