import { NextLink, Translate } from '~/i18n';
// import { motion } from 'framer-motion';
import React, { useEffect } from 'react';
// import CheckInvitationForm from '../join/check-invitation-form';
import Cookies from 'js-cookie';
// import Image from '../shared/image';
import Timer from './timer';
import classNames from 'classnames';
// import classNames from 'classnames';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const HomepageSections = () => {
   // const { translate } = useTranslate();

   useEffect(() => {
      Cookies.remove('user_data');
      // Cookies.remove('reg_num');
   }, []);

   return (
      <section className="relative py-10 sm:py-14">
         {/* subtle glow behind card */}
         <div
            className="pointer-events-none absolute left-1/2 top-10 h-[420px] w-[420px] -translate-x-1/2 rounded-full opacity-30 blur-3xl"
            style={{
               background:
                  'radial-gradient(circle at center, rgba(0,155,152,0.35), rgba(226,163,40,0.18), transparent 65%)',
            }}
         />

         <div className="container relative">
            <div className="row justify-center">
               <div className="relative text-center md:col-7">
                  <div
                     className={classNames(
                        'rounded-2xl p-[1px]',
                        'from-white/15 bg-gradient-to-r via-white/5 to-white/10',
                        'shadow-[0_12px_40px_rgba(0,0,0,0.45)]'
                     )}>
                     <div
                        className={classNames(
                           'rounded-2xl border border-white/10',
                           'bg-black/35 backdrop-blur-xl',
                           'p-6 sm:p-8 sm:pb-10'
                        )}>
                        {/* <div className="col-12 text-center">
                           <div className="mb-4 inline-block rounded-lg bg-yellow-400 py-1 px-4 text-xs">
                              <div>نسخة تجريبية</div>
                              <div>Testing version</div>
                           </div>
                        </div> */}

                        <h1
                           className={classNames(
                              'text-center text-2xl font-black sm:text-3xl',
                              'tracking-tight',
                              'from-[#4E442D] to-gold-primary bg-clip-text text-transparent ltr:bg-gradient-to-r rtl:bg-gradient-to-l'
                           )}>
                           <Translate id="web:event_name" />
                        </h1>

                        <div className="mt-6">
                           <ul className="row justify-center pb-2">
                              {/* Location */}
                              <li className="col-12 pb-4">
                                 <div
                                    className={classNames(
                                       'flex items-center gap-3 rtl:space-x-reverse',
                                       'rounded-xl border border-white/10',
                                       'bg-white/5 px-4 py-3',
                                       'hover:bg-white/7 hover:border-white/15 transition'
                                    )}>
                                    <div className="flex h-11 w-11 items-center justify-center rounded-lg bg-white/5">
                                       <svg
                                          className="h-[34px] w-[34px] text-white"
                                          fill="none"
                                          stroke="currentColor"
                                          viewBox="0 0 24 24"
                                          xmlns="http://www.w3.org/2000/svg">
                                          <path
                                             strokeLinecap="round"
                                             strokeLinejoin="round"
                                             strokeWidth={2}
                                             d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z"
                                          />
                                          <path
                                             strokeLinecap="round"
                                             strokeLinejoin="round"
                                             strokeWidth={2}
                                             d="M15 11a3 3 0 11-6 0 3 3 0 016 0z"
                                          />
                                       </svg>
                                    </div>
                                    <div className="text-left rtl:text-right">
                                       <a
                                          className="font-semibold text-white underline decoration-white/30 underline-offset-4 transition hover:decoration-white/70"
                                          href="https://share.google/3U7BiRzBv0bY9s01d"
                                          target="_blank"
                                          rel="noopener noreferrer">
                                          <Translate id="web:event_location" />
                                       </a>
                                       {/* <div className="text-white/65 mt-0.5 text-xs">
                                          <Translate id="web:open_in_maps" />
                                       </div> */}
                                    </div>
                                 </div>
                              </li>

                              {/* Date */}
                              <li className="col-12 pb-4">
                                 <div
                                    className={classNames(
                                       'flex items-center gap-3 rtl:space-x-reverse',
                                       'rounded-xl border border-white/10',
                                       'bg-white/5 px-4 py-3',
                                       'hover:bg-white/7 hover:border-white/15 transition'
                                    )}>
                                    <div className="flex h-11 w-11 items-center justify-center rounded-lg bg-white/5">
                                       <svg
                                          className="h-[34px] w-[34px] text-white"
                                          fill="none"
                                          stroke="currentColor"
                                          viewBox="0 0 24 24"
                                          xmlns="http://www.w3.org/2000/svg">
                                          <path
                                             strokeLinecap="round"
                                             strokeLinejoin="round"
                                             strokeWidth={2}
                                             d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z"
                                          />
                                       </svg>
                                    </div>
                                    <div className="text-left font-semibold text-white rtl:text-right">
                                       <Translate id="web:event_date" />
                                       {/* <div className="text-white/65 mt-0.5 text-xs font-normal">
                                          <Translate id="web:save_the_date" />
                                       </div> */}
                                    </div>
                                 </div>
                              </li>

                              {/* Time */}
                              {/* <li className="col-12 pb-1">
                                 <div
                                    className={classNames(
                                       'flex items-center gap-3 rtl:space-x-reverse',
                                       'rounded-xl border border-white/10',
                                       'bg-white/5 px-4 py-3',
                                       'hover:bg-white/7 hover:border-white/15 transition'
                                    )}>
                                    <div className="flex h-11 w-11 items-center justify-center rounded-lg bg-white/5">
                                       <img
                                          src="/images/clock.png"
                                          className="h-[34px] w-[34px]"
                                          alt="clock"
                                       />
                                    </div>
                                    <div className="text-left font-semibold text-white rtl:text-right">
                                       <Translate id="web:event_time" />
                                       <div className="text-white/65 mt-0.5 text-xs font-normal">
                                          <Translate id="web:doors_open_note" />
                                       </div> 
                                    </div>
                                 </div>
                              </li> */}
                           </ul>
                        </div>

                        <div className="mt-6">
                           <Timer />
                        </div>

                        <div className="mt-6 text-center">
                           <div className="row justify-center">
                              <div className="md:col-6">
                                 <NextLink
                                    href="/join/attendee"
                                    className={classNames(
                                       'block w-full border-none border-transparent px-4 py-3 text-center text-sm font-bold leading-5 text-white',

                                       // 'disabled:cursor-not-allowed disabled:opacity-50',
                                       'bg-primary hover:bg-primary-600',
                                       // 'bg-gradient-to-r from-[#C3FF42] via-[#27CBC0] to-[#0077C0]',
                                       'focus:outline-none focus:ring focus:ring-primary focus:ring-opacity-50',
                                       'transition-all duration-150',
                                       'rounded-xl',
                                       'bg-gradient-to-r from-[#4E442D] to-gold-primary',

                                       'rounded-xl'
                                    )}>
                                    <Translate id="web:register_now" />
                                 </NextLink>
                              </div>
                           </div>
                        </div>

                        <div className="mt-8 border-t border-white/10 pt-6">
                           <p
                              className={classNames(
                                 'text-center text-xl font-black sm:text-2xl',
                                 'from-[#4E442D] to-gold-primary bg-clip-text text-transparent ltr:bg-gradient-to-r rtl:bg-gradient-to-l'
                              )}>
                              <Translate id="homepage:contact_us" />
                           </p>

                           <div className="mt-2">
                              <p className="break-all font-en text-sm text-white/80">
                                 registration@esportsworldcup.com
                              </p>
                           </div>
                        </div>

                        {/* keep your old blocks/commented code below */}
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
   );
};

export default HomepageSections;
