// import { Translate } from '~/i18n';
// import { useAuth } from '~/auth';
import { differenceInSeconds, isPast } from 'date-fns';
import React, { memo } from 'react';
import { useTimer } from 'reactjs-countdown-hook';
import { Translate } from '~/i18n';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/
const Timer = () => {
   // Event date: July 6th, 2026 (using explicit Date constructor to avoid parsing ambiguity)
   // Month is 0-indexed: 6 = July, day = 6
   const eventDate = new Date(2026, 6, 6, 0, 0, 0);
   const statTimeInSeconds = differenceInSeconds(eventDate, new Date());

   const { seconds, minutes, hours, days } = useTimer(statTimeInSeconds);

   return (
      <div className="flex justify-center">
         <div className="w-full">
            {isPast(eventDate) ? (
               <div className="py-2"></div>
            ) : (
               <React.Fragment>
                  <div className="flex flex-wrap items-center justify-center gap-2 sm:gap-3 md:gap-4">
                     {/* Days */}
                     <div className="relative">
                        <div className="relative rounded-xl border border-white/10 bg-gradient-to-br from-white/5 to-white/0 p-3 shadow-lg backdrop-blur-sm sm:p-4">
                           <div className="absolute inset-0 rounded-xl bg-gradient-to-br from-[#4E442D]/10 to-gold-primary/5 opacity-50"></div>
                           <div className="relative">
                              <div className="text-center">
                                 <div className="bg-gradient-to-r from-[#4E442D] to-gold-primary bg-clip-text text-2xl font-black leading-tight text-transparent sm:text-3xl md:text-4xl">
                                    {days}
                                 </div>
                                 <div className="mt-1 text-xs font-semibold uppercase tracking-wider text-white/70 sm:text-sm">
                                    <Translate id="web:days" />
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>

                     {/* Separator */}
                     <div className="my-auto bg-gradient-to-b from-[#4E442D] to-gold-primary bg-clip-text text-xl font-bold text-transparent sm:text-2xl md:text-3xl">
                        :
                     </div>

                     {/* Hours */}
                     <div className="relative">
                        <div className="relative rounded-xl border border-white/10 bg-gradient-to-br from-white/5 to-white/0 p-3 shadow-lg backdrop-blur-sm sm:p-4">
                           <div className="absolute inset-0 rounded-xl bg-gradient-to-br from-[#4E442D]/10 to-gold-primary/5 opacity-50"></div>
                           <div className="relative">
                              <div className="text-center">
                                 <div className="bg-gradient-to-r from-[#4E442D] to-gold-primary bg-clip-text text-2xl font-black leading-tight text-transparent sm:text-3xl md:text-4xl">
                                    {hours}
                                 </div>
                                 <div className="mt-1 text-xs font-semibold uppercase tracking-wider text-white/70 sm:text-sm">
                                    <Translate id="web:hours" />
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>

                     {/* Separator */}
                     <div className="my-auto bg-gradient-to-b from-[#4E442D] to-gold-primary bg-clip-text text-xl font-bold text-transparent sm:text-2xl md:text-3xl">
                        :
                     </div>

                     {/* Minutes */}
                     <div className="relative">
                        <div className="relative rounded-xl border border-white/10 bg-gradient-to-br from-white/5 to-white/0 p-3 shadow-lg backdrop-blur-sm sm:p-4">
                           <div className="absolute inset-0 rounded-xl bg-gradient-to-br from-[#4E442D]/10 to-gold-primary/5 opacity-50"></div>
                           <div className="relative">
                              <div className="text-center">
                                 <div className="bg-gradient-to-r from-[#4E442D] to-gold-primary bg-clip-text text-2xl font-black leading-tight text-transparent sm:text-3xl md:text-4xl">
                                    {minutes}
                                 </div>
                                 <div className="mt-1 text-xs font-semibold uppercase tracking-wider text-white/70 sm:text-sm">
                                    <Translate id="web:minutes" />
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>

                     {/* Separator */}
                     <div className="my-auto bg-gradient-to-b from-[#4E442D] to-gold-primary bg-clip-text text-xl font-bold text-transparent sm:text-2xl md:text-3xl">
                        :
                     </div>

                     {/* Seconds */}
                     <div className="relative">
                        <div className="relative rounded-xl border border-white/10 bg-gradient-to-br from-white/5 to-white/0 p-3 shadow-lg backdrop-blur-sm sm:p-4">
                           <div className="absolute inset-0 rounded-xl bg-gradient-to-br from-[#4E442D]/10 to-gold-primary/5 opacity-50"></div>
                           <div className="relative">
                              <div className="text-center">
                                 <div className="bg-gradient-to-r from-[#4E442D] to-gold-primary bg-clip-text text-2xl font-black leading-tight text-transparent sm:text-3xl md:text-4xl">
                                    {seconds}
                                 </div>
                                 <div className="mt-1 text-xs font-semibold uppercase tracking-wider text-white/70 sm:text-sm">
                                    <Translate id="web:seconds" />
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
               </React.Fragment>
            )}
         </div>
      </div>
   );
};

export default memo(Timer);
