import { Translate, useTranslate } from '~/i18n';

import { FacebookIcon, LinkedinIcon, TwitterIcon } from 'next-share';
// import { Icon } from '@iconify/react';
import classNames from 'classnames';
// import Modal from '../shared/modals';
import React, { useEffect, useState } from 'react';
import styles from './styles/sharebtn-sections.module.css';
import Axios from '~/utils/axios';
import Cookies from 'js-cookie';
// import toast from 'react-hot-toast';
// import ThreeDotsWave from '../animation/three-dots-wave';
// import { useRouter } from 'next/router';
// import { fromBuffer } from 'pdf2pic';
// import { pdfToPng } from 'pdf-to-png-converter';
// import { GuestType } from '~/interfaces/guest';

// import { CopyToClipboard } from 'react-copy-to-clipboard';

// import { encodeURL } from 'js-base64';
/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/
type ShareSectionsProps = {
   token: string;
   shareTextEn: string | null;
   shareTextAr: string | null;
};
const ShareSections = ({ token, shareTextEn, shareTextAr }: ShareSectionsProps) => {
   Cookies.remove('user_data');
   Cookies.remove('reg_num');

   function toHtml(text: string | null) {
      // textarea -> HTML version (for your modal with <br/>)
      return (text || '').trim().replace(/\n/g, '<br/>');
   }
   function toPlain(text: string | null) {
      // textarea -> plain text (for native share, copy-to-clipboard, X, etc.)
      return (text || '').trim(); // keeps \n\n as-is
   }
   // 👉 These are the four values you asked about:
   const data_en = toHtml(shareTextEn);
   const data_ar = toHtml(shareTextAr);
   const dataShare_en = toPlain(shareTextEn); // with \n\n for copy/share
   const dataShare_ar = toPlain(shareTextAr);
   const [copied, setCopied] = useState(false);
   const { lang } = useTranslate();
   // const [pdfData, setPdfData] = useState('');
   const [poster, setPoster] = useState('');
   const [loading, setLoading] = useState(false);
   // const [category, setCategory] = useState('');

   const [loading2, setLoading2] = useState(false);
   // const [retryCount, setRetryCount] = useState(0);

   // const [linkedInAccessToken, setLinkedInAccessToken] = useState('');
   // const [postLoading, setPostLoading] = useState(false);

   const shareText = lang === 'en' ? dataShare_en : dataShare_ar; // Use the appropriate share text
   // const shareUrl = 'https://csr-forum.com'; // The URL to share
   // const posterUrl = `https://csr.eu-central-1.linodeobjects.com/social_card.png`; // The poster URL

   const test = () => {
      navigator.clipboard.writeText(lang === 'en' ? dataShare_en : dataShare_ar);
      if (copied) {
         return;
      }
      setCopied(true);
      setTimeout(() => {
         setCopied(false);
      }, 500);
   };

   useEffect(() => {
      let interval: any;

      const fetchData = async () => {
         // const regId = JSON.parse(Cookies.get('reg_num') || 'null');
         if (loading) return;

         setLoading(true);

         try {
            const response = await Axios.get(`/get-social-card/${token}?lang=${lang}`);

            if (response.data.status === 'success') {
               setPoster(response.data.poster);
               setLoading(false);
               clearInterval(interval); // Stop polling
            } else {
               console.log('Poster still processing...');
            }
         } catch (error: any) {
            console.log('Error fetching social card:', error?.response?.data || error.message);
         }
      };

      if (poster === '') {
         interval = setInterval(fetchData, 3000); // Poll every 3 seconds
         fetchData(); // Fetch immediately
      }

      return () => clearInterval(interval); // Cleanup on unmount
   }, [lang, poster, token, loading]);
   // const handleShare = (platform: any) => {
   //    let shareLink = '';
   //    switch (platform) {
   //       case 'twitter':
   //          shareLink = `https://twitter.com/intent/tweet?text=${encodeURIComponent(
   //             shareText
   //          )}&url=${encodeURIComponent(shareUrl)}&image=${encodeURIComponent(posterUrl)}`;
   //          break;
   //       case 'linkedin':
   //          shareLink = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(
   //             shareUrl
   //          )}&title=${encodeURIComponent(shareText)}&summary=${encodeURIComponent(
   //             shareText
   //          )}&source=${encodeURIComponent(shareUrl)}`;
   //          break;
   //       case 'facebook':
   //          shareLink = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(
   //             shareUrl
   //          )}&quote=${encodeURIComponent(shareText)}&picture=${encodeURIComponent(posterUrl)}`;
   //          break;
   //       default:
   //          break;
   //    }
   //    window.open(shareLink, '_blank');
   // };

   // const [authUrl, setAuthUrl] = useState('');
   // const router = useRouter();

   // useEffect(() => {
   //    const fetchData = async () => {
   //       try {
   //          if (loading) return;

   //          setLoading(true);
   //          const response = await Axios.get(
   //             `linkedin/auth-url?lang=${lang}&redirect_to=${window.location.href}`
   //          );
   //          setAuthUrl(response.data.url);
   //          Cookies.remove('success_page_url');
   //          Cookies.set('success_page_url', `/join/${router.query.category}/success`);

   //          setLoading(false);
   //       } catch (error: any) {
   //          console.log(error.response);
   //       }
   //    };

   //    fetchData();
   // }, [lang]);

   // useEffect(() => {
   //    const accessToken = Cookies.get('linkedin_access_token');
   //    if (accessToken) {
   //       setLinkedInAccessToken(accessToken);
   //    }
   // }, []);

   const startDownload = async () => {
      // const regId = JSON.parse(Cookies.get('reg_num') || '');

      try {
         if (loading2) return;
         setLoading2(true);
         const response = await Axios({
            url: `/get-social-card-img/${token}?lang=${lang}`,
            method: 'get',
            responseType: 'blob',
            // headers: {
            //    Authorization: `Bearer ${token}`,
            // },
         });
         const url = window.URL.createObjectURL(new Blob([response.data]));
         const link = document.createElement('a');
         link.href = url;
         // console.log(getExtension(response.data.type), 'getExtension(response.data.type)');

         link.setAttribute('download', `social_media_card.png`);
         document.body.appendChild(link);
         link.click();
         setLoading2(false);
      } catch (error: any) {
         console.log(error.response);
      }
   };

   const handleShare = (platform: any) => {
      let shareLink = '';
      switch (platform) {
         case 'twitter':
            shareLink = `https://twitter.com/intent/tweet?text=${encodeURIComponent(shareText)}`;
            window.open(shareLink, '_blank');
            break;
         case 'linkedin':
            shareLink = 'https://www.linkedin.com/feed/?shareActive=true';
            window.open(shareLink, '_blank');

            break;
         case 'facebook':
            shareLink = `https://www.facebook.com`;
            window.open(shareLink, '_blank');
            break;
         default:
            break;
      }
   };

   // const postToLinkedIn = async (linkedInAccessToken: string) => {
   //    setPostLoading(true);
   //    try {
   //       // if (!linkedInAccessToken) {
   //       //    toast.error('Authentication required. Please login with LinkedIn first.');
   //       //    return;
   //       // }

   //       const response = await Axios.post('linkedin/post', {
   //          accessToken: linkedInAccessToken,
   //          registration_nubmer: token,
   //          // message: 'Excited to be part of this event! #Networking',
   //       });

   //       if (response.data.status === 'success') {
   //          toast.success('Post shared successfully! ,Please check your LinkedIn account.');
   //          console.log('Post Successful', response.data.post);
   //       } else {
   //          toast.error('Failed to share post.');
   //          console.error('Post Error:', response.data.message);
   //       }
   //    } catch (error) {
   //       console.error('Post Error:', error);
   //       toast.error('An error occurred while sharing the post.');
   //    }
   //    setPostLoading(false);
   // };
   return (
      <React.Fragment>
         <div className="container">
            <div className="row justify-center">
               <div className="md:col-6">
                  <div className="relative rounded-lg border bg-white p-4 shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)] sm:px-10 sm:py-6">
                     <div>
                        <div className="text-xl font-bold">
                           <Translate id="web:step1_copy_content" />
                        </div>
                        <div className={classNames(styles['dashedBorder'], 'relative my-4 p-5')}>
                           <div
                              className="break-words"
                              dangerouslySetInnerHTML={{
                                 __html: lang === 'en' ? data_en : data_ar,
                              }}
                           />
                           {/* <CopyToClipboard text={msg} onCopy={() => setCopiedFunc()}> */}
                           <button
                              onClick={() => test()}
                              className="absolute bottom-3 z-10 w-[80px] bg-primary px-2 text-white transition-colors duration-150 hover:bg-primary-600 ltr:right-4 rtl:left-4 ">
                              {copied ? <Translate id="web:done" /> : <Translate id="web:copy" />}
                           </button>
                           {/* </CopyToClipboard> */}
                        </div>

                        <React.Fragment>
                           <div className={classNames(styles['dashedBorder'], 'relative my-4 p-5')}>
                              <div>
                                 {loading ? (
                                    <p>
                                       <Translate id="web:loading_img" />
                                    </p>
                                 ) : (
                                    <div>{poster && <img src={poster} alt="poster" />}</div>
                                 )}
                              </div>
                              {/* download btn */}
                              {poster && (
                                 <div className="ltr:text-right rtl:text-left">
                                    <button
                                       onClick={() => {
                                          startDownload();
                                       }}
                                       // target="_blank"
                                       // rel="noopener noreferrer"
                                       // href={`${process.env.NEXT_PUBLIC_STORAGE_URL}/social_card/${poster}`}
                                       className="relative z-50  mt-2 bg-primary px-2 text-white transition-colors duration-150 hover:bg-primary-600">
                                       {loading2
                                          ? lang === 'ar'
                                             ? 'جاري التحميل'
                                             : 'Loading'
                                          : lang === 'ar'
                                          ? 'تحميل'
                                          : 'Download'}
                                    </button>
                                 </div>
                              )}
                           </div>
                        </React.Fragment>

                        <div className="text-xl font-bold">
                           <Translate id="web:step2_share_in_your_favorite_social_platforms" />
                        </div>
                     </div>

                     <div className="mt-4 flex justify-center space-x-6 rtl:space-x-reverse">
                        {/* {linkedInAccessToken ? (
                           <button
                              disabled={postLoading}
                              onClick={() => postToLinkedIn(linkedInAccessToken)}
                              className="flex items-center justify-center space-x-2 rounded-md border border-gray-300 bg-white p-1 px-2 hover:bg-gray-100 rtl:space-x-reverse">
                              {postLoading ? (
                                 <React.Fragment>
                                    <div>{'Loading'}</div>
                                    <div className="w-8">{<ThreeDotsWave color="black" />}</div>
                                 </React.Fragment>
                              ) : (
                                 <React.Fragment>
                                    <div className="font-bold">
                                       {lang === 'en' ? 'Share' : 'مشاركة'}
                                    </div>
                                    <div>
                                       <LinkedinIcon size={35} round />
                                    </div>
                                 </React.Fragment>
                              )}
                           </button>
                        ) : (
                           <button
                              onClick={() => handleShare('linkedin')}
                              className="flex items-center justify-center space-x-2 rounded-md border border-gray-300 bg-white p-1 px-2 hover:bg-gray-100 rtl:space-x-reverse">
                              <div className="font-bold">
                                 {lang === 'en' ? 'Login' : 'تسجيل الدخول'}
                              </div>
                              <div>
                                 <LinkedinIcon size={35} round />
                              </div>
                           </button>
                        )} */}
                        <button
                           onClick={() => handleShare('linkedin')}
                           className="flex items-center justify-center space-x-2 rounded-md border border-gray-300 bg-white p-1 px-2 hover:bg-gray-100 rtl:space-x-reverse">
                           <React.Fragment>
                              {/* <div className="font-bold">{lang === 'en' ? 'Share' : 'مشاركة'}</div> */}
                              <div>
                                 <LinkedinIcon size={35} round />
                              </div>
                           </React.Fragment>
                        </button>
                        <button
                           onClick={() => handleShare('twitter')}
                           className="flex items-center justify-center rounded-md border border-gray-300 bg-white p-1 px-2 hover:bg-gray-100">
                           <TwitterIcon size={35} round />
                        </button>
                        {/* <button
                           onClick={() => handleShare('instagram')}
                           className="flex items-center justify-center rounded-md border border-gray-300 bg-white p-1 px-2 hover:bg-gray-100">
                           <InstagramIcon size={35} round />
                        </button> */}
                        <button
                           onClick={() => handleShare('facebook')}
                           className="flex items-center justify-center rounded-md border border-gray-300 bg-white p-1 px-2 hover:bg-gray-100">
                           <FacebookIcon size={35} round />
                        </button>
                        {/* <button
                           onClick={() => handleShare('tiktok')}
                           className="flex items-center justify-center  rounded-md border border-gray-300 bg-white p-1 px-2 px-3 hover:bg-gray-100">
                           <Icon
                              onClick={() => handleShare('tiktok')}
                              icon="bi:tiktok"
                              className={classNames('  h-8  w-8    cursor-pointer  ')}
                           />
                        </button>
                        <button
                           onClick={() => handleShare('whatsapp')}
                           className="flex items-center justify-center rounded-md border border-gray-300 bg-white p-1 px-2 hover:bg-gray-100">
                           <WhatsappIcon size={35} round />
                        </button> */}
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </React.Fragment>
   );
};

export default ShareSections;
