import classNames from 'classnames';
import { memo, Ref } from 'react';
import Select, { Props, StylesConfig } from 'react-select';
import { useTranslate } from '~/i18n';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

interface UISelectProps extends Props {
   innerRef?: Ref<any>;
   error?: React.ReactNode;
   valid?: React.ReactNode;
   groupClassName?: string;
}

const baseGray = '#7F8694';
const basePrimary = '#685BC7';
const baseWhite = '#ffffff';
const baseError = '#FF0848';
const baseBlack = '#000000';

const colors = {
   main: baseGray,
   secondary: basePrimary,
   error: baseError,
   border: baseGray,
   OptBg: baseWhite,
   isFocusedBg: basePrimary,
   isFocusedColor: baseWhite,
   selectedBg: basePrimary,
   selectedColor: baseWhite,
   disabled: '#f2f2f2',
   boxShadowIsError: '0 0 0 3px #ef434380',
   boxShadowIsFocused: '0 0 0 3px #FCC89B80',
   valSelected: baseBlack,
};

const UISelect: React.FC<UISelectProps> = ({
   id,
   innerRef,
   valid,
   error,
   styles,
   groupClassName,
   ...rest
}) => {
   const { translate } = useTranslate();

   const selectStyles: StylesConfig = {
      ...styles,
      option: (base, state) => ({
         ...base,
         color: state.isSelected ? colors.isFocusedColor : colors.main,
         backgroundColor: state.isSelected || state.isFocused ? colors.selectedBg : colors.OptBg,
         '&:hover': {
            backgroundColor: colors.selectedBg,
            color: colors.isFocusedColor,
         },
         fontSize: '16px',
      }),
      control: (base, state) => ({
         ...base,
         color: colors.main,
         backgroundColor: state.isDisabled ? colors.disabled : 'transparent',
         cursor: state.isDisabled ? 'not-allowed' : 'default',
         pointerEvents: state.isDisabled ? 'auto' : undefined,
         borderRadius: '12px',
         padding: 2,
         borderColor: error ? colors.error : colors.border,
         '&:hover': {
            borderColor: error ? colors.error : state.isFocused ? '#F4C8A0' : colors.border,
         },
         boxShadow: state.isFocused
            ? error
               ? colors.boxShadowIsError
               : colors.boxShadowIsFocused
            : 'none',
         outlineOffset: state.isFocused ? '2px' : '0px',
      }),
      dropdownIndicator: base => ({
         ...base,
         color: colors.main,
         '&:hover': {
            color: colors.main,
         },
      }),
      placeholder: base => ({
         ...base,
         color: colors.main,
         fontSize: '16px',
         fontWeight: 500,
      }),
      indicatorSeparator: base => ({
         ...base,
         backgroundColor: colors.main,
      }),
      valueContainer: base => ({
         ...base,
         color: colors.main,
      }),
      menu: base => ({
         ...base,
         marginTop: '7px',
         // overflow: 'hidden',
         borderRadius: 0,
         backgroundColor: colors.main,
         zIndex: 99,
         border: `1px solid ${colors.main}`,
      }),
      menuList: base => ({
         ...base,
         padding: 0,
         borderRadius: 0,
         // overflow: 'hidden',
         backgroundColor: colors.main,
         '::-webkit-scrollbar': {
            width: '4px',
            height: '0px',
         },
         '::-webkit-scrollbar-track': {
            background: '#f1f1f1',
         },
         '::-webkit-scrollbar-thumb': {
            background: colors.main,
         },
         '::-webkit-scrollbar-thumb:hover': {
            background: colors.main,
         },
      }),
      singleValue: base => ({
         ...base,
         color: colors.valSelected,
         fontSize: '16px',
         fontWeight: 500,
      }),
      input: base => ({
         ...base,
         color: colors.main,
         fontSize: '16px',
      }),
   };

   return (
      <div className={classNames(groupClassName || 'relative mb-5 w-full pb-1')}>
         <Select
            className="react-select"
            inputId={id}
            instanceId={id}
            styles={selectStyles}
            noOptionsMessage={({ inputValue }) =>
               `${translate({ id: 'common:no_results' })} ${inputValue}`
            }
            ref={innerRef}
            isSearchable
            {...rest}
         />
         {valid && !error && typeof valid !== 'boolean' && (
            <div className="text-xs text-primary">{valid}</div>
         )}
         {error && typeof error !== 'boolean' && (
            <div className="absolute text-xs text-error" role="alert">
               {error}
            </div>
         )}
      </div>
   );
};

export default memo(UISelect);
