import { NextLink, Translate } from '~/i18n';

import Lottie from 'react-lottie';
import TicAnimations from '~/animations/tic_new.json';
import Cookies from 'js-cookie';
import classNames from 'classnames';
// import classNames from 'classnames';
import ShareBtnSections from './sharebtn-sections';
// import Cookies from 'js-cookie';
// import { nanoid } from 'nanoid';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type SuccessSectionsProps = {
   // category: string;
   visibility?: 'private' | 'public';
   // withToken: boolean;
   withShare?: boolean;
   shareTextEn: string | null;
   shareTextAr: string | null;
   showInSuccessPage: boolean;
};

const SuccessSections = ({
   // visibility,
   withShare,
   shareTextEn,
   shareTextAr,
   showInSuccessPage,
}: SuccessSectionsProps) => {
   Cookies.remove('user_data');
   const regId = Cookies.get('reg_num');
   // console.log(token, 'token');

   return (
      <section>
         <div className="container mb-10 py-5">
            <div className="row">
               <div className="lg:col-6 lg:offset-3">
                  <div className="rounded-xl border border-white/50   shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)]">
                     <div className="p-6 sm:p-12">
                        <div className="text-center">
                           <div className="lottie-fix mx-auto h-60 w-60 cursor-default ">
                              <Lottie
                                 options={{
                                    animationData: TicAnimations,
                                    autoplay: true,
                                    loop: false,
                                 }}
                              />
                           </div>
                           <div className="relative z-10">
                              <h1
                                 className={classNames(
                                    'text-3xl font-bold text-gray-800 md:text-4xl',
                                    'from-[#4E442D] to-gold-primary bg-clip-text text-transparent ltr:bg-gradient-to-r rtl:bg-gradient-to-l'
                                 )}>
                                 <Translate id="web:thank_you" />
                              </h1>
                              {/* {visibility === 'private' ? (
                                 <p className="mt-2 text-black">
                                    <Translate id="web:thank_you_private" />
                                 </p>
                              ) : (
                                 <p className="mt-2 text-black">
                                    <Translate id="web:thank_you_public" />
                                 </p>
                              )} */}

                              <div className="my-3 text-white">
                                 <Translate id="web:thank_you_private" />
                              </div>

                              <div
                                 className={classNames(
                                    ' font-bold text-gray-800  ',
                                    'from-[#4E442D] to-gold-primary bg-clip-text text-transparent ltr:bg-gradient-to-r rtl:bg-gradient-to-l'
                                 )}>
                                 <Translate id="web:registration_number" />
                              </div>
                              <div className="text-white">{regId}</div>
                              <div className="mt-8 text-center">
                                 <div className="row justify-center">
                                    <div className="md:col-6">
                                       <NextLink
                                          href="/"
                                          className={classNames(
                                             'block w-full border-none border-transparent px-4 py-3 text-center text-sm font-bold leading-5 text-white',

                                             // 'disabled:cursor-not-allowed disabled:opacity-50',
                                             'bg-primary hover:bg-primary-600',
                                             // 'bg-gradient-to-r from-[#C3FF42] via-[#27CBC0] to-[#0077C0]',
                                             'focus:outline-none focus:ring focus:ring-primary focus:ring-opacity-50',
                                             'transition-all duration-150',
                                             'rounded-xl',
                                             'bg-gradient-to-r from-[#4E442D] to-gold-primary',

                                             'rounded-xl'
                                          )}>
                                          <Translate id="web:back_to_homepage" />
                                       </NextLink>
                                    </div>
                                 </div>
                              </div>
                              {withShare && showInSuccessPage && (
                                 <div className="mt-8">
                                    <hr />
                                    {regId && (
                                       <ShareBtnSections
                                          shareTextEn={shareTextEn}
                                          shareTextAr={shareTextAr}
                                          regId={regId}
                                       />
                                    )}
                                 </div>
                              )}
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
   );
};

export default SuccessSections;
