import { Translate } from '~/i18n';
// import { motion } from 'framer-motion';
import React from 'react';
// import CheckInvitationForm from '../join/check-invitation-form';
import Cookies from 'js-cookie';
// import Image from '../shared/image';
import classNames from 'classnames';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const RegisterClosed = () => {
   // const { translate } = useTranslate();
   Cookies.remove('user_data');

   return (
      <section>
         <div className="container py-20">
            <div className="row">
               <div className="col-12 relative text-center">
                  <h1
                     className={classNames(
                        'text-xl font-bold capitalize text-secondary md:mb-4 md:text-2xl'
                     )}>
                     <Translate id="homepage:event_name" />
                  </h1>

                  <div className="row">
                     <div className="md:col-4 md:offset-4">
                        <div className="rounded-lg border bg-white shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)]">
                           <p className={classNames('my-5 text-2xl font-black text-primary')}>
                              <Translate id="web:registration_closed" />
                           </p>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </section>
   );
};

export default RegisterClosed;
