import React, { useState, useEffect } from 'react';
import { useFormContext } from 'react-hook-form';
import SubmitBtn from '~/components/shared/buttons/submit-btn';
import CustomInput from '~/components/shared/forms/custom-input';
import { Translate, useTranslate } from '~/i18n';
// import isUniqueAttribute from '~/utils/unique-attribute';
// import validator from 'validator';
import cookies from 'js-cookie';
import Axios from '~/utils/axios';
import toast from 'react-hot-toast';
import { GuestType } from '~/interfaces/guest';
import classNames from 'classnames';
import CustomRadioInput from '~/components/shared/forms/custom-radio-input';
// import { CountryType } from '~/interfaces/country';
import BackBtn from '~/components/shared/buttons/back-btn';
import { useGoogleReCaptcha } from 'react-google-recaptcha-v3';
import CustomDayInput from '~/components/shared/forms/custom-day-input';
import { getUnixTime, getYear } from 'date-fns';
import { zonedTimeToUtc } from 'date-fns-tz';
import { CalendarIcon } from '@heroicons/react/24/outline';
import styles from './styles/personal-info-2.module.css';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type AccommodationInfoProps = {
   onNextClick: () => any;
   onBackClick: () => any;
   step: string | undefined;
   role?: string;
   token?: string;
   withToken: boolean;
};

const AccommodationInfo = ({
   onNextClick,
   onBackClick,
   step,
   token,
   role,
}: AccommodationInfoProps) => {
   const { translate, lang } = useTranslate();
   const [loading, setLoading] = useState(false);

   const {
      handleSubmit,
      getValues,
      setValue,
      watch,
      register,
      formState: { errors },
   } = useFormContext<GuestType>();
   const { executeRecaptcha } = useGoogleReCaptcha();

   // Reset require_transfer when step-4 loads to avoid carrying over value from step-3
   useEffect(() => {
      if (step === 'accommodation-info') {
         setValue('require_transfer', null, { shouldValidate: false });
      }
   }, [step, setValue]);

   // values: FormData
   const submitForm = async (values: GuestType) => {
      if (loading) {
         return;
      }
      setLoading(true);
      const recaptcha = await executeRecaptcha?.();

      try {
         const data = {
            ...values,
            code: token,
            category: role,
            email: values?.email?.toLowerCase(),
            recaptcha,
         };

         delete data.personal_image_url;
         delete data.document_copy_url;
         delete data.visa_copy_url;

         if (data.is_saudi === 'yes') {
            delete data.birth_city;
            delete data.issue_date;
            delete data.issue_place;
            delete data.visa_copy;
            delete data.residency_status;
            delete data.valid_visa;
         }
         const response = await Axios.post(`guests?lang=${lang}`, data);

         cookies.set('reg_num', response.data.data);
         onNextClick();
      } catch (error: any) {
         if (error.response?.status === 404) {
            toast.error(error.response?.data?.data);
         } else if (error?.response?.status === 403) {
            toast.error(translate({ id: 'res:recaptcha_failed' }), {
               duration: 4000,
            });
         } else {
            toast.error(translate({ id: 'res:500' }));
         }
         setLoading(false);
      }
   };

   return (
      <React.Fragment>
         {step == 'accommodation-info' && (
            <div className="rounded-lg border shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)]">
               <div className="p-6 sm:p-12">
                  <h2 className=" text-xl font-bold capitalize text-primary md:mb-4 md:text-2xl">
                     <Translate id="web:accommodation-info" />
                  </h2>
                  <div className="pt-5">
                     <form
                        noValidate
                        onSubmit={handleSubmit(submitForm)}
                        className="relative"
                        autoComplete="off">
                        <div>
                           {/* require_accommodation */}
                           <CustomRadioInput
                              label={translate({ id: 'web:require_accommodation' })}
                              isRequired
                              isInline
                              options={[
                                 { value: 'yes', label: translate({ id: 'web:yes' }) },
                                 { value: 'no', label: translate({ id: 'web:no' }) },
                              ]}
                              id="require_accommodation"
                              error={errors.require_accommodation?.message}
                              {...register('require_accommodation', {
                                 required: translate({ id: 'validation:required' }),
                              })}
                           />
                           <div>
                              {watch('require_accommodation') !== null ? (
                                 watch('require_accommodation') === 'yes' ? (
                                    <div
                                       className={classNames(
                                          styles['dashedBorder'],
                                          'mb-6 px-4 py-2'
                                       )}>
                                       <p className="text-white">
                                          <Translate id="web:require_accommodation_note_yes" />
                                       </p>
                                    </div>
                                 ) : (
                                    ''
                                 )
                              ) : (
                                 ''
                              )}
                           </div>
                           {watch('require_accommodation') !== null ? (
                              watch('require_accommodation') === 'yes' ? (
                                 <React.Fragment>
                                    {/* check_in_date */}
                                    <CustomDayInput
                                       label={translate({
                                          id: 'web:check_in_date',
                                       })}
                                       type="text"
                                       placeHolder={translate({
                                          id: 'web:check_in_date',
                                       })}
                                       id="check_in_date"
                                       isInline
                                       isRequired={getValues('require_accommodation') === 'yes'}
                                       fromYear={getYear(new Date())}
                                       toYear={getYear(new Date()) + 1}
                                       fromMonth={new Date(2026, 3, 1)}
                                       {...register('check_in_date', {
                                          required:
                                             getValues('require_accommodation') === 'yes'
                                                ? translate({
                                                     id: 'validation:required',
                                                  })
                                                : false,
                                       })}
                                       append={
                                          <span className="block border-gray-500 px-2 text-gray-500 ltr:border-l rtl:border-r">
                                             <CalendarIcon className="h-4 w-4" />
                                          </span>
                                       }
                                       value={getValues('check_in_date')}
                                       error={errors.check_in_date?.message}
                                       callBack={(item: Date) => {
                                          const timestamp = getUnixTime(item);
                                          const saudiArabiaTimestamp =
                                             zonedTimeToUtc(
                                                timestamp * 1000,
                                                'Asia/Riyadh'
                                             ).getTime() / 1000;
                                          setValue(
                                             'check_in_date',
                                             saudiArabiaTimestamp.toString(),
                                             {
                                                shouldValidate: true,
                                             }
                                          );
                                       }}
                                    />
                                    {/* check_out_date */}
                                    <CustomDayInput
                                       label={translate({
                                          id: 'web:check_out_date',
                                       })}
                                       type="text"
                                       placeHolder={translate({
                                          id: 'web:check_out_date',
                                       })}
                                       id="check_out_date"
                                       isInline
                                       isRequired={getValues('require_accommodation') === 'yes'}
                                       fromYear={getYear(new Date())}
                                       toYear={getYear(new Date()) + 1}
                                       fromMonth={new Date(2026, 3, 1)}
                                       {...register('check_out_date', {
                                          required:
                                             getValues('require_accommodation') === 'yes'
                                                ? translate({
                                                     id: 'validation:required',
                                                  })
                                                : false,
                                       })}
                                       append={
                                          <span className="block border-gray-500 px-2 text-gray-500 ltr:border-l rtl:border-r">
                                             <CalendarIcon className="h-4 w-4" />
                                          </span>
                                       }
                                       value={getValues('check_out_date')}
                                       error={errors.check_out_date?.message}
                                       callBack={(item: Date) => {
                                          const timestamp = getUnixTime(item);
                                          const saudiArabiaTimestamp =
                                             zonedTimeToUtc(
                                                timestamp * 1000,
                                                'Asia/Riyadh'
                                             ).getTime() / 1000;
                                          setValue(
                                             'check_out_date',
                                             saudiArabiaTimestamp.toString(),
                                             {
                                                shouldValidate: true,
                                             }
                                          );
                                       }}
                                    />
                                    {/* special_requests */}
                                    <CustomInput
                                       label={translate({ id: 'web:special_requests' })}
                                       type="textarea"
                                       rows={3}
                                       isInline
                                       autoComplete="off"
                                       placeHolder={translate({
                                          id: 'web:special_requests',
                                       })}
                                       id="special_requests"
                                       error={errors.special_requests?.message}
                                       {...register('special_requests', {
                                          required: false,
                                          maxLength: {
                                             value: 500,
                                             message: translate({
                                                id: 'validation:you_reached_the_text_limit',
                                             }),
                                          },
                                       })}
                                    />
                                    {/* dietary_requirements */}
                                    <CustomInput
                                       label={translate({
                                          id: 'web:dietary_requirements',
                                       })}
                                       type="textarea"
                                       rows={3}
                                       isInline
                                       autoComplete="off"
                                       placeHolder={translate({
                                          id: 'web:dietary_requirements',
                                       })}
                                       id="dietary_requirements"
                                       error={errors.dietary_requirements?.message}
                                       {...register('dietary_requirements', {
                                          required: false,
                                          maxLength: {
                                             value: 500,
                                             message: translate({
                                                id: 'validation:you_reached_the_text_limit',
                                             }),
                                          },
                                       })}
                                    />
                                 </React.Fragment>
                              ) : (
                                 ''
                              )
                           ) : (
                              ''
                           )}
                           <hr className="my-7 border-white/50" />

                           <h2 className=" text-xl font-bold capitalize text-primary md:mb-4 md:text-2xl">
                              <Translate id="web:transportation" />
                           </h2>
                           <p className="text-white">
                              <Translate id="web:transportation_note" />
                           </p>
                           <div className="mt-4">
                              {/* require_transfer */}
                              <CustomRadioInput
                                 label={translate({ id: 'web:require_transfer' })}
                                 isRequired
                                 isInline
                                 options={[
                                    { value: 'yes', label: translate({ id: 'web:yes' }) },
                                    { value: 'no', label: translate({ id: 'web:no' }) },
                                 ]}
                                 id="require_transfer"
                                 error={errors.require_transfer?.message}
                                 {...register('require_transfer', {
                                    required: translate({ id: 'validation:required' }),
                                 })}
                              />
                           </div>
                        </div>
                        <div className="mt-10">
                           <div className="row">
                              <div className="col-6 sm:col-3 sm:offset-3">
                                 <BackBtn
                                    id="back-btn" //* for test cases
                                    callBack={() => {
                                       onBackClick();
                                    }}
                                    text={`${translate({ id: `web:back` })}`}
                                 />
                              </div>
                              <div className="col-6 sm:col-3">
                                 <SubmitBtn
                                    id="submit-btn" //* for test cases
                                    loading={loading}
                                    text={`${translate({ id: `web:submit` })}`}
                                 />
                              </div>
                           </div>
                        </div>
                     </form>
                  </div>
               </div>
            </div>
         )}
      </React.Fragment>
   );
};

export default AccommodationInfo;
