import React, { useEffect } from 'react';
import { useFormContext } from 'react-hook-form';
import SubmitBtn from '~/components/shared/buttons/submit-btn';
import cookie from 'js-cookie';
import { Translate, useTranslate } from '~/i18n';
import toast from 'react-hot-toast';
import { GuestType } from '~/interfaces/guest';
import classNames from 'classnames';
import CustomInput from '~/components/shared/forms/custom-input';
import CustomRadioInput from '~/components/shared/forms/custom-radio-input';
import CustomDayInput from '~/components/shared/forms/custom-day-input';
import { CalendarIcon } from '@heroicons/react/24/outline';
import { getUnixTime, getYear } from 'date-fns';
import BackBtn from '~/components/shared/buttons/back-btn';
import { zonedTimeToUtc } from 'date-fns-tz';
import styles from './styles/personal-info-2.module.css';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

type FlightsInfoProps = {
   onNextClick: () => any;
   onBackClick: () => any;
   onUpdateClick: () => any;
   step: string | undefined;
   nextStep: string;
   role?: string;
   mandatoryFields?: string[];
};

const FlightsInfo = ({ onNextClick, step, onBackClick, nextStep }: FlightsInfoProps) => {
   const { translate } = useTranslate();

   const {
      handleSubmit,
      watch,
      register,
      setValue,
      getValues,
      formState: { errors },
   } = useFormContext<GuestType>();

   const submitForm = async (values: GuestType) => {
      try {
         const updatedUserObj = {
            ...values,
            step: nextStep,
         };
         cookie.set('user_data', JSON.stringify(updatedUserObj), {
            secure: true, // Ensures the cookie is secure in production
            sameSite: 'Strict', // Prevents cross-site request forgery
         });
         onNextClick();

         toast.success(translate({ id: 'res:info_saved' }));
      } catch (error: any) {
         console.log(error, 'error');
      }
   };

   useEffect(() => {
      setValue('destination_to', translate({ id: 'web:riyadh' }));
      setValue('departure_city_from', translate({ id: 'web:riyadh' }));
   }, [translate, setValue]);

   return (
      <React.Fragment>
         {step === 'flights-info' ? (
            <div className="rounded-lg border shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)]">
               <div className="p-6 sm:p-12">
                  <div className=" text-xl font-bold capitalize text-primary md:mb-4 md:text-2xl">
                     <Translate id="web:flights-info" />
                  </div>
                  <div className="pt-5">
                     <form
                        noValidate
                        onSubmit={handleSubmit(submitForm)}
                        className="relative"
                        autoComplete="off">
                        <div>
                           {/* require_flights */}
                           <CustomRadioInput
                              label={translate({ id: 'web:require_flights' })}
                              isRequired={true}
                              isInline
                              options={[
                                 { value: 'yes', label: translate({ id: 'web:yes' }) },
                                 { value: 'no', label: translate({ id: 'web:no' }) },
                              ]}
                              id="require_flights"
                              error={errors.require_flights?.message}
                              {...register('require_flights', {
                                 required: translate({ id: 'validation:required' }),
                              })}
                           />
                           <h2 className="mt-4 text-xl font-bold capitalize text-white md:mb-4 md:text-2xl">
                              <Translate id="web:transportation" />
                           </h2>
                           <p className="text-white">
                              <Translate id="web:transportation_note" />
                           </p>
                           {/* require_transfer */}
                           <div className="mt-4">
                              <CustomRadioInput
                                 label={translate({ id: 'web:require_transfer' })}
                                 isRequired
                                 isInline
                                 options={[
                                    { value: 'yes', label: translate({ id: 'web:yes' }) },
                                    { value: 'no', label: translate({ id: 'web:no' }) },
                                 ]}
                                 id="require_transfer"
                                 error={errors.require_transfer?.message}
                                 {...register('require_transfer', {
                                    required: translate({ id: 'validation:required' }),
                                 })}
                              />
                           </div>
                           <div>
                              {watch('require_flights') !== null ? (
                                 watch('require_flights') === 'yes' ? (
                                    <div
                                       className={classNames(
                                          styles['dashedBorder'],
                                          'mb-6 px-4 py-2'
                                       )}>
                                       <p className="text-white">
                                          <Translate id="web:require_flights_note_yes" />
                                       </p>
                                    </div>
                                 ) : (
                                    <div>
                                       {watch('require_transfer') !== null ? (
                                          watch('require_transfer') === 'yes' ? (
                                             <div
                                                className={classNames(
                                                   styles['dashedBorder'],
                                                   'mb-6 px-4 py-2'
                                                )}>
                                                <p className="text-white">
                                                   <Translate id="web:require_transfer_note_yes" />
                                                </p>
                                             </div>
                                          ) : (
                                             ''
                                          )
                                       ) : (
                                          ''
                                       )}
                                    </div>
                                 )
                              ) : (
                                 ''
                              )}
                           </div>
                           <div>
                              {watch('require_flights') !== null ? (
                                 watch('require_flights') === 'yes' ||
                                 watch('require_flights') === 'no' ? (
                                    <React.Fragment>
                                       <h2 className="my-4  text-lg font-bold text-primary">
                                          <Translate id="web:travel_to_saudi" />
                                       </h2>
                                       {/* travel_to_saudi */}
                                       <React.Fragment>
                                          {/* departure_city_to */}
                                          <CustomInput
                                             label={translate({ id: 'web:departure_city_to' })}
                                             type="text"
                                             isRequired={getValues('require_flights') === 'yes'}
                                             isInline
                                             autoComplete="off"
                                             placeHolder={translate({
                                                id: 'web:departure_city_to',
                                             })}
                                             id="departure_city_to"
                                             error={errors.departure_city_to?.message}
                                             {...register('departure_city_to', {
                                                required:
                                                   getValues('require_flights') === 'yes'
                                                      ? translate({
                                                           id: 'validation:required',
                                                        })
                                                      : false,
                                             })}
                                          />
                                          {/* destination_to */}
                                          <CustomInput
                                             label={translate({ id: 'web:destination_to' })}
                                             type="text"
                                             isRequired={getValues('require_flights') === 'yes'}
                                             isInline
                                             readOnly
                                             autoComplete="off"
                                             placeHolder={translate({
                                                id: 'web:destination_to',
                                             })}
                                             id="destination_to"
                                             error={errors.destination_to?.message}
                                             {...register('destination_to', {
                                                required: translate({
                                                   id: 'validation:required',
                                                }),
                                             })}
                                          />

                                          {/* expected_date_of_arrival */}
                                          <CustomDayInput
                                             label={translate({
                                                id: 'web:expected_date_of_arrival',
                                             })}
                                             type="text"
                                             placeHolder={translate({
                                                id: 'web:expected_date_of_arrival',
                                             })}
                                             id="expected_date_of_arrival"
                                             isInline
                                             isRequired={getValues('require_flights') === 'yes'}
                                             fromYear={getYear(new Date())}
                                             toYear={getYear(new Date()) + 1}
                                             fromMonth={new Date()}
                                             {...register('expected_date_of_arrival', {
                                                required:
                                                   getValues('require_flights') === 'yes'
                                                      ? translate({
                                                           id: 'validation:required',
                                                        })
                                                      : false,
                                             })}
                                             append={
                                                <span className="block border-gray-500 px-2 text-gray-500 ltr:border-l rtl:border-r">
                                                   <CalendarIcon className="h-4 w-4" />
                                                </span>
                                             }
                                             value={getValues('expected_date_of_arrival')}
                                             error={errors.expected_date_of_arrival?.message}
                                             callBack={(item: Date) => {
                                                const timestamp = getUnixTime(item);
                                                const saudiArabiaTimestamp =
                                                   zonedTimeToUtc(
                                                      timestamp * 1000,
                                                      'Asia/Riyadh'
                                                   ).getTime() / 1000;
                                                setValue(
                                                   'expected_date_of_arrival',
                                                   saudiArabiaTimestamp.toString(),
                                                   {
                                                      shouldValidate: true,
                                                   }
                                                );
                                             }}
                                          />

                                          {watch('require_flights') !== null &&
                                          watch('require_transfer') !== null ? (
                                             watch('require_flights') === 'no' &&
                                             watch('require_transfer') === 'yes' ? (
                                                <React.Fragment>
                                                   {/* travel_to_saudi */}
                                                   <React.Fragment>
                                                      {/* flight_arrival_time */}
                                                      <CustomInput
                                                         label={translate({
                                                            id: 'web:flight_arrival_time',
                                                         })}
                                                         type="text"
                                                         isRequired={false}
                                                         isInline
                                                         autoComplete="off"
                                                         placeHolder={'00:00 AM'}
                                                         id="flight_arrival_time"
                                                         error={errors.flight_arrival_time?.message}
                                                         {...register('flight_arrival_time', {
                                                            required: false,
                                                            maxLength: {
                                                               value: 8,
                                                               message: translate({
                                                                  id: 'validation:you_reached_the_text_limit',
                                                               }),
                                                            },
                                                         })}
                                                      />
                                                      {/* flight_arrival_company */}
                                                      <CustomInput
                                                         label={translate({
                                                            id: 'web:flight_arrival_company',
                                                         })}
                                                         type="text"
                                                         isRequired={false}
                                                         isInline
                                                         autoComplete="off"
                                                         placeHolder={translate({
                                                            id: 'web:flight_arrival_company',
                                                         })}
                                                         id="flight_arrival_company"
                                                         error={
                                                            errors.flight_arrival_company?.message
                                                         }
                                                         {...register('flight_arrival_company', {
                                                            required: false,
                                                            maxLength: {
                                                               value: 50,
                                                               message: translate({
                                                                  id: 'validation:you_reached_the_text_limit',
                                                               }),
                                                            },
                                                         })}
                                                      />
                                                      {/* flight_arrival_number */}
                                                      <CustomInput
                                                         label={translate({
                                                            id: 'web:flight_arrival_number',
                                                         })}
                                                         type="text"
                                                         isRequired={false}
                                                         isInline
                                                         autoComplete="off"
                                                         placeHolder={translate({
                                                            id: 'web:flight_arrival_number',
                                                         })}
                                                         id="flight_arrival_number"
                                                         error={
                                                            errors.flight_arrival_number?.message
                                                         }
                                                         {...register('flight_arrival_number', {
                                                            required: false,
                                                            maxLength: {
                                                               value: 20,
                                                               message: translate({
                                                                  id: 'validation:you_reached_the_text_limit',
                                                               }),
                                                            },
                                                         })}
                                                      />
                                                   </React.Fragment>
                                                </React.Fragment>
                                             ) : (
                                                ''
                                             )
                                          ) : (
                                             ''
                                          )}
                                          {/* specific_requirements_to */}
                                          <CustomInput
                                             label={translate({
                                                id: 'web:specific_requirements_to',
                                             })}
                                             type="textarea"
                                             rows={3}
                                             isInline
                                             autoComplete="off"
                                             placeHolder={translate({
                                                id: 'web:specific_requirements_to',
                                             })}
                                             id="specific_requirements_to"
                                             error={errors.specific_requirements_to?.message}
                                             {...register('specific_requirements_to', {
                                                required: false,
                                                maxLength: {
                                                   value: 500,
                                                   message: translate({
                                                      id: 'validation:you_reached_the_text_limit',
                                                   }),
                                                },
                                             })}
                                          />
                                       </React.Fragment>
                                       <hr className="my-5 border-white/50" />
                                       <h2 className="my-4  text-lg font-bold text-primary">
                                          <Translate id="web:travel_from_saudi" />
                                       </h2>
                                       {/* travel_from_saudi */}
                                       <React.Fragment>
                                          {/* departure_city_from */}
                                          <CustomInput
                                             label={translate({ id: 'web:departure_city_from' })}
                                             type="text"
                                             isRequired={getValues('require_flights') === 'yes'}
                                             isInline
                                             readOnly
                                             autoComplete="off"
                                             placeHolder={translate({
                                                id: 'web:departure_city_from',
                                             })}
                                             id="departure_city_from"
                                             error={errors.departure_city_from?.message}
                                             {...register('departure_city_from', {
                                                required:
                                                   getValues('require_flights') === 'yes'
                                                      ? translate({
                                                           id: 'validation:required',
                                                        })
                                                      : false,
                                             })}
                                          />
                                          {/* destination_from */}
                                          <CustomInput
                                             label={translate({ id: 'web:destination_from' })}
                                             type="text"
                                             isRequired={getValues('require_flights') === 'yes'}
                                             isInline
                                             autoComplete="off"
                                             placeHolder={translate({
                                                id: 'web:destination_from',
                                             })}
                                             id="destination_from"
                                             error={errors.destination_from?.message}
                                             {...register('destination_from', {
                                                required:
                                                   getValues('require_flights') === 'yes'
                                                      ? translate({
                                                           id: 'validation:required',
                                                        })
                                                      : false,
                                             })}
                                          />

                                          {/* expected_date_of_departure */}
                                          <CustomDayInput
                                             label={translate({
                                                id: 'web:expected_date_of_departure',
                                             })}
                                             type="text"
                                             placeHolder={translate({
                                                id: 'web:expected_date_of_departure',
                                             })}
                                             id="expected_date_of_departure"
                                             isInline
                                             isRequired={getValues('require_flights') === 'yes'}
                                             fromYear={getYear(new Date())}
                                             toYear={getYear(new Date()) + 1}
                                             fromMonth={new Date()}
                                             {...register('expected_date_of_departure', {
                                                required:
                                                   getValues('require_flights') === 'yes'
                                                      ? translate({
                                                           id: 'validation:required',
                                                        })
                                                      : false,
                                             })}
                                             append={
                                                <span className="block border-gray-500 px-2 text-gray-500 ltr:border-l rtl:border-r">
                                                   <CalendarIcon className="h-4 w-4" />
                                                </span>
                                             }
                                             value={getValues('expected_date_of_departure')}
                                             error={errors.expected_date_of_departure?.message}
                                             callBack={(item: Date) => {
                                                const timestamp = getUnixTime(item);
                                                const saudiArabiaTimestamp =
                                                   zonedTimeToUtc(
                                                      timestamp * 1000,
                                                      'Asia/Riyadh'
                                                   ).getTime() / 1000;
                                                setValue(
                                                   'expected_date_of_departure',
                                                   saudiArabiaTimestamp.toString(),
                                                   {
                                                      shouldValidate: true,
                                                   }
                                                );
                                             }}
                                          />

                                          {watch('require_flights') !== null &&
                                          watch('require_transfer') !== null ? (
                                             watch('require_flights') === 'no' &&
                                             watch('require_transfer') === 'yes' ? (
                                                <React.Fragment>
                                                   {/* travel_from_saudi */}
                                                   <React.Fragment>
                                                      {/* flight_departure_time */}
                                                      <CustomInput
                                                         label={translate({
                                                            id: 'web:flight_departure_time',
                                                         })}
                                                         type="text"
                                                         isRequired={false}
                                                         isInline
                                                         autoComplete="off"
                                                         placeHolder={'00:00 AM'}
                                                         id="flight_departure_time"
                                                         error={
                                                            errors.flight_departure_time?.message
                                                         }
                                                         {...register('flight_departure_time', {
                                                            required: false,
                                                            maxLength: {
                                                               value: 8,
                                                               message: translate({
                                                                  id: 'validation:you_reached_the_text_limit',
                                                               }),
                                                            },
                                                         })}
                                                      />
                                                      {/* flight_departure_company */}
                                                      <CustomInput
                                                         label={translate({
                                                            id: 'web:flight_departure_company',
                                                         })}
                                                         type="text"
                                                         isRequired={false}
                                                         isInline
                                                         autoComplete="off"
                                                         placeHolder={translate({
                                                            id: 'web:flight_departure_company',
                                                         })}
                                                         id="flight_departure_company"
                                                         error={
                                                            errors.flight_departure_company?.message
                                                         }
                                                         {...register('flight_departure_company', {
                                                            required: false,
                                                            maxLength: {
                                                               value: 50,
                                                               message: translate({
                                                                  id: 'validation:you_reached_the_text_limit',
                                                               }),
                                                            },
                                                         })}
                                                      />
                                                      {/* flight_departure_number */}
                                                      <CustomInput
                                                         label={translate({
                                                            id: 'web:flight_departure_number',
                                                         })}
                                                         type="text"
                                                         isRequired={false}
                                                         isInline
                                                         autoComplete="off"
                                                         placeHolder={translate({
                                                            id: 'web:flight_departure_number',
                                                         })}
                                                         id="flight_departure_number"
                                                         error={
                                                            errors.flight_departure_number?.message
                                                         }
                                                         {...register('flight_departure_number', {
                                                            required: false,
                                                            maxLength: {
                                                               value: 20,
                                                               message: translate({
                                                                  id: 'validation:you_reached_the_text_limit',
                                                               }),
                                                            },
                                                         })}
                                                      />
                                                   </React.Fragment>
                                                </React.Fragment>
                                             ) : (
                                                ''
                                             )
                                          ) : (
                                             ''
                                          )}
                                          {/* specific_requirements_from */}
                                          <CustomInput
                                             label={translate({
                                                id: 'web:specific_requirements_from',
                                             })}
                                             type="textarea"
                                             rows={3}
                                             isInline
                                             autoComplete="off"
                                             placeHolder={translate({
                                                id: 'web:specific_requirements_from',
                                             })}
                                             id="specific_requirements_from"
                                             error={errors.specific_requirements_from?.message}
                                             {...register('specific_requirements_from', {
                                                required: false,
                                                maxLength: {
                                                   value: 500,
                                                   message: translate({
                                                      id: 'validation:you_reached_the_text_limit',
                                                   }),
                                                },
                                             })}
                                          />
                                       </React.Fragment>
                                       <hr className="my-5 border-white/50" />
                                       {/* comments */}
                                       <CustomInput
                                          label={translate({ id: 'web:comments' })}
                                          type="textarea"
                                          rows={5}
                                          isInline
                                          // disabled={!!user && role !== 'xrole-name'}
                                          autoComplete="off"
                                          placeHolder={translate({
                                             id: 'web:comments',
                                          })}
                                          id="comments"
                                          error={errors.comments?.message}
                                          {...register('comments', {
                                             required: false,
                                             maxLength: {
                                                value: 500,
                                                message: translate({
                                                   id: 'validation:you_reached_the_text_limit',
                                                }),
                                             },
                                          })}
                                       />
                                    </React.Fragment>
                                 ) : (
                                    ''
                                 )
                              ) : (
                                 ''
                              )}
                           </div>
                        </div>
                        <div className="mt-10">
                           <div className="row">
                              <div className="col-6 sm:col-3 sm:offset-3">
                                 <BackBtn
                                    id="back-btn" //* for test cases
                                    callBack={() => {
                                       onBackClick();
                                    }}
                                    text={`${translate({ id: `web:back` })}`}
                                 />
                              </div>
                              <div className="col-6 sm:col-3">
                                 <SubmitBtn
                                    id="submit-btn" //* for test cases
                                    text={`${translate({ id: `web:next` })}`}
                                 />
                              </div>
                           </div>
                        </div>
                     </form>
                  </div>
               </div>
            </div>
         ) : (
            ''
         )}
      </React.Fragment>
   );
};

export default FlightsInfo;
