import { useTranslate } from '~/i18n';
import classNames from 'classnames';
import { Controller, useForm } from 'react-hook-form';
// import CustomMultiSelect from '../shared/forms/custom-multi-select';
import { GuestType } from '~/interfaces/guest';
import { toast } from 'react-hot-toast';
import React, { useState } from 'react';
// import BackBtn from '../shared/buttons/back-btn';
import SubmitBtn from '../shared/buttons/submit-btn';
import { useGoogleReCaptcha } from 'react-google-recaptcha-v3';
import Axios from '~/utils/axios';
import { useRouter } from 'next/router';

import CustomInput from '../shared/forms/custom-input';
// import { CountryType } from '~/interfaces/country';
import CustomRadioInput from '../shared/forms/custom-radio-input';
import isUniqueAttribute from '~/utils/unique-attribute';
import validator from 'validator';
import PhoneInputV2 from '../shared/forms/phone-input-new';
import parsePhoneNumberFromString from 'libphonenumber-js';
import TitleSelectNew from '../shared/select/titles-select-new';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/
interface MissingDataSectionsProps {
   token: string;
   guestData: GuestType;
}

// type Item = {
//    label: string;
//    value: string;
// };
const MissingDataSections = ({ token, guestData }: MissingDataSectionsProps) => {
   const { translate, lang } = useTranslate();
   const [loading, setLoading] = useState(false);
   const router = useRouter();
   const {
      handleSubmit,
      getValues,
      control,
      setValue,
      register,
      watch,
      formState: { errors },
   } = useForm<GuestType>({
      defaultValues: {
         ...guestData,
      },
   });

   // const [countries, setCountriesList] = useState<CountryType[]>([]);

   // useEffect(() => {
   //    const fetchData = async () => {
   //       try {
   //          const response = await Axios.get(`/countries-select?lang=${lang}`);
   //          setCountriesList(response.data.data);
   //       } catch (error: any) {
   //          console.log(error.response);
   //       }
   //    };
   //    fetchData();
   // }, [lang]);

   // const [loading, setLoading] = useState('');

   const { executeRecaptcha } = useGoogleReCaptcha();
   // const [isOpen2, setIsOpen2] = useState(false);

   const submitForm = async (values: GuestType) => {
      if (loading) {
         return;
      }
      setLoading(true);
      const recaptcha = await executeRecaptcha?.();
      //test
      try {
         const data = {
            ...values,
            token: token,
            recaptcha: recaptcha,
         };

         await Axios.post(`complete-data?lang=${lang}`, data);

         toast.success(translate({ id: 'res:data_saved' }));
         router.push(`/${lang}`);
      } catch (error: any) {
         toast.error(translate({ id: 'res:500' }));
         setLoading(false);
         // console.log(error, 'erorr');
      }
      setLoading(false);
   };

   return (
      <React.Fragment>
         <div className="container relative py-10">
            <div className="row">
               <div className="lg:col-8 lg:offset-2 xl:col-8 xl:offset-2">
                  <div className="rounded-lg border bg-white shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)]">
                     <div className="p-6 sm:p-12">
                        <h2
                           className={classNames(
                              'text-xl font-bold text-gray-800 md:mb-4 md:text-2xl'
                           )}>
                           {/* todo */}
                           Required Information to Complete Your Registration
                        </h2>

                        <div className="pt-5">
                           <div className="pt-5">
                              <form
                                 noValidate
                                 onSubmit={handleSubmit(submitForm)}
                                 className="relative"
                                 autoComplete="off">
                                 {/* gender */}
                                 <CustomRadioInput
                                    label={translate({ id: 'web:gender' })}
                                    isRequired
                                    isInline
                                    options={[
                                       { value: 'male', label: translate({ id: 'web:male' }) },
                                       { value: 'female', label: translate({ id: 'web:female' }) },
                                    ]}
                                    id="gender"
                                    error={errors.gender?.message}
                                    {...register('gender', {
                                       required: translate({ id: 'validation:required' }),
                                    })}
                                 />
                                 {/* title_id */}
                                 <Controller
                                    name="title_id"
                                    control={control}
                                    render={() => (
                                       <TitleSelectNew
                                          // role={role}
                                          gender={watch('gender')}
                                          isRequired={true}
                                          selected_id={getValues()['title_id']} // on edit
                                          label={translate({ id: 'web:title' })}
                                          errors={errors.title_id?.message}
                                          callBack={(item: { value: string } | null) => {
                                             setValue('title_id', item?.value || null, {
                                                shouldValidate: true,
                                             });
                                          }}
                                       />
                                    )}
                                    rules={{
                                       required: translate({ id: 'validation:required' }),
                                    }}
                                 />

                                 {/* first_name */}
                                 <CustomInput
                                    label={translate({ id: 'web:first_name' })}
                                    type="text"
                                    isRequired
                                    isInline
                                    autoComplete="off"
                                    placeHolder={translate({ id: 'web:first_name' })}
                                    id="first_name"
                                    // disabled={  !== null}
                                    error={errors.first_name?.message}
                                    {...register('first_name', {
                                       required: translate({ id: 'validation:required' }),
                                       pattern: {
                                          value: /^[a-zA-Z0-9 -]+$/i,
                                          message: translate({
                                             id: 'validation:english_letters',
                                          }),
                                       },
                                    })}
                                 />

                                 {/* last_name */}
                                 <CustomInput
                                    label={translate({ id: 'web:last_name' })}
                                    type="text"
                                    autoComplete="off"
                                    placeHolder={translate({ id: 'web:last_name' })}
                                    id="last_name"
                                    isRequired
                                    isInline
                                    // disabled={guestLastName !== null}
                                    error={errors.last_name?.message}
                                    {...register('last_name', {
                                       required: translate({ id: 'validation:required' }),
                                       pattern: {
                                          value: /^[a-zA-Z0-9 -]+$/i,
                                          message: translate({
                                             id: 'validation:english_letters',
                                          }),
                                       },
                                    })}
                                 />

                                 {/* company */}
                                 <CustomInput
                                    label={translate({ id: 'web:company' })}
                                    type="text"
                                    autoComplete="off"
                                    // disabled={!!user && role !== 'xrole-name'}
                                    placeHolder={translate({ id: 'web:company' })}
                                    id="company"
                                    isRequired
                                    isInline
                                    error={errors.company?.message}
                                    {...register('company', {
                                       required: translate({ id: 'validation:required' }),
                                       maxLength: {
                                          value: 100,
                                          message: translate({
                                             id: 'validation:you_reached_the_text_limit',
                                          }),
                                       },
                                    })}
                                 />
                                 {/* position_id */}
                                 {/* <Controller
                           name="position_id"
                           control={control}
                           render={() => (
                              <PositionSelect
                                 // role={role}
                                 isRequired={true}
                                 selected_id={getValues()['position_id']} // on edit
                                 label={translate({ id: 'web:position' })}
                                 errors={errors.position_id?.message}
                                 callBack={(item: Item) => {
                                    setValue('position_id', item.value, {
                                       shouldValidate: true,
                                    });
                                 }}
                              />
                           )}
                           rules={{
                              required: translate({ id: 'validation:required' }),
                           }}
                        /> */}

                                 {/* job_title */}
                                 <CustomInput
                                    label={translate({ id: 'web:job_title' })}
                                    type="text"
                                    autoComplete="off"
                                    // disabled={!!user && role !== 'xrole-name'}
                                    placeHolder={translate({ id: 'web:job_title' })}
                                    id="job_title"
                                    isRequired
                                    isInline
                                    error={errors.job_title?.message}
                                    {...register('job_title', {
                                       required: translate({ id: 'validation:required' }),
                                       maxLength: {
                                          value: 100,
                                          message: translate({
                                             id: 'validation:you_reached_the_text_limit',
                                          }),
                                       },
                                    })}
                                 />
                                 {/* org_size */}
                                 {/* <div className="row">
                           <div className="self-center md:mb-5 md:col-3">
                              <Label
                                 id="org_size"
                                 isRequired={
                                    optionalFields && optionalFields.includes('org_size')
                                       ? false
                                       : true
                                 }
                                 label={translate({ id: 'web:org_size' })}
                              />
                           </div>
                           <div className="md:col-9">
                              <Controller
                                 name="org_size"
                                 control={control}
                                 render={() => (
                                    <CustomSelect
                                       value={
                                          OrganizationSizeTypeSelect.find(
                                             item => item.value === getValues()['org_size']
                                          ) || ''
                                       }
                                       placeholder={translate({
                                          id: 'web:select_org_size',
                                       })}
                                       onChange={(value: any) => {
                                          setValue('org_size', String(value?.value), {
                                             shouldValidate: true,
                                          });
                                       }}
                                       id="org_size"
                                       options={OrganizationSizeTypeSelect}
                                       error={errors.org_size?.message}
                                    />
                                 )}
                                 rules={{
                                    // required: translate({
                                    //    id: 'validation:required',
                                    // }),
                                    required:
                                       optionalFields && optionalFields.includes('org_size')
                                          ? false
                                          : translate({ id: 'validation:required' }),
                                 }}
                              />
                           </div>
                        </div> */}
                                 {/* industry */}
                                 {/* <div className="row">
                           <div className="self-center md:mb-5 md:col-3">
                              <Label
                                 id="industry"
                                 isRequired={
                                    optionalFields && optionalFields.includes('industry')
                                       ? false
                                       : true
                                 }
                                 label={translate({ id: 'web:industry' })}
                              />
                           </div>
                           <div className="md:col-9">
                              <Controller
                                 name="industry"
                                 control={control}
                                 render={() => (
                                    <CustomSelect
                                       value={
                                          IndustryTypeSelect.find(
                                             item => item.value === getValues()['industry']
                                          ) || ''
                                       }
                                       placeholder={translate({
                                          id: 'web:select_industry',
                                       })}
                                       onChange={(value: any) => {
                                          setValue('industry', String(value?.value), {
                                             shouldValidate: true,
                                          });
                                       }}
                                       id="industry"
                                       options={IndustryTypeSelect}
                                       error={errors.industry?.message}
                                    />
                                 )}
                                 rules={{
                                    required:
                                       optionalFields && optionalFields.includes('industry')
                                          ? false
                                          : translate({ id: 'validation:required' }),
                                 }}
                              />
                           </div>
                        </div> */}
                                 {/* interests */}
                                 {/* <div className="row">
                           <div className="self-center md:mb-5 md:col-3">
                              <Label
                                 id="interests"
                                 isRequired={
                                    optionalFields && optionalFields.includes('interests')
                                       ? false
                                       : true
                                 }
                                 label={translate({ id: 'web:interests' })}
                              />
                           </div>
                           <div className="md:col-9">
                              <Controller
                                 name="interests"
                                 control={control}
                                 render={() => (
                                    <CustomSelect
                                       value={
                                          GenericOptionsSelect.find(
                                             item => item.value === getValues()['interests']
                                          ) || ''
                                       }
                                       placeholder={translate({
                                          id: 'web:select_interests',
                                       })}
                                       onChange={(value: any) => {
                                          setValue('interests', String(value?.value), {
                                             shouldValidate: true,
                                          });
                                       }}
                                       id="interests"
                                       options={GenericOptionsSelect}
                                       error={errors.interests?.message}
                                    />
                                 )}
                                 rules={{
                                    // required: translate({
                                    //    id: 'validation:required',
                                    // }),
                                    required:
                                       optionalFields && optionalFields.includes('interests')
                                          ? false
                                          : translate({ id: 'validation:required' }),
                                 }}
                              />
                           </div>
                        </div> */}

                                 {/* interests */}
                                 {/* <CheckboxInput
                           label={translate({ id: 'web:interests' })}
                           isRequired
                           isInline
                           options={GenericOptionsSelect}
                           id="interests"
                           error={errors.interests?.message}
                           {...register('interests', {
                              required: translate({ id: 'validation:required' }),
                           })}
                        /> */}

                                 {/* city */}
                                 {/* <CustomInput
                           label={translate({ id: 'web:city' })}
                           type="text"
                           autoComplete="off"
                           // disabled={!!user && role !== 'xrole-name'}
                           placeHolder={translate({ id: 'web:city' })}
                           id="city"
                           // isRequired
                           isInline
                           error={errors.city?.message}
                           {...register('city', {
                              required: false,
                           })}
                        /> */}

                                 {/* email */}
                                 <CustomInput
                                    label={translate({ id: 'web:email' })}
                                    type="email"
                                    // disabled={!!user && role == 'xrole-name'}
                                    isRequired
                                    isInline
                                    placeHolder={translate({ id: 'web:email' })}
                                    id="email"
                                    disabled={
                                       // guestEmail !== null ||
                                       getValues('is_email_verified') === 'yes'
                                    }
                                    error={errors.email?.message}
                                    {...register('email', {
                                       required: translate({ id: 'validation:required' }),
                                       // value: guestEmail,
                                       validate: {
                                          trim: (value: any) =>
                                             value == value.trim() || 'يرجى حذف المسافات',
                                          isEmail: value =>
                                             validator.isEmail(value || '') ||
                                             translate({ id: 'validation:not_email' }),
                                          isUnique: async value => {
                                             const { isUnique, status } = await isUniqueAttribute(
                                                'guests',
                                                'email',
                                                value,
                                                'create',
                                                getValues('id')
                                             );
                                             if (!isUnique && status === 422) {
                                                return translate({ id: 'validation:unique_email' });
                                             } else if (!isUnique) {
                                                return translate({
                                                   id: 'validation:unique_email_failed',
                                                });
                                             } else {
                                                return true;
                                             }
                                          },
                                       },
                                    })}
                                 />
                                 {/* phone (single field with flags + masking; stores E.164 in `phone`) */}
                                 <Controller
                                    name="phone"
                                    control={control}
                                    rules={{
                                       required: translate({ id: 'validation:required' }),
                                       validate: (v?: string | null) => {
                                          const s = (v ?? '').replace(/\s+/g, '');
                                          const pn = parsePhoneNumberFromString(s);
                                          return pn?.isValid()
                                             ? true
                                             : translate({ id: 'validation:invalid_phone' });
                                       },
                                    }}
                                    render={({ field }) => (
                                       <PhoneInputV2
                                          lang={lang}
                                          label={translate({ id: 'web:phone' })}
                                          isInline
                                          isRequired
                                          defaultCountry="sa"
                                          // onlyCountries={ONLY_COUNTRIES}
                                          value={field.value ?? ''}
                                          onChange={field.onChange}
                                          // show error only after touch or submit
                                          error={errors.phone?.message}
                                       />
                                    )}
                                 />
                                 <div className="mt-10">
                                    <div className="row justify-end">
                                       <div className="col-6 sm:col-3">
                                          <SubmitBtn
                                             id="submit-btn" //* for test cases
                                             loading={loading}
                                             className="w-full overflow-hidden rounded-md bg-primary p-3"
                                             text={`${translate({ id: `web:next` })}`}
                                          />
                                       </div>
                                    </div>
                                 </div>
                              </form>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </React.Fragment>
   );
};

export default MissingDataSections;
