import classNames from 'classnames';
import { Translate } from '~/i18n';

/******************************************************************
 *
 *  THIS COMPONENT WAS GENERATED BY NEXTCRAZY-CLI
 *
 ******************************************************************/

const WringTokenSections = () => {
   return (
      <div className="container relative py-10">
         <div className="row">
            <div className="lg:col-8 lg:offset-2 xl:col-8 xl:offset-2">
               <div className="rounded-lg border bg-white shadow-[0px_7px_29px_0px_rgba(100,100,111,0.2)]">
                  <div className="p-6  sm:p-12">
                     <h2
                        className={classNames(
                           'mt-3 text-center text-xl font-bold capitalize text-gray-800  md:text-2xl'
                        )}>
                        <Translate id="web:sorry_wrong_link" />
                     </h2>
                     <p className="mt-4 text-center">
                        <Translate id="web:you_either_visited_the_wrong_link_or_link_is_expired" />
                     </p>
                  </div>
               </div>
            </div>
         </div>
      </div>
   );
};

export default WringTokenSections;
